### ISSUE TITLE
Browser Extension for Media Detection and Download

### ISSUE THREAD

**Issue by NoobGajen** [NickvisionApps/Parabolic#1000]
Is there a plan to add a feature like IDM or XDM? This would include a browser extension that watches web pages and detects media like videos or audio. When media is found, it could show a button to download it directly.  
 

### Key Features:  
- Detect media on web pages (e.g., videos or audio) and display a download button.  
- Allow users to download media in various formats, such as MP4 or MP3.  
- Integrate directly with Parabolic to handle downloads.  
- Provide an option to enable or disable the extension for specific sites.  
- Ensure compatibility with popular browsers like Chrome and Firefox.

**Comment by nlogozzo** [comment]
I don't have the skill/want to build and manage browser extensions.

You can use something like https://addons.mozilla.org/en-US/firefox/addon/open-with/ and have it open Parabolic with `flatpak run org.nickvision.tubeconverter` if installed via Flatpak or `C:\Program Files (x86)\Nickvision Parabolic\Release\org.nickviison.tubeconverter.qt.exe` if installed on Windows to open the application and send it a URL via CLI.
