### ISSUE TITLE
Ютуб Ошибка загрузки

### ISSUE THREAD

**Issue by Badylai** [NickvisionApps/Parabolic#1006]
winsows 11 запущено от имени администратора. Закрывается, загрузка не завершена
![image](https://github.com/user-attachments/assets/4d64e787-0033-4533-a50f-af4d29edcde4)

**Comment by nlogozzo** [comment]
I don't understand what the issue is.

**Comment by Badylai** [comment]
Рассказываю.
Открываю приложение.
Добавляю ссылку ютуб.
Начинается скачивание
При завершении загрузки приложение закрывается.
Открыв приложение заново, нет завершенных загрузок, нет файлов которые должны были загрузиться.

**Comment by Badylai** [comment]
Заработала предыдущая версия.
