### ISSUE TITLE
[Possible Bug] yt-dlp runs on the background even after clicking "Stop"

### ISSUE THREAD

**Issue by AuroraMartell** [NickvisionApps/Parabolic#1008]
Per the title. The current parabolic version keeps downloading the video (with yt-dlp running on the background) even after you click on the stop button. I think this might be a bug.

**Comment by nlogozzo** [comment]
Are you on Windows? If so duplicate of #805

**Comment by AuroraMartell** [comment]
> Are you on Windows? If so duplicate of #805

Yes, I'm on Windows. Will there be a fix?

**Comment by nlogozzo** [comment]
> Will there be a fix?

As soon as I can figure it out, yes.

**Comment by AuroraMartell** [comment]
> > Will there be a fix?
> 
> As soon as I can figure it out, yes.

Neat! I love this software.

**Comment by nlogozzo** [comment]
@AuroraMartell [V2025.1.0](https://github.com/NickvisionApps/Parabolic/releases/tag/2025.1.0) is here with a fix for this issue!

**Comment by AuroraMartell** [comment]
> @AuroraMartell [V2025.1.0](https://github.com/NickvisionApps/Parabolic/releases/tag/2025.1.0) is here with a fix for this issue!

Will test and report back. Thanks, Nick!
