### ISSUE TITLE
No sound after downloading MP4 File

### ISSUE THREAD

**Issue by Maanyaaz** [NickvisionApps/Parabolic#1009]
I have attached the video of what happens. This is on my laptop. The processing bar disappears without any indication and the MP4 file has no sound. The system details are also attached. Please help. 

https://github.com/user-attachments/assets/b0a67fc5-08d5-44a0-941a-bffdfd54a432

![para 2](https://github.com/user-attachments/assets/08d55389-fa39-4f2c-9828-83177e4b2e54)
![para 1](https://github.com/user-attachments/assets/bab33a8c-ce22-4512-8654-5aef185967d1)

**Comment by nlogozzo** [comment]
The progress bar did not disappear. The download was completed therefore it moved to the `Completed` section.

As far as no audio, Windows Media Player has very limited codec support and this cannot play the audio file. Try installing and opening the file in VLC and you will see it works without issue.
