### ISSUE TITLE
AUR package should list yt-dlp and aria2 as dependencies?

### ISSUE THREAD

**Issue by BettaGeorge** [NickvisionApps/Parabolic#1011]
If you install the `parabolic-qt` or `parabolic-gtk` package (and its dependencies) from the AUR (version is tagged as 2024.12.1), then the GUI opens, but all buttons are greyed out except the "Add Credential" button in the "Keyring" tab, so the program is unusable. Upon start, parabolic does complain that `yt-dlp` and `aria2` are missing, but this is quickly drowned out by the usual onslaught of QT messages. Should those two not be listed as dependencies?

![image](https://github.com/user-attachments/assets/9eb70e52-6e2b-48be-bdf9-42f8b3058083)

**Comment by nlogozzo** [comment]
They should be dependencies. But we do not manage the AUR package. Please leave a comment on the AUR itself.
