### ISSUE TITLE
AUR version does not correctly register its command

### ISSUE THREAD

**Issue by BettaGeorge** [NickvisionApps/Parabolic#1013]
The current package in the AUR, for both the QT and the GTK version, is flagged as providing the command `tube-converter`, but the executable is actually hidden in `/usr/lib/org.nickvision.tubeconverter/org.nickvision.tubeconverter.qt` (or `.gtk`) and not linked into `/usr/bin`. Install was done once via `makepkg -si` and once by manually building the package and installing via `pacman -U`.

**Comment by nlogozzo** [comment]
We do not manage the AUR package. Please leave a comment on the AUR itself.
