### ISSUE TITLE
Unable to open Help page

### ISSUE THREAD

**Issue by rene-coty** [NickvisionApps/Parabolic#424]
When clicking 'Help' in the menu button, the following page appears:
![Capture d’écran du 2023-07-01 10-58-25](https://github.com/NickvisionApps/Parabolic/assets/95506494/c00d1c06-ff4e-4e92-87fb-2465231edb7b)
Translation : "Document not found", "The URI [help:tubeconverter/index] doesn't refer to a valid page"

**Comment by nlogozzo** [comment]
What language is this? French?

**Comment by fsobolev** [comment]
> What language is this? French?

I think the language doesn't matter, I suppose the problem is that the link to documentation in code should be `help:parabolic`, not `help:tubeconverter` (I didn't check it yet tho).

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Parabolic/releases/tag/2023.7.0

*Should get the update from flathub/snap in a little bit*
