### ISSUE TITLE
Option to allow only Windows supported characters in filenames

### ISSUE THREAD

**Issue by fsobolev** [NickvisionApps/Parabolic#441]
Suggested in Matrix chat.

>  I just wanted to say an option to limit characters to the windows range would be useful (Parabolic)
I don't necessarily use Windows but android also doesn't support such characters for some reason, and I was wondering why mtp crashed

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Parabolic/releases/tag/2023.7.2-rc1
