### ISSUE TITLE
Proposition: allow to choose the langage of the video

### ISSUE THREAD

**Issue by Philetjosie** [NickvisionApps/Parabolic#444]
On Arte.tv website, (and probably on many others), videos are proposed on different languages, usually original language and some others. It would be really helpfull to be able to chose which langage Parabole will download. 
Thanks a lot for this wonderful software. Latest release has fix the problem of huge processor usage, which was previously freezing my computer.

**Comment by nlogozzo** [comment]
Ah so like choosing the audio of the video? Gotta see how yt-dlp allows for this selection.

**Comment by fsobolev** [comment]
> Ah so like choosing the audio of the video? Gotta see how yt-dlp allows for this selection.

It allows to select language when specifying a format, for example `ba[language=de]`. The question is how to detect when there are multiple audio tracka with different languages.

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Parabolic/releases/tag/2023.7.2-rc1
