### ISSUE TITLE
[Feature Request] Searchable download history

### ISSUE THREAD

**Issue by rubiojr** [NickvisionApps/Parabolic#453]
It'd be nice to store download history and make it searchable, so we can quickly search and open previously downloaded videos.

(Bonus points for keeping it in a documented format or sqlite file :smile: that can be used from other apps/scripts).

I currently store all downloaded videos in a local folder, so I can use the CLI or Nautilus to search and open them, but this currently lacks advanced search capabilities than an integrated solution storing video metadata would give us, I think.

Props for the amazing app :sparkles:

**Comment by nlogozzo** [comment]
![image](https://github.com/NickvisionApps/Parabolic/assets/17648453/c11b1b2f-58e7-43d5-acb0-5fb5c9eae31c)

Download history has been merged into main! RC1 release will probably come tomorrow with this feature :)


Download history is saved in a json file called `downloadHistory.json` in the app's config directory (same place as `config.json`)

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Parabolic/releases/tag/2023.7.3-rc1
