### ISSUE TITLE
duplicate AUR package created by AutoUpdateBot

### ISSUE THREAD

**Issue by apandada1** [NickvisionApps/Parabolic#465]
This AUR package was recently created by AutoUpdateBot https://aur.archlinux.org/packages/tube-converter

Perhaps the bot does not know that tube-converter has been renamed to parabolic?

**Comment by fsobolev** [comment]
@bordam

**Comment by bordam** [comment]
Yes, I’ll have to make a PR for AutoUpdateBot. I’ll do that in a couple of days

**Comment by bordam** [comment]
Ok, the PR was accepted. Now we'll have to wait for the request to be accepted in the AUR

**Comment by nlogozzo** [comment]
Closing this as it's now in the hands of the Arch gods 😆
