### ISSUE TITLE
[Feature Request] Ability to select all or deselect all when downloading playlists

### ISSUE THREAD

**Issue by Nikko-A** [NickvisionApps/Parabolic#478]
Given that I update the videos I download frequently, I need to be able to download only a specific number of videos in playlists, but I can't deselect everything in bulk. Alternatively, I also can't choose to select all. I would just like to ask if a feature can be implemented that would be able to address these, thanks!

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Parabolic/releases/tag/2023.8.0-rc1
