### ISSUE TITLE
Feature Request: An ability to turn off history

### ISSUE THREAD

**Issue by Karol739** [NickvisionApps/Parabolic#488]
I think it's a good idea to provide users with new settings function to completely turn off saving downloads history in Parabolic. Then, in History dialog, a message "History is empty" and (maybe?) Adw.Banner with an ability to quickly turn on this function (or just a link to app preferences) may pop up.

Have a good day!

**Comment by fsobolev** [comment]
The same question as in request to disable pasting from clipboard: why?

**Comment by nlogozzo** [comment]
> why?

agreed...i see no point in this.
