### ISSUE TITLE
Best quality mp3 bitrate is 128 kb/s

### ISSUE THREAD

**Issue by J-Kappes** [NickvisionApps/Parabolic#507]
Maybe this doesn't make a difference due to the source quality but I think I hear a difference between what I get with Parabolic and what I get with `yt-dlp --extract-audio --audio-format mp3 --audio-quality 2`. The former yields a bitrate of 128 kb/s while the latter yields a variable bitrate with an average of 201 kb/s. That still isn't technically the best quality but it's good enough for me.

**Comment by fsobolev** [comment]
I think we could set `--audio-quality` to 0 (best).
But out of curiosity... Why not downloading audio without conversion to avoid quality loss?

**Comment by J-Kappes** [comment]
> But out of curiosity... Why not downloading audio without conversion to avoid quality loss?

To save disk space at no perceivable loss of quality. I haven't found any credible source suggesting that people can hear the difference between uncompressed and >192 kb/s mp3, that's why I stick to ~192 kb/s mp3s for the bulk of my library, especially on my phone which I use with budget ear phones. Even my desk speakers probably aren't nearly as good as the equipment used in [this study](https://www.researchgate.net/profile/Amandine-Pras/publication/257068576_Subjective_Evaluation_of_MP3_Compression_for_Different_Musical_Genres/links/00b4952459dc60f9a1000000/Subjective-Evaluation-of-MP3-Compression-for-Different-Musical-Genres.pdf) concluding that one can still hear the difference at 192 kb/s.

**Comment by nlogozzo** [comment]
Please test this release and let us know how it goes:

https://github.com/NickvisionApps/Parabolic/releases/tag/2023.8.1-beta1

**Comment by J-Kappes** [comment]
It works. I got a variable bit rate with an average of 272 kb/s.

**Comment by HironoKenta** [comment]
IDK if something broken again, I get 128kbps for mp3, but 300+ kbps for m4a (likely reencoded from opus f 251), I just selected MP3 (Audio) and left quality on Best.

Is possible to list qualities profiles by other than bitrate value? (like i.e. Opus 128, AAC 128 etc.)
And also make it remember the choice? As I get the yt-dlp postprocessor doesn't reencode it if the input and output formats matches, so one can download m4a/aac or opus without any quality loss.

I know not all platforms and videos stream the same codec/format, but it can be made it to "prefer" the previous chosen one if present and go to best alternative if not.

**Comment by nlogozzo** [comment]
> IDK if something broken again, I get 128kbps for mp3, but 300+ kbps for m4a (likely reencoded from opus f 251), I just selected MP3 (Audio) and left quality on Best.
> 
> Is possible to list qualities profiles by other than bitrate value? (like i.e. Opus 128, AAC 128 etc.) And also make it remember the choice? As I get the yt-dlp postprocessor doesn't reencode it if the input and output formats matches, so one can download m4a/aac or opus without any quality loss.
> 
> I know not all platforms and videos stream the same codec/format, but it can be made it to "prefer" the previous chosen one if present and go to best alternative if not.

I believe this is what https://github.com/NickvisionApps/Parabolic/issues/965 is requesting.

**Comment by HironoKenta** [comment]
IDK @ricardouk (as I get) intended to match container/video/audio formats as mp4/x264/aac and mkv/av1(or vp9)/opus(or vorbis), to maybe mitigate some compatibly issues on players.

I intended to replace the "bitrate way" of list the avaiable audio formats with the codec + bitrate one, and make that choice to be remember and reapplied in future, but maybe also something like "m4a is selected so use f 140 if avaiable" (the same for opus) can work too. (btw I'll prefer to reencode opus->mp3(or vorbis) as it usually shows better quality than aac, while IIRC yt-dlp's "best audio" will only prefer the higher bitrate one)

Anyway I reply to this issue thread coz I get a 128kbps mp3, even when quality was on default Best.

Do you want me to open a separate ticket for the aforementioned enhancement?

**Comment by nlogozzo** [comment]
> Do you want me to open a separate ticket for the aforementioned enhancement?

Yes please
