### ISSUE TITLE
Time frame download process faulty

### ISSUE THREAD

**Issue by ElFrogster** [NickvisionApps/Parabolic#509]
The download of a specified time frame option does not seem to fully work. It seems to generate a faulty file or at least cannot be properly played with the two programs I tried it with (VLC media player, Footage, both as Flatpak).
Trying to play it via VLC offers some information that might help figuring out what is going on. The video is shown to have the length of the entire video (not just the length of whatever time frame you downloaded it as) and it starts playing the audio of the video (but only of the time frame you downloaded) once that audio segment has been passed, the video stops entirely (even though it's supposed to have the length of the full video, according to VLC). So I suspect that the issue might not be with the download process itself, but maybe with some faulty metadata that still claim the video has the duration of the full video, which then throws the video software for a loop.

**Comment by fsobolev** [comment]
Could you give a link that you tried to download?

**Comment by ElFrogster** [comment]
Sure:

https://youtu.be/htUsOp0Wlfg

example time frame 23:40 to 24:10, but anything should work,

Although when I tried it with this one the issue of the wrong video duration shown did not show up, it showed the correct length. But the video was still only audio.

**Comment by ElFrogster** [comment]
I also tried a longer time frame (sth like 8:30 to 10:20 and the issue of the full length being shown did crop up again. Odd.

**Comment by fsobolev** [comment]
I tried to download part of video using yt-dlp and indeed `bestvideo+bestaudio` cases audio-only file, while 720p worked as expected, seems like there are some limitations on what can be partially downloaded, need to investigate.

**Comment by fsobolev** [comment]
Okay, I figured out something. This video is available in multiple codecs:

```
270 mp4   1920x1080   30    │ ~966.29MiB 5150k m3u8  │ avc1.640028   5150k video only
137 mp4   1920x1080   30    │  584.29MiB 3190k https │ avc1.640028   3190k video only          1080p, mp4_dash
614 mp4   1920x1080   30    │ ~481.95MiB 2569k m3u8  │ vp09.00.40.08 2569k video only
248 webm  1920x1080   30    │  285.54MiB 1559k https │ vp09.00.40.08 1559k video only          1080p, webm_dash
616 mp4   1920x1080   30    │ ~  1.05GiB 5750k m3u8  │ vp09.00.40.08 5750k video only          Premium
```

And `bestvideo` is 616, mp4 with vp09, which causes video not to download, it can't be downloaded partially.
137 and 248 both work okay more or less... They get downloaded, but there's still something wrong with time: in Clapper audio starts a couple of seconds before video, in Celluloid file plays normally but can't be precisely seeked.
I think we could make Parabolic avoid downloading mp4 with vp09 for partial downloads, but timing issue... I don't think we can do anything with this.

**Comment by nlogozzo** [comment]
Please test this release and let us know how it goes:

https://github.com/NickvisionApps/Parabolic/releases/tag/2023.8.1-beta1
