### ISSUE TITLE
"No active internet connection" message when connection is available

### ISSUE THREAD

**Issue by mishrashutosh** [NickvisionApps/Parabolic#512]
I just installed Parabolic from Flathub on a fresh Fedora setup, and I see a message that says "no active internet connection".

Debug information:

```
org.nickvision.tubeconverter
2023.8.0
GTK 4.10.4
libadwaita 1.3.3
Flatpak
yt-dlp 2023.07.06
psutil 5.9.5
ffmpeg version 6.0
aria2 version 1.36.0
en-IN
LANG=en_IN.UTF-8
LC_CTYPE="en_IN.UTF-8"
LC_NUMERIC="en_IN.UTF-8"
LC_TIME="en_IN.UTF-8"
LC_COLLATE="en_IN.UTF-8"
LC_MONETARY="en_IN.UTF-8"
LC_MESSAGES="en_IN.UTF-8"
LC_PAPER="en_IN.UTF-8"
LC_NAME="en_IN.UTF-8"
LC_ADDRESS="en_IN.UTF-8"
LC_TELEPHONE="en_IN.UTF-8"
LC_MEASUREMENT="en_IN.UTF-8"
LC_IDENTIFICATION="en_IN.UTF-8"
LC_ALL=

```

![Screenshot from 2023-08-04 00-43-16](https://github.com/NickvisionApps/Parabolic/assets/6448741/a02ec2ad-ef41-45c1-ac65-0996a9d22cdb)

![Screenshot from 2023-08-04 00-48-41](https://github.com/NickvisionApps/Parabolic/assets/6448741/181abc78-0e08-4ee5-ac9d-603a4dbd22e1)

Please let me know if you need any other info.

**Comment by fsobolev** [comment]
Fixed in https://github.com/flathub/org.nickvision.tubeconverter/pull/97, the update should be available soon

**Comment by nlogozzo** [comment]
Yes just released the fix....the update has been published so you probably should get it in literally 5 minutes 😆

**Comment by mishrashutosh** [comment]
Ah that's awesome! thank you!
