### ISSUE TITLE
"No active internet connection" in Parabolic

### ISSUE THREAD

**Issue by TreeTox** [NickvisionApps/Parabolic#518]
Everything has been working fine. No config changes eg via Flatseal but since latest update, unable to download anything, with message, "No active internet connection"

![sc](https://github.com/NickvisionApps/Parabolic/assets/74877855/8bcd92f3-10d3-453d-ad7c-ee920f24fa96)

**Comment by nlogozzo** [comment]
Are you running flatpak or snap?

Can you please run `flatpak update` to double check for am update as we released a patched version to fix this...

**Comment by nlogozzo** [comment]
If your still facing issues, can you try V2023.8.1-beta1: https://github.com/NickvisionApps/Parabolic/releases/tag/2023.8.1-beta1

**Comment by TreeTox** [comment]
Thanks for getting back to me so fast!
Running a flatpak. Tried snap too - same message.
Also tried the beta, exactly the same.

![sc2](https://github.com/NickvisionApps/Parabolic/assets/74877855/aefad4b7-dfaf-46c5-b9fa-a60e9c08e169)

**Comment by nlogozzo** [comment]
Hmmm...what distro are you running? What version? Are you using a VPN or some other network?

**Comment by dtfleetwood** [comment]
Seeing this as well, on Fedora 38.

**Comment by nlogozzo** [comment]
> Seeing this as well, on Fedora 38.

GNOME or KDE?

**Comment by nlogozzo** [comment]
@dtfleetwood Also are you using a VPN or something like that?

**Comment by dtfleetwood** [comment]
No VPN, wired network to router to internet.

**Comment by dtfleetwood** [comment]
Oh and Gnome, sorry I missed that question.

**Comment by nlogozzo** [comment]
> If your still facing issues, can you try V2023.8.1-beta1: https://github.com/NickvisionApps/Parabolic/releases/tag/2023.8.1-beta1

@dtfleetwood Could you try the beta as well?

**Comment by dtfleetwood** [comment]
Still no network.

**Comment by fsobolev** [comment]
Could you please run this command and provide the result?

```
dbus-send --system --type=method_call --dest=org.freedesktop.NetworkManager --print-reply /org/freedesktop/NetworkManager org.freedesktop.DBus.Properties.Get string:'org.freedesktop.NetworkManager' string:'State'
```

And also please enter the app's sandbox (I assume you use flatpak?)

```
flatpak run --command=sh org.nickvision.tubeconverter
```

and run the command above again.

**Comment by dtfleetwood** [comment]
Result from running outside the sandbox: 

dbus-send --system --type=method_call --dest=org.freedesktop.NetworkManager --print-reply /org/freedesktop/NetworkManager org.freedesktop.DBus.Properties.Get string:'org.freedesktop.NetworkManager' string:'State'
method return time=1691358583.849314 sender=:1.22 -> destination=:1.8583 serial=232619 reply_serial=2
   variant       uint32 60

From inside the sandbox: 

[📦 org.nickvision.tubeconverter ~]$ dbus-send --system --type=method_call --dest=org.freedesktop.NetworkManager --print-reply /org/freedesktop/NetworkManager org.freedesktop.DBus.Properties.Get string:'org.freedesktop.NetworkManager' string:'State'
method return time=1691358648.669602 sender=:1.22 -> destination=:1.8588 serial=232624 reply_serial=2
   variant       uint32 60

**Comment by fsobolev** [comment]
@dtfleetwood Thanks, this helps a lot

**Comment by dtfleetwood** [comment]
No problem! I installed the app for the first time just before I posted here. Happy to help out.

**Comment by nlogozzo** [comment]
> No problem! I installed the app for the first time just before I posted here. Happy to help out.

Yes, we know the fix now :) I'll try to get a beta out tonight so you can test and at least use the app!

**Comment by fsobolev** [comment]
@TreeTox If you will still have the problem in the new beta version feel free to reopen the issue and in that case please provide the output of the command I mentioned above.

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Parabolic/releases/tag/2023.8.1-beta2

@dtfleetwood Please test and let us know how it goes :)

*Should be available through `flathub-beta` in the coming minutes...make sure your on the correct version before testing

**Comment by TreeTox** [comment]
I run NordVPN but I tried it with the VPN off, and the same message. No other settings, just vanilla Fedora 38 with no complex custom firewalls or blocks.

             .',;::::;,'.                garen@Artsakh 
         .';:cccccccccccc:;,.            ------------- 
      .;cccccccccccccccccccccc;.         OS: Fedora Linux 38 (KDE Plasma) x86_64 
    .:cccccccccccccccccccccccccc:.       Host: Inspiron 5405 1.7.0 
  .;ccccccccccccc;.:dddl:.;ccccccc;.     Kernel: 6.4.7-200.fc38.x86_64 
 .:ccccccccccccc;OWMKOOXMWd;ccccccc:.    Uptime: 11 hours, 13 mins 
.:ccccccccccccc;KMMc;cc;xMMc:ccccccc:.   Packages: 1 (dpkg), 2928 (rpm), 39 (flatpak), 27 (snap) 
,cccccccccccccc;MMM.;cc;;WW::cccccccc,   Shell: bash 5.2.15 
:cccccccccccccc;MMM.;cccccccccccccccc:   Resolution: 2560x1080 
:ccccccc;oxOOOo;MMM0OOk.;cccccccccccc:   DE: Plasma 5.27.6 
cccccc:0MMKxdd:;MMMkddc.;cccccccccccc;   WM: kwin 
ccccc:XM0';cccc;MMM.;cccccccccccccccc'   WM Theme: plastik 
ccccc;MMo;ccccc;MMW.;ccccccccccccccc;    Theme: [Plasma], Breeze [GTK2/3] 
ccccc;0MNc.ccc.xMMd:ccccccccccccccc;     Icons: [Plasma], breeze-dark [GTK2/3] 
cccccc;dNMWXXXWM0::cccccccccccccc:,      Terminal: yakuake 
cccccccc;.:odl:.;cccccccccccccc:,.       CPU: AMD Ryzen 7 4700U with Radeon Graphics (8) @ 2.000GHz 
:cccccccccccccccccccccccccccc:'.         GPU: AMD ATI 03:00.0 Renoir 
.:cccccccccccccccccccccc:;,..            Memory: 6913MiB / 15337MiB 
  '::cccccccccccccc::;,.

**Comment by nlogozzo** [comment]
> I run NordVPN but I tried it with the VPN off, and the same message. No other settings, just vanilla Fedora 38 with no complex custom firewalls or blocks.
> 
> OS: Fedora Linux 38 (KDE Plasma) x86_64 Host: Inspiron 5405 1.7.0 Kernel: 6.4.7-200.fc38.x86_64 Uptime: 11 hours, 13 mins Packages: 1 (dpkg), 2928 (rpm), 39 (flatpak), 27 (snap) Shell: bash 5.2.15 Resolution: 2560x1080 DE: Plasma 5.27.6 WM: kwin WM Theme: plastik heme: [Plasma], Breeze [GTK2/3] Icons: [Plasma], breeze-dark [GTK2/3] Terminal: yakuake CPU: AMD Ryzen 7 4700U with Radeon Graphics (8) @ 2.000GHz GPU: AMD ATI 03:00.0 Renoir Memory: 6913MiB / 15337MiB

Thanks for the info...Please try beta2: https://github.com/NickvisionApps/Parabolic/releases/tag/2023.8.1-beta2

**Comment by TreeTox** [comment]
> > I run NordVPN but I tried it with the VPN off, and the same message. No other settings, just vanilla Fedora 38 with no complex custom firewalls or blocks.
> > OS: Fedora Linux 38 (KDE Plasma) x86_64 Host: Inspiron 5405 1.7.0 Kernel: 6.4.7-200.fc38.x86_64 Uptime: 11 hours, 13 mins Packages: 1 (dpkg), 2928 (rpm), 39 (flatpak), 27 (snap) Shell: bash 5.2.15 Resolution: 2560x1080 DE: Plasma 5.27.6 WM: kwin WM Theme: plastik heme: [Plasma], Breeze [GTK2/3] Icons: [Plasma], breeze-dark [GTK2/3] Terminal: yakuake CPU: AMD Ryzen 7 4700U with Radeon Graphics (8) @ 2.000GHz GPU: AMD ATI 03:00.0 Renoir Memory: 6913MiB / 15337MiB
> 
> Thanks for the info...Please try beta2: https://github.com/NickvisionApps/Parabolic/releases/tag/2023.8.1-beta2

Amazing - I can confirm the beta has now worked!
You guys have been very quick , very fast turnaround.

**Comment by nlogozzo** [comment]
> Amazing - I can confirm the beta has now worked!

Glad it works!!!

> You guys have been very quick , very fast turnaround.

Thank you to all of you for using our apps and working with us to find these bugs and fix them :)

--

Stable release should be out by the end of the week

**Comment by dtfleetwood** [comment]
> https://github.com/NickvisionApps/Parabolic/releases/tag/2023.8.1-beta2
> 
> @dtfleetwood Please test and let us know how it goes :)
> 
> *Should be available through `flathub-beta` in the coming minutes...make sure your on the correct version before testing

Can confirm it's working on my system! Sorry for the delay, I'm on Lisbon time. Great job and quick turnaround, thanks everyone!

**Comment by cassiofb-dev** [comment]
I'm with this issue, is this fix only in the beta?

**Comment by nlogozzo** [comment]
@cassiofb-dev This was fixed in stable about a month ago....what version of Parabolic are you running? Is it the latest 2023.8.3?

**Comment by cassiofb-dev** [comment]
I think so, I just installed from flathub. I'll provide debug info bellow:

```txt
org.nickvision.tubeconverter
2023.8.3
GTK 4.10.4
libadwaita 1.3.3
Flatpak
yt-dlp 2023.07.06
psutil 5.9.5
ffmpeg version 6.0
aria2 version 1.36.0
en-US
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```

**Comment by fsobolev** [comment]
Could you please provide an output of commands I mentioned in [this comment](https://github.com/NickvisionApps/Parabolic/issues/518#issuecomment-1666975323)?

**Comment by nlogozzo** [comment]
@cassiofb-dev Could you open the terminal and run these 2 commands and provide the output:
```
flatpak run --command=sh org.nickvision.tubeconverter
dbus-send --system --type=method_call --dest=org.freedesktop.NetworkManager --print-reply /org/freedesktop/NetworkManager org.freedesktop.DBus.Properties.Get string:'org.freedesktop.NetworkManager' string:'State'
```
This will tell us how Parabolic sees your internet connection...

**Comment by nlogozzo** [comment]
> Could you please provide an output of commands I mentioned in [this comment](https://github.com/NickvisionApps/Parabolic/issues/518#issuecomment-1666975323)?

Beat me too it 😅

**Comment by cassiofb-dev** [comment]
Okay, here is the output:

```txt
localhost:~$ flatpak run --command=sh org.nickvision.tubeconverter
[📦 org.nickvision.tubeconverter ~]$ dbus-send --system --type=method_call --dest=org.freedesktop.NetworkManager --print-reply /org/freedesktop/NetworkManager org.freedesktop.DBus.Properties.Get string:'org.freedesktop.NetworkManager' string:'State'
method return time=1693761470.055625 sender=:1.3 -> destination=:1.174 serial=332 reply_serial=2
   variant       uint32 50
[📦 org.nickvision.tubeconverter ~]$
```

**Comment by nlogozzo** [comment]
@fsobolev `ConnectedLocal`...hmm

@cassiofb-dev Are you using a VPN or in an enterprise network or something?

**Comment by cassiofb-dev** [comment]
> @fsobolev `ConnectedLocal`...hmm
> 
> @cassiofb-dev Are you using a VPN or in an enterprise network or something?

No, just normal network. Other flatpak apps can access internet (I'm using flatpak firefox too).

**Comment by nlogozzo** [comment]
> No, just normal network. Other flatpak apps can access internet (I'm using flatpak firefox too).

Ok, no worries. Just that your system reports the connection as a "local" connection instead of a "global" one....but no worries will be fixed in this week's stable release :) Use #569 to track

**Comment by cassiofb-dev** [comment]
> > No, just normal network. Other flatpak apps can access internet (I'm using flatpak firefox too).
> 
> Ok, no worries. Just that your system reports the connection as a "local" connection instead of a "global" one....but no worries will be fixed in this week's stable release :) Use #569 to track

Thanks, I use yt-dlp sometimes and a GUI would help me a lot 🙏

**Comment by cassiofb-dev** [comment]
@nlogozzo worked like a charm thanks!

![image](https://github.com/NickvisionApps/Parabolic/assets/61878987/7199c68e-1d73-4109-8a1e-505bb3bfa7f0)

**Comment by cassiofb-dev** [comment]
@nlogozzo sorry to trouble you again but the message is back.

**Comment by nlogozzo** [comment]
@cassiofb-dev has anything about your internet connection changed? Ethernet to wifi? Start using a VPN?

**Comment by nlogozzo** [comment]
CC @fsobolev

**Comment by cassiofb-dev** [comment]
No, just ethernet. A issue I'm also having now is with github.io domain but all other things in internet are ok.

**Comment by nlogozzo** [comment]
> Okay, here is the output:
> 
> ```txt
> localhost:~$ flatpak run --command=sh org.nickvision.tubeconverter
> [📦 org.nickvision.tubeconverter ~]$ dbus-send --system --type=method_call --dest=org.freedesktop.NetworkManager --print-reply /org/freedesktop/NetworkManager org.freedesktop.DBus.Properties.Get string:'org.freedesktop.NetworkManager' string:'State'
> method return time=1693761470.055625 sender=:1.3 -> destination=:1.174 serial=332 reply_serial=2
>    variant       uint32 50
> [📦 org.nickvision.tubeconverter ~]$
> ```

@cassiofb-dev could you run this command again and provide us with the new output

**Comment by cassiofb-dev** [comment]
Hmm... Strange, the output changed. Here is it:

```txt
[📦 org.nickvision.tubeconverter ~]$ dbus-send --system --type=method_call --dest=org.freedesktop.NetworkManager --print-reply /org/freedesktop/NetworkManager org.freedesktop.DBus.Properties.Get string:'org.freedesktop.NetworkManager' string:'State'
Failed to open connection to "system" message bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[📦 org.nickvision.tubeconverter ~]$
```

**Comment by nlogozzo** [comment]
@fsobolev Any idea what's going on?

**Comment by fsobolev** [comment]
> @fsobolev Any idea what's going on?

We use portal now instead of asking NetworkManager directly, the permission was removed because it's not needed anymore and so the old command doesn't give any result inside flatpak.
The portal doesn't give network status like NetworkManager does, `GetAvailable` returns only boolean whether the network is available, so we can't now control what state should be considered as available network.
I looked what it does under the hood, and it treats [`ConnectedLocal` as no available network](https://github.com/GNOME/glib/blob/main/gio/gnetworkmonitornm.c#L194). No surprise, because [according to docs](https://developer-old.gnome.org/NetworkManager/stable/nm-dbus-types.html#NMState) it should indeed be treated like so.

> There is only local IPv4 and/or IPv6 connectivity, but no default route to access the Internet. The graphical shell should indicate no network connectivity.

So from the start it's not the bug on our side, but it seems in network manager that gives `ConnectedLocal` status while there is a full internet connection.

**Comment by nlogozzo** [comment]
@cassiofb-dev so then I'd open a bug here: https://gitlab.freedesktop.org/NetworkManager/NetworkManager and state that you have full network connectivity and access but NetworkManager is saying you are ConnectedLocal instead of ConnectedGlobal.

What does GNOME shell's network icon say in the top panel to the right? Does it show full connectivity?

**Comment by cassiofb-dev** [comment]
@nlogozzo I think you got the issue. Even Gnome can't use my network, its really strange because the browser and multiplayer games are fine:

![image](https://github.com/NickvisionApps/Parabolic/assets/61878987/7238eed1-598c-4db5-bc00-cf6afaa29a5b)

**Comment by nlogozzo** [comment]
> @nlogozzo I think you got the issue. Even Gnome can't use my network, its really strange because the browser and multiplayer games are fine:


Yeah so you have internet it's just the NetworkManager is telling Parabolic and other system tools that you don't. Definitely open an issue for NetworkManager.

What distro are you using?

**Comment by nlogozzo** [comment]
If anything however I will add a --nonetcheck argument that you can pass to Parabolic to bypass the network check which will still let you use the application.

Something like `flatpak run org.nickvision.tubeconverter --nonetcheck`

**Comment by cassiofb-dev** [comment]
@nlogozzo No need, the issue was on my side. Actually gnome network manager did not have permission to manage connection. I just give permissions following this guide https://wiki.debian.org/NetworkManager, it also works on alpine that also does not give permission.

Now it's working again, thanks for the patience 🙏

**Comment by nlogozzo** [comment]
> @nlogozzo No need, the issue was on my side. Actually gnome network manager did not have permission to manage connection. I just give permissions following this guide https://wiki.debian.org/NetworkManager, it also works on alpine that also does not give permission.
> 
> Now it's working again, thanks for the patience 🙏

Oh OK glad you got it fixed!!
