### ISSUE TITLE
Allow codec choice for Youtube downloads

### ISSUE THREAD

**Issue by Sesivany** [NickvisionApps/Parabolic#520]
It's possible to pick a video format (either webp or mp4) for Youtube downloads, but both encapsule VP9 which is not supported on many TVs and multimedia boxes, that's why it'd be great to be able to pick H.264 codec in which Youtube videos are also provided.

**Comment by fsobolev** [comment]
Ability to choose codec to download contradicts the current app design. Parabolic doesn't really allow to choose what to download, instead it allows to choose the format for target file. Whether media is available in this format is not user concern, conversion takes place if needed.
So what was done in #522 is that when selecting MP4 format h264/h265 will be preferred over vp8/vp9. If vp9 is still desirable codec to save disk space, there's webm format for it.

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Parabolic/releases/tag/2023.8.1-beta2
