### ISSUE TITLE
Crashes on startup on Apple silicon hardware

### ISSUE THREAD

**Issue by Donkey-Doug** [NickvisionApps/Parabolic#542]
I am running linux on an Apple M1 macbook air and Parabolic crashes on startup. I am not sure what other info you need. Let me know how I can help.

**Comment by nlogozzo** [comment]
Flatpak, snap or something else?
What distro and version?

**Comment by Donkey-Doug** [comment]
- Flatpak
- Arch linux
- ARM64 CPU
- 16K pages

Also, sometimes it does start but then it crashes later

**Comment by nlogozzo** [comment]
Can you run it in the terminal (`flatpak run org.nickvision.tubeconverter`} and see if you get any error messages?

**Comment by archismanpanigrahi** [comment]
Also, check if you face the same issue when you use the AUR package.

**Comment by nlogozzo** [comment]
@Donkey-Doug any update?

**Comment by Donkey-Doug** [comment]
Sorry for the late response. I will reply this week.

**Comment by Donkey-Doug** [comment]
I ran flatpak run org.nickvision.tubeconverter

The error is:
  
libEGL warning: egl: failed to create dri2 screen
libEGL warning: failed to get driver name for fd 0

libEGL warning: MESA-LOADER: failed to retrieve device information

libEGL warning: failed to get driver name for fd 0

**Comment by nlogozzo** [comment]
@DaPigGuy if I'm not mistaken, do you run apple silicon? Any idea?

**Comment by fsobolev** [comment]
@Donkey-Doug could you try [AUR package](https://aur.archlinux.org/packages/parabolic)?

**Comment by Donkey-Doug** [comment]
I failed to install the AUR package. See errors below:

Cloning into 'parabolic'...
remote: Enumerating objects: 36, done.
remote: Counting objects: 100% (36/36), done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 36 (delta 15), reused 36 (delta 15), pack-reused 0
Receiving objects: 100% (36/36), done.
Resolving deltas: 100% (15/15), done.

<username>@<pc name>:~ -$ cd parabolic

<username>@<pc name>:~/parabolic:master -$ makepkg -si
==> Making package: parabolic 2023.8.2-1 (do 24 aug 2023 15:52:50 CEST)
==> Checking runtime dependencies...
==> Installing missing dependencies...
[sudo] password for <username>: 
error: target not found: dotnet-runtime>=7
==> ERROR: 'pacman' failed to install missing dependencies.
==> Missing dependencies:
  -> aria2
  -> dotnet-runtime>=7
  -> python-brotli
  -> python-mutagen
  -> python-pycryptodomex
  -> python-pyxattr
  -> python-websockets
==> Checking buildtime dependencies...
==> Installing missing dependencies...
error: target not found: dotnet-sdk>=7
==> ERROR: 'pacman' failed to install missing dependencies.
==> Missing dependencies:
  -> blueprint-compiler
  -> dotnet-sdk>=7
==> ERROR: Could not resolve all dependencies.
<username>@<pc name>:~/parabolic:master 8$

**Comment by archisman-panigrahi** [comment]
Use a package manager like yay.

yay -S parabolic

**Comment by nlogozzo** [comment]
> I installed parabolic though yay, but no icon is visible except for the one that was already there as a flatpak. How do I ensure I launch the yay-installed version? Should I have deleted the flatpak first?

Just run `parabolic` in the terminal...if that doesn't work try `tube-converter` or `org.nickvision.tubeconverter` I'm not am arch user so idk what the maintainer made it.

**Comment by nlogozzo** [comment]
> So I guess it is a flatpak issue?

If it runs then yes it's a flatpak issue...idk if gtk flatpak supports Apple silicon yet

**Comment by archisman-panigrahi** [comment]
Also, if you are using Arch, then most flatpak packages are available on the AUR. The native packages from the AUR consume less space, usually launch faster (although the speedup may not be noticeable in powerful computers like Apple Silicon Mac), and easily integrate with other apps and themes.

**Comment by fsobolev** [comment]
> If it runs then yes it's a flatpak issue...idk if gtk flatpak supports Apple silicon yet

Well, the error clearly goes from Mesa, and I remember I had similar error messages with some app (not on Apple, I don't have one, just on a regular PC) when I had outdated Mesa in Flatpak, updating everything solved the issue. I don't know what was really the root of problem there, but anyway, what I want to say is that this is graphics driver issue, not Parabolic, and so nothing we can do and this issue should be closed.
