### ISSUE TITLE
Parabolic not updating

### ISSUE THREAD

**Issue by danostg** [NickvisionApps/Parabolic#545]
LinuxMint Cinnamon 21.2   Parabolic not updating via update manager
![Parabolic not updating](https://github.com/NickvisionApps/Parabolic/assets/34676884/de40f2c6-7bbe-45c7-a475-b42772ba2b3a)
please help
danostg@gmail.com

**Comment by nlogozzo** [comment]
Seems like a linux mint issue...
Did you try `flatpak update` in the terminal?

**Comment by fsobolev** [comment]
Try in terminal:

```
sudo flatpak repair
flatpak repair --user
flatpak update
```
