### ISSUE TITLE
Having trouble opening with flatpak in Linux Mint 21.2

### ISSUE THREAD

**Issue by okietech** [NickvisionApps/Parabolic#554]
I can install it, but when I try to run it won't open.

**Comment by nlogozzo** [comment]
Do you get any error message when run via the terminal? `flatpak run org.nickvision.tubeconverter`

**Comment by okietech** [comment]
error: While opening repository /home/jason/.local/share/flatpak/repo: opening repo: opendir(objects): No such file or directory

**Comment by nlogozzo** [comment]
Definitely not a Parabolic issue...can you install and run other flatpak apps?

Seems like linux mint break flatpak sometimes...see https://github.com/flatpak/flatpak/issues/3585
