### ISSUE TITLE
Option to dowload only subtitles ?

### ISSUE THREAD

**Issue by Philetjosie** [NickvisionApps/Parabolic#568]
Hello, thanks again for your great work with parabole. My suggestion is to have an option to download only subtitles for a movie. The reason is that many times, I have downloaded a movie, and have the choice between SRT or VTT subtitles. But sometimes, the one I choose does not work. Then I have to redownload everything in order to get the subtitles right. It would be much simpler to be able to download only the subtitle file so that I can test which on works. Many thanks again.

**Comment by fsobolev** [comment]
Let me guess: VTT subtitles don't work with MP4 video?
If there are any other cases, please provide info about what options to set to reproduce.

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Parabolic/releases/tag/2023.9.0-rc1
