### ISSUE TITLE
Update Aura to 2023.9.1

### ISSUE THREAD

**Issue by nlogozzo** [NickvisionApps/Parabolic#569]

**Comment by fsobolev** [comment]
Depends on https://github.com/NickvisionApps/Aura/pull/16 to fix #518

**Comment by nlogozzo** [comment]
![image](https://github.com/NickvisionApps/Parabolic/assets/17648453/b1e6795e-20d5-4de8-9ed5-9dbcdd97a7af)

Publishing now...

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Parabolic/releases/tag/2023.9.0-rc1
