### ISSUE TITLE
Not all subtitle languages are supported

### ISSUE THREAD

**Issue by suleymanboyar** [NickvisionApps/Parabolic#572]
The function `ValidateSubtitleLangs` returns false for languages that follows this form of scheme: `en-CA`. I believe the issue lies in that the list of codes is a union of ISO letters with either two or three letters. This causes to languages like `en-CA` (Canada) becomes invalid.

https://github.com/NickvisionApps/Parabolic/blob/2ab34a7388b27a5882daaf51f66c50b954eb9825/NickvisionTubeConverter.Shared/Controllers/PreferencesViewController.cs#L29-L30

**Comment by fsobolev** [comment]
Does yt-dlp support such codes? I thougth it only supports 2- and 3-letter language codes. Could you give an example of video that uses `en-CA` or similar code for subtitles?

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Parabolic/releases/tag/2023.9.0-rc1
