### ISSUE TITLE
Keep original channel name in metadata

### ISSUE THREAD

**Issue by sojusnik** [NickvisionApps/Parabolic#574]
One some videos the channel name, that gets written into the metadata, is translated into English, f.i. in [this](https://www.youtube.com/watch?v=akHMCjT9kQA) one, where the original channel name is "Первый образовательный телеканал", but the metadata shows "The first educational TV channel".

Is it possible to define to always use the original channel name, rather the translation?

**Comment by fsobolev** [comment]
A note for myself: `--extractor-args youtube:lang=LANG_CODE`

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Parabolic/releases/tag/2023.9.0-rc1
