### ISSUE TITLE
Include URL to video in metadata

### ISSUE THREAD

**Issue by sojusnik** [NickvisionApps/Parabolic#576]
It would be very convenient, if the URL to the video could be written in to the metadata. F.i. [Video Downloader](https://flathub.org/apps/com.github.unrud.VideoDownloader) already does that and puts it in the commentary field.

**Comment by fsobolev** [comment]
We explicitely [remove](https://github.com/NickvisionApps/Parabolic/issues/326) URL from metadata to clear traces of a media source.
I guess it's time for one more toggle in preferences...

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Parabolic/releases/tag/2023.9.0-rc1
