### ISSUE TITLE
[Feature Request] Center[ish]-align all dialogs

### ISSUE THREAD

**Issue by hyuri** [NickvisionApps/Parabolic#582]
Hi!

The new download dialog starts roughly centered both horizontally and vertically. But after validation, it grows downwards and becomes vertically off-centered:
![image](https://github.com/NickvisionApps/Parabolic/assets/18584014/37a466bd-77e4-4867-937f-6af0d48a2116)

It would be nice if all dialogs always remained roughly centered:
![image](https://github.com/NickvisionApps/Parabolic/assets/18584014/73e68a5a-c70b-4d36-9773-c01c6e2a61dd)

Not a big deal, just a bit annoying for people who like symmetry like me :laughing:

**Comment by hyuri** [comment]
I'm on Gnome (42.9)

**Comment by nlogozzo** [comment]
> I'm on Gnome (42.9)

Ubuntu or stock (i.e. Fedora)

**Comment by hyuri** [comment]
> > I'm on Gnome (42.9)
> 
> Ubuntu or stock (i.e. Fedora)?

Pop!_OS 22.04

**Comment by nlogozzo** [comment]
> > > I'm on Gnome (42.9)
> > 
> > Ubuntu or stock (i.e. Fedora)?
> 
> Pop!_OS 22.04

Are you using wayland or xorg? 

*You can find out from GNOME settings -> About -> Windowing System (i believe that's what it says)...either X11 or Wayland*

**Comment by hyuri** [comment]
Xorg

**Comment by fsobolev** [comment]
This is version 2023.8.3, right? Could you try latest rc (and if possible both on X11 and Wayland)? We changed this dialog to be resizable so I'm curious if this could accidentally fix the issue.

**Comment by hyuri** [comment]
Yes, 2023.8.3. I'll try it soon on X11, but I don't have Wayland installed.

**Comment by nlogozzo** [comment]
@hyuri any update?

**Comment by hyuri** [comment]
@nlogozzo Hey, sorry, got insanely busy until the 24th. I'll test it on Monday.

**Comment by hyuri** [comment]
Just tested with 2023.9.0. Still happening:

![image](https://github.com/NickvisionApps/Parabolic/assets/18584014/60e95b4d-cd8e-4746-8afd-f3733b88a3d0)

**Comment by nlogozzo** [comment]
@fsobolev Thoughts? Seems like themes being themes...

**Comment by fsobolev** [comment]
> @fsobolev Thoughts? Seems like themes being themes...

I don't think it's caused by custom theme. I will later try on Sliverblue with GNOME to see if there's the same issue on vanilla GNOME.

**Comment by nlogozzo** [comment]
@fsobolev Any luck?

**Comment by fsobolev** [comment]
GNOME 44.5, tried both X11 and Wayland, can't reproduce.
Sorry, but it seems there's something wrong with your configuration, maybe an extension causes this.
