### ISSUE TITLE
Keep subtitles as separate files if embedding failed

### ISSUE THREAD

**Issue by fsobolev** [NickvisionApps/Parabolic#597]
> Another idea would that in case of an error linked to the subtitles conversion or the subtitles embedding, the original sub file is kept (.srt or .vtt), as most media players can automatically play the video with the corresponding sub file (if it has the same name).

_Originally posted by @Philetjosie in https://github.com/NickvisionApps/Parabolic/issues/596#issuecomment-1723886807_

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Parabolic/releases/tag/2023.9.1-rc1
