### ISSUE TITLE
It seems that all arte.tv links are now considered as invalid

### ISSUE THREAD

**Issue by Philetjosie** [NickvisionApps/Parabolic#598]
I have tried to download a video from arte.tv, but Parabole says the link is invalid. I have test others arte.tv link, and get the same invalid message error. However, the links are valid.
Here are some examples:
https://www.arte.tv/fr/videos/114146-000-A/omar-m-a-tuer/
https://www.arte.tv/fr/videos/111195-000-A/face-a-face/
https://www.arte.tv/fr/videos/000430-000-A/charles-mort-ou-vif/

Strange problem ?

**Comment by fsobolev** [comment]
I assume you're running flatpak so here are the commands to test in terminal:

```
flatpak run --command=sh org.nickvision.tubeconverter
yt-dlp -F https://www.arte.tv/fr/videos/114146-000-A/omar-m-a-tuer/
```

Please provide the output.

**Comment by Philetjosie** [comment]
Hello,

sorry I'm running a snap.

Therefore, the first command gives an error:

philippe@philippe-desktop:~$ flatpak run --command=sh org.nickvision.tubeconverter
error: app/org.nickvision.tubeconverter/x86_64/master not installed

I will uninstall the snap and try with the flatpak

**Comment by Philetjosie** [comment]
Hello, I'm now running the flatpak version and here are the error messages I get:

philippe@philippe-desktop:~$ flatpak run --command=sh org.nickvision.tubeconverter
[📦 org.nickvision.tubeconverter ~]$ yt-dlp -F https://www.arte.tv/fr/videos/114146-000-A/omar-m-a-tuer/
[ArteTV] Extracting URL: https://www.arte.tv/fr/videos/114146-000-A/omar-m-a-tuer/
[ArteTV] 114146-000-A: Downloading JSON metadata
WARNING: [ArteTV] Skipping stream with unknown protocol API_HLS_NG
WARNING: [ArteTV] Skipping stream with unknown protocol API_HLS_NG
WARNING: [ArteTV] Skipping stream with unknown protocol API_HLS_NG
WARNING: [ArteTV] Skipping stream with unknown protocol API_HLS_NG
WARNING: [ArteTV] Skipping stream with unknown protocol API_HLS_NG
WARNING: [ArteTV] Skipping stream with unknown protocol API_HLS_NG
ERROR: [ArteTV] 114146-000-A: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

I check the release of yt-dlp:

[📦 org.nickvision.tubeconverter ~]$ yt-dlp -U
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)

Therefore, I will open an issue for yt-dlp. Thanks for your help.

**Comment by Philetjosie** [comment]
The bug is already reported on yt-dlp, a quick fix has been proposed.

**Comment by fsobolev** [comment]
Thanks! Yeah, seems like it's related to [this issue](https://www.github.com/yt-dlp/yt-dlp/issues/8156). We will apply the patch on next release if needed.

**Comment by Philetjosie** [comment]
Thanks a lot for your help. I have manually edited the arte.py file as proposed on the yt_dlp page, and it works again. Regards.

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Parabolic/releases/tag/2023.9.1-rc1
