### ISSUE TITLE
Parabolic no longer works as it should, after the last update.

### ISSUE THREAD

**Issue by jotakswe** [NickvisionApps/Parabolic#599]
Parabolic no longer works as it should, after the last update.
Was using the Snap version, but have switched to the AUR version, but it's the same thing there.
Can't get the subtitles when downloading the video.
During the download, I have to quickly copy the .vtt file to another place, otherwise it will be deleted, in order to get a subtitles file to use.
While troubleshooting, I saw that the operation log file was overwritten during download.
This when I used the "Disallow Conversions - OFF" parameter.
In order to be able to include everything that was done and written in the log file, I had to use a file management program to copy out the log file as it was written to it, so that it would not be overwritten.
When I used the "Disallow Conversions - ON" parameter, the log file was not overwritten, it seems, but it still didn't work as it should.
Sends various log files and other information for troubleshooting.
NOTE. The log files that I send show that the log files are changed during the download of video and subtitles.
I used "Meld" to compare the files.

[Disallow Conversions - OFF - log3-20:16:53.txt](https://github.com/NickvisionApps/Parabolic/files/12676380/Disallow.Conversions.-.OFF.-.log3-20.16.53.txt)
[Disallow Conversions - OFF - log4-20:17:03.txt](https://github.com/NickvisionApps/Parabolic/files/12676381/Disallow.Conversions.-.OFF.-.log4-20.17.03.txt)
[Disallow Conversions - OFF - MediaInfo.txt](https://github.com/NickvisionApps/Parabolic/files/12676382/Disallow.Conversions.-.OFF.-.MediaInfo.txt)
[Disallow Conversions - ON - log6-19:59:56.txt](https://github.com/NickvisionApps/Parabolic/files/12676385/Disallow.Conversions.-.ON.-.log6-19.59.56.txt)
[Disallow Conversions - ON - MediaInfo.txt](https://github.com/NickvisionApps/Parabolic/files/12676386/Disallow.Conversions.-.ON.-.MediaInfo.txt)
[Versions.txt](https://github.com/NickvisionApps/Parabolic/files/12676390/Versions.txt)

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Parabolic/releases/tag/2023.9.1-rc1
