### ISSUE TITLE
Creating a playlist folder

### ISSUE THREAD

**Issue by Articmar** [NickvisionApps/Parabolic#600]
Please add a function to create a folder when downloading a playlist. 

What I mean in detail:
When I insert a link to a YouTube playlist, that a folder with the same name as the YouTube playlist is created first, and all videos from that playlist are downloaded to that folder.

If this is possible.

**Comment by nlogozzo** [comment]
This feature has been implemented! Will be released in an update soon to come!

**Comment by nlogozzo** [comment]
Parabolic [V2024.9.0-beta2](https://github.com/NickvisionApps/Parabolic/releases/tag/2024.9.0-beta2) is here with a fix for this issue!

Please follow the install instructions on the page to test it out :)
