### ISSUE TITLE
[Feature Request] download a playlist with different maximum resolutions

### ISSUE THREAD

**Issue by autovettore** [NickvisionApps/Parabolic#613]
As of 2023.9.0, when you download a video playlist, all videos in that playlist default to the highest resolution available for the worst quality video. What I mean by that is, let’s say there are 3 videos in a playlist:
Vid1: 1080p
Vid2: 1440p
Vid3: 2160p
If you download this playlist, all videos are going to be only 1080p even though other videos they are also available in higher resolutions.
It would be great to add an option like “Best available quality” that would be selected for all videos and would download the highest resolution available.

**Comment by fsobolev** [comment]
The app should provide you with the highest resolution available across all videos in playlist, so in your example 2160p should be available in the list, and in this case videos will be downloaded in the best available quality.
This works for me, I can't reproduce the problem. Could you give a link to the playlist you tried to download?

**Comment by autovettore** [comment]
For example this one: https://www.youtube.com/playlist?list=PLkIGJ7Ljv6Yz6KYEqbfkvv1I0TSIfEvrs
it only downloads in 1080p even though the last 2 videos are also available in 1440p and this one even in 4k: https://www.youtube.com/watch?v=vIiI8uBwWTk&list=PLkIGJ7Ljv6Yz6KYEqbfkvv1I0TSIfEvrs

**Comment by autovettore** [comment]
So after further testing I came to a conclusion that the “Maximum Quality” offered in the “Add Download” window is set by the FIRST video in the playlist.
Here is another example, first video is in 1440p and e.g. last is in 2160p, yet the maximal available quality is 1440p:
https://www.youtube.com/playlist?list=PLkIGJ7Ljv6YwqxT29cCprQgIx3IN7WyqA

If however the first video is in 2160p and last is 1440p (playlist below), you can still choose 2160p as a download quality:
https://www.youtube.com/playlist?list=PLkIGJ7Ljv6YzOP7W36SjRWctna19jcWGa

**Comment by fsobolev** [comment]
> So after further testing I came to a conclusion that the “Maximum Quality” offered in the “Add Download” window is set by the FIRST video in the playlist.

Yeah, sorry, I should have write it after I re-read the code and remembered that 😅 The thing is, when loading data for playlists with yt-dlp, we have 2 options: either download all data for all videos, which can take *a lot* of time (50 videos in playlist? The data will be loading for a minute) or download only basic data like titles and URLs without resolutions. At some moment in the past we implemented the second option, and together with playlist data we also load the full data for the first entry to get the list of resolutions to have at least something.
We will probably just add "Best" option to the list to download maximum available quality for each video as you suggested.

**Comment by autovettore** [comment]
Ok, no problem. Thanks for clarifying the functionality!

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Parabolic/releases/tag/2023.11.0-rc1
