### ISSUE TITLE
[Bug] Can't download videos when subtitles are activated 

### ISSUE THREAD

**Issue by Raxelgrande** [NickvisionApps/Parabolic#618]
Error message inside the video's area in Parabolic: 
[parabolic-bug0.txt](https://github.com/NickvisionApps/Parabolic/files/12775896/parabolic-bug0.txt)

OS: Endeavour OS 
DE: KDE Plasma 5.27.8 
Kernel: 6.5.5-zen1-1-zen

It refuses to download anything if i include subtitles. It happens on other videos too.

**Comment by nlogozzo** [comment]
If you go into Preferences, did you configure the `Subtitle Languages (Comma-Separated)` field? 

You need to specify the languages you'd like Parabolic to download when downloading subtitles otherwise it will download 20+ different languages which we're sure most users won't want. But you can also just specify `all` in that field to achieve this.

**Comment by nlogozzo** [comment]
@fsobolev Maybe disable the `Download Subtitle` option in `AddDownloadDialog` if the subtitle languages is empty? or provide a warning to configure it firts

**Comment by fsobolev** [comment]
Could you please provide the debug info from Troubleshooting section in about dialog?

**Comment by Raxelgrande** [comment]
I didn't know that there was a setting to configure subtitle languages. Mine was set up to "es,spa"
I tried to download another video, this time with the "all" setting and it downloaded the video, without any subtitle. 
[parabolic-bug1.txt](https://github.com/NickvisionApps/Parabolic/files/12777518/parabolic-bug1.txt)
It would be cool to have a setup at first launch that asks you what language you prefer for subtitles, or provide a better default, for example: English and the default language indicated by Flatpak

**Troubleshooting output:**
org.nickvision.tubeconverter
2023.9.1
GTK 4.10.5
libadwaita 1.3.5
Flatpak
yt-dlp 2023.09.24
psutil 5.9.5
ffmpeg version 6.0
aria2 version 1.36.0
es-EC
LANG=es_EC.UTF-8
LC_CTYPE="es_EC.UTF-8"
LC_NUMERIC=es_EC.UTF-8
LC_TIME=es_EC.UTF-8
LC_COLLATE="es_EC.UTF-8"
LC_MONETARY=es_EC.UTF-8
LC_MESSAGES="es_EC.UTF-8"
LC_PAPER=es_EC.UTF-8
LC_NAME=es_EC.UTF-8
LC_ADDRESS=es_EC.UTF-8
LC_TELEPHONE=es_EC.UTF-8
LC_MEASUREMENT=es_EC.UTF-8
LC_IDENTIFICATION=es_EC.UTF-8
LC_ALL=

**Comment by fsobolev** [comment]
what's the output of

```
locale -a
```

and

```
flatpak run --command=locale org.nickvision.tubeconverter -a
```

?

**Comment by Raxelgrande** [comment]
Sorry for the delay. The output of "locale -a" is: 
C
C.utf8
en_US.utf8
es_EC.utf8
POSIX

The output of "flatpak run --command=locale org.nickvision.tubeconverter -a" is 
[parabolic-debug0.txt](https://github.com/NickvisionApps/Parabolic/files/12889278/parabolic-debug0.txt)

**Comment by nlogozzo** [comment]
@fsobolev Did we ever figure out what the actual issue here is?

**Comment by fsobolev** [comment]
> @fsobolev Did we ever figure out what the actual issue here is?

No. There's `es_EC` in `locale` output in flatpak, but no `es_EC.utf8`, no idea why, maybe this causes the problem (and this most likely affects all apps, not just Parabolic). And I didn't manage to enforce another locale for python process in Parabolic.

**Comment by nlogozzo** [comment]
@Raxelgrande Sorry it's been a little bit. 

Upon further inspection of the log, it reads:
```
ERROR: 'ascii' codec can't decode byte 0xc3 in position 140: ordinal not in range(128)
```
Which seems like the reason nothing is downloading, not really an issue with subtitles. 
Going to look into it and fix it...

**Comment by nlogozzo** [comment]
According to this: https://github.com/ytdl-org/youtube-dl/issues/24516

This error shows when using python2 and not 3. How did you install Parabolic? Flatpak, Snap, or local repo?

**Comment by nlogozzo** [comment]
I just tried this with my subtitle langs set to `es,spa` on the latest development build: https://github.com/NickvisionApps/Parabolic/actions/runs/6827561547 and it worked no problem.

You can download the flatpak file from that build ^ and run it and test it on your machine.

Once you extract the zip run `flatpak install org.nickvision.tubeconverter.flatpak` from the directory where the file is. Then run `flatpak run org.nickvision.tubeconverter//master` to run the app. Once you've tested it and are done with it, you can uninstall it via `flatpak uninstall org.nickvision.tubeconverter//master`. 

*Installing and running this build is isolated from your main flatpak install of Parabolic. So you will need to reconfigure any settings you may have set in the stable version*

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Parabolic/releases/tag/2023.11.0-beta2

*Will be available via `flathub-beta` within the hour!*
