### ISSUE TITLE
Aria2 -x option must be between 1 and 16

### ISSUE THREAD

**Issue by fsobolev** [NickvisionApps/Parabolic#627]
```
Exception: [[AbstractOptionHandler.cc:69](http://abstractoptionhandler.cc:69/)] errorCode=28 We encountered a problem while processing the option '--max-connection-per-server'.
  -> [[OptionHandlerImpl.cc:184](http://optionhandlerimpl.cc:184/)] errorCode=1 max-connection-per-server must be between 1 and 16.
Usage:
 -x, --max-connection-per-server=NUM The maximum number of connections to one
                              server for each download.

                              Possible Values: 1-16
                              Default: 1
                              Tags: #basic, #http, #ftp



ERROR: aria2c exited with code 28
```

**Comment by nlogozzo** [comment]
If I could, I'll take the fix for this in the `winui` branch

**Comment by soumyaDghosh** [comment]
> If I could, I'll take the fix for this in the `winui` branch

Should I not try then? I mean the fix is anyways very small.

**Comment by fsobolev** [comment]
> > If I could, I'll take the fix for this in the `winui` branch
> 
> Should I not try then? I mean the fix is anyways very small.

Nick already fixed it https://github.com/NickvisionApps/Parabolic/pull/625/commits/554e781c3feef553f2ea82e28d5ade839b17faa1

**Comment by soumyaDghosh** [comment]
Thanks @nlogozzo

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Parabolic/releases/tag/2023.11.0-beta1
