### ISSUE TITLE
Add language code format and option to disable auto-generated 

### ISSUE THREAD

**Issue by elio567** [NickvisionApps/Parabolic#629]
Please can you add language code format two-letter with region, but with underscore. For example: "en_US".
And option to disable downloading  auto-generated subs on Youtube

**Comment by nlogozzo** [comment]
> Please can you add language code format two-letter with region, but with underscore. For example: "en_US".

Probably not. Since `en-US` and `en_US` are the same thing and yt-dlp wants with the `-` instead of `_`. So you can easily just specify the `-`.

> And option to disable downloading auto-generated subs on Youtube

Will do

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Parabolic/releases/tag/2023.11.0-beta2

*Will be available via `flathub-beta` within the hour!*
