### ISSUE TITLE
It does not work to download from tv4play.se.

### ISSUE THREAD

**Issue by jotakswe** [NickvisionApps/Parabolic#646]
It does not work to download from tv4play.se.
Web Page: https://www.tv4play.se/video/7ad8478e2a50d1a74cc1/avsnitt-1
https://www.tv4play.se/program/4cbc86ffa7fd2657a5fc/morden-i-sandhamn?season=f0d4288014d06806533c
Getting the error "Media URL (Invalid)
Have tested with both Authenticate info and without Authenticate info, but without success.
If there is any more information you need, just let me know.

Parabolic: 2023.11.0-beta1
OS: Linux Manjaro 6.1.60-1-MANJARO (64-bit)
Browser: Firefox 119.0 (64-bit)
[231108 - textfiles.zip](https://github.com/NickvisionApps/Parabolic/files/13302209/231108.-.textfiles.zip)
[231108 - output.log](https://github.com/NickvisionApps/Parabolic/files/13302295/231108.-.output.log)

**Comment by nlogozzo** [comment]
> ERROR: Unsupported URL: https://www.tv4play.se/video/7ad8478e2a50d1a74cc1/avsnitt-1

This error makes me feel like this link isn't support. Although tv4play is listed as a supported site, it seems like some videos are DRM-protected, which yt-dlp doesn't support.

See https://github.com/yt-dlp/yt-dlp/issues/7321

In that case if the above cookies file doesn't work, then there is nothing we can do.

**Comment by jotakswe** [comment]
@nlogozzo
Unfortunately no luck with the cookies file.
It is probably so that it does not work with DRM material, unfortunately.

Should I close the error report?

**Comment by nlogozzo** [comment]
> Should I close the error report?

I'll close it

**Comment by jotakswe** [comment]
@nlogozzo 
Have found a solution to the problem, now you "just" have to implement it in "Parabolic". :-)

[Issue #646 - 231109.zip](https://github.com/NickvisionApps/Parabolic/files/13309366/Issue.646.-.231109.zip)

**Comment by nlogozzo** [comment]
Great will look into it!

**Comment by nlogozzo** [comment]
Ok so, Parabolic is just a frontend for `yt-dlp`. All the work of finding videos and their correct URL to download comes from `yt-dlp`. As seen from the first message using the URL `https://www.tv4play.se/video/7ad8478e2a50d1a74cc1/avsnitt-1` gives `Unsupported URL` from yt-dlp. So it's out of scope for me to try and use something else to parse the video and get the correct URL to download.

I recommend opening an issue on `yt-dlp`'s repo with your URL to get them to parse it correctly.
