### ISSUE TITLE
Can't download video from instagram if there are more than one video in the playlist

### ISSUE THREAD

**Issue by congomonster** [NickvisionApps/Parabolic#651]
Hi,

sorry for the long title. I try to dicribe the problem in short words.

1. I try to download a video from instagram. But under the link are two videos. The url has an index=1 or index=2 at the and. Here like this fake link:
https://www.instagram.com/p/not_a_real_link/?img_index=1
2. When i copy the link to parabolic, it only downloads the second video twice. I can't download the first video. Even if i change the index at the and or put in the link without ?img_index=1

Parabolic: Snap Version 2023.9.1
System: Ubuntu 23.10
Gnome 45
Linux 6.5.0-10-generic

**Comment by nlogozzo** [comment]
Do you have a real link? I'd like to play around with it to see what yt-dlp sees.

Is this link just a regular post that has multiple pics/videos?

**Comment by congomonster** [comment]
Hi,
here is a link: https://www.instagram.com/p/CzZK-9zJKK-/?img_index=1
It's a skateboarding clip. I want the first one. But i only get the second clip two times. I think the post is a normal post. I found this in my timeline and saved it for later.

**Comment by nlogozzo** [comment]
Fixed with https://github.com/NickvisionApps/Parabolic/commit/5be82674ed6e6d8eb045cc056bd43150bfe380b5

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Parabolic/releases/tag/2023.11.0-rc1
