### ISSUE TITLE
[Feature Request] SponsorBlock

### ISSUE THREAD

**Issue by Heus-Sueh** [NickvisionApps/Parabolic#654]
Equal to the [YTDLnis](https://github.com/deniscerri/ytdlnis) function
![image](https://github.com/NickvisionApps/Parabolic/assets/98482469/78714593-d85e-4e93-a7df-c28e784dc620)

**Comment by nlogozzo** [comment]
Hi, this feature already exists. You need to enable it in Preferences/Settings.

GNOME:
![image](https://github.com/NickvisionApps/Parabolic/assets/17648453/9e8392ec-112b-4f44-a997-7ebdefa43546)

WinUI:
![image](https://github.com/NickvisionApps/Parabolic/assets/17648453/239da223-fafc-4d1f-8396-89fa0c4416fd)

**Comment by Heus-Sueh** [comment]
> Hi, this feature already exists. You need to enable it in Preferences/Settings.
> 
> GNOME: ![image](https://user-images.githubusercontent.com/17648453/282499781-9e8392ec-112b-4f44-a997-7ebdefa43546.png)
> 
> WinUI: ![image](https://user-images.githubusercontent.com/17648453/282499866-239da223-fafc-4d1f-8396-89fa0c4416fd.png)

Wouldn't it be better to put this option there in the advanced options?
![image](https://github.com/NickvisionApps/Parabolic/assets/98482469/b0e2c095-a7e4-4763-ac60-81a483966d2c)

**Comment by nlogozzo** [comment]
Advanced Options are settings that apply to individual downloads. Things in Preferences apply to all downloads.

If you use SponsorBlock for one video, you'd probably want to use it for all, no?
If a video doesn't have sponsors, leaving SponsorBlock on won't have any effect on the download.
