### ISSUE TITLE
[Feature Request] Add play button to notification when download finished

### ISSUE THREAD

**Issue by Jummit** [NickvisionApps/Parabolic#666]
Similar to Gnome Software, which has a button to launch newly installed apps in the notification. I think this would add quiet a bit of polish, even though it's a small feature.

If there is the caveat that it can't ask which player to choose, it could just use the default application for music/videos.

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Parabolic/releases/tag/2023.11.0-rc2
