### ISSUE TITLE
Greyed-out Download Button - Windows

### ISSUE THREAD

**Issue by ironveil** [NickvisionApps/Parabolic#671]
After installing the latest Windows release (2023.11.0-rc2), there seems to be an issue with the downloader backend. The 'download' buttons are greyed out and it doesn't allow me to download anything?

![image](https://github.com/NickvisionApps/Parabolic/assets/131584614/865e3b11-f5ce-43de-942a-1b44544285d3)

**Comment by nlogozzo** [comment]
Could you go into Help->About and click the button that contains the version number. Give it a few seconds and then you should get "Copied debug info to clipboard." Once it says that could you paste that here?

Also could you try restarting your system and running Parabolic again? If that doesn't fix it, try running the installer again and restart and run Parabolic again.

I'm currently not home so I will do further investigation when I am home..but it'd like you to do does things above in the mean time.

**Comment by nlogozzo** [comment]
Just for further information: the only time Parabolic would gray out the Add Download button is if it detected there is no internet. Did you change anything about ur connection recently? VPN or smth?

**Comment by ironveil** [comment]
Ah right, I've just double checked and it seems to not like my firewall. When I disable the firewall, it works fine. Which is weird since I have allowed the .exe to pass through and it shows that Parabolic is making a connection. How does the program check for an active internet connection?

Seeing as this isn't a Parabolic issue, it is probably okay to close the issue.

---

Debug info:
org.nickvision.tubeconverter
2023.11.0-rc2

Microsoft Windows NT 10.0.22621.0
en-GB
aria2 version 1.36.0
ffmpeg version 6.1-full_build-www.gyan.dev
yt-dlp 2023.10.13
psutil 5.9.5

**Comment by nlogozzo** [comment]
> How does the program check for an active internet connection?

It just uses C#'s ping function to hit a few sites to see if it has connection.

> yt-dlp 2023.10.13

The installer for rc2 should have installed 2023.11.16 so seems like ur firewall is blocking it all.
