### ISSUE TITLE
Crashing when adding another URL via CLI

### ISSUE THREAD

**Issue by haeckle** [NickvisionApps/Parabolic#684]
### Description:
While a download is running trying to add another URL via the commandline argument the application crashes. Adding the second URL is done via invoking Parabolic from Firefox Open With addon ([AMO](https://addons.mozilla.org/firefox/addon/open-with/)). Tried it with YouTube as well as [ardmediathek.de](https://www.ardmediathek.de/) videos.

### Debug Information:

> org.nickvision.tubeconverter
> 2023.11.0
> GTK 4.12.3
> libadwaita 1.4.0
> Flatpak
> ffmpeg version 6.1
> aria2 Version 1.36.0
> yt-dlp 2023.11.16
> psutil 5.9.6
> de-DE
> LANG=de_DE.UTF-8
> LC_CTYPE="de_DE.UTF-8"
> LC_NUMERIC="de_DE.UTF-8"
> LC_TIME="de_DE.UTF-8"
> LC_COLLATE="de_DE.UTF-8"
> LC_MONETARY="de_DE.UTF-8"
> LC_MESSAGES="de_DE.UTF-8"
> LC_PAPER="de_DE.UTF-8"
> LC_NAME="de_DE.UTF-8"
> LC_ADDRESS="de_DE.UTF-8"
> LC_TELEPHONE="de_DE.UTF-8"
> LC_MEASUREMENT="de_DE.UTF-8"
> LC_IDENTIFICATION="de_DE.UTF-8"
> LC_ALL=

### Stacktrace:

```
Process terminated. A callback was made on a garbage collected delegate of type 'NickvisionTubeConverter.GNOME!NickvisionTubeConverter.GNOME.Program+OpenCallback::Invoke'.
Repeat 2 times:
--------------------------------
   at Gio.Internal.Application.Run(IntPtr, Int32, System.String[])
--------------------------------
   at Gio.Application.Run(Int32, System.String[])
   at Gio.Application.RunWithSynchronizationContext(System.String[])
   at NickvisionTubeConverter.GNOME.Program.Run(System.String[])
   at NickvisionTubeConverter.GNOME.Program.Main(System.String[])
```

### OS environment:
Fedora Silverblue 37 with Kernel 6.5.8-100.fc37.x86_64

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Parabolic/releases/tag/2023.11.1

**Comment by haeckle** [comment]
Wow, that was fast. Thanks!
