### ISSUE TITLE
unable to install psutil (windows 10)

### ISSUE THREAD

**Issue by rexendevar** [NickvisionApps/Parabolic#687]
Thought I would install Parabolic to my Windows partition as well since I do occasionally use it. It says it's unable to install `psutil` and that the program would not work correctly (which i confirmed). I tried to run the exe via the command line but it did not give me any new feedback.

**Comment by nlogozzo** [comment]
Do you have any firewall set up? It could be that it's blocking psutil from installing (which uses python's pip util to install it)...

**Comment by nlogozzo** [comment]
I think I found the issue....give me a minute to build the new installer

**Comment by rexendevar** [comment]
i don't think i have a firewall. i'm not logging back on tonight to check
sorry

**Comment by nlogozzo** [comment]
> i don't think i have a firewall. i'm not logging back on tonight to check

no worries, it's not the firewall. psutil requires vs redistributable to be on the system, so I'm packaging that with the installer and it should work after...

**Comment by nlogozzo** [comment]
Whenever you get the chance, I updated the installer here: https://github.com/NickvisionApps/Parabolic/releases/tag/2023.11.1

Please download and try to install it and see what happens

**Comment by rexendevar** [comment]
same issue.

**Comment by nlogozzo** [comment]
ah ok...i'll look into it more

**Comment by CarrotManMatt** [comment]
I am also experiencing this issue

**Comment by nlogozzo** [comment]
@rexendevar @CarrotManMatt Could you try this installer: https://we.tl/t-mug3HcsQ31 ?

Just note that it will install a beta version of the app...but it does work without issues

**Comment by CarrotManMatt** [comment]
@nlogozzo Sorry for my delay in testing this for you. Still no luck, fails to install due to inability to install psutil. Weirdly it also caused a soft restart before throwing the error (I allowed it to restart rather than cancelling, however that ended the install process. So after I had rebooted, I relaunched the installer which then encountered the error on the second try)

**Comment by nlogozzo** [comment]
@rexendevar @CarrotManMatt Hey, could you try the installer from this release: https://github.com/NickvisionApps/Parabolic/releases/tag/2023.12.0-beta1

psutil had a bug fix release that fixed some Windows installer issues so I hope it works now!

**Comment by CarrotManMatt** [comment]
@nlogozzo I'm sorry that I'm becoming your constant bearer of bad news, but *still* no luck! Those darn psutils.
![image](https://github.com/NickvisionApps/Parabolic/assets/108596565/0772719c-73ce-4bac-a9b7-c5ba060682a4)

**Comment by nlogozzo** [comment]
> @nlogozzo I'm sorry that I'm becoming your constant bearer of bad news, but *still* no luck! 

No worries...I find it crazy how no one else is reporting an issue on psutil repo about this itself.
And users of Windows 11 have no issues...

**Comment by CarrotManMatt** [comment]
I am not well versed on these things (and will be moving to linux after KDE 6) so what is psutils anyway?

**Comment by nlogozzo** [comment]
> I am not well versed on these things (and will be moving to linux after KDE 6) so what is psutils anyway?

Psutils is a python module that allows you to tap into running processes and control them and their children. 

Even though the app is made in C#, we actually embed python and use that to call and run yt-dlp. So the psutil module allows us to tap into yt-dlp and kill it and it's spawned ffmpeg processes when the user wants to stop a download while it's running.

I didn't find an easy way to do this in C# as the built in .NET process library didn't seem to provide an easy way to do this like psutils tho...I'm going to look for a proper C# solution to remove the use psutils all together.

**Comment by nlogozzo** [comment]
@CarrotManMatt Luckily I was able to figure it out! Hope to have a beta 2 release out in a few hours for you to test :)

**Comment by nlogozzo** [comment]
@CarrotManMatt Try this: https://github.com/NickvisionApps/Parabolic/releases/tag/2023.12.0-beta2
