### ISSUE TITLE
different parts of the same video have the same file name when downloading

### ISSUE THREAD

**Issue by SokolovskyMaxim** [NickvisionApps/Parabolic#689]
different parts of the same video have the same file name when downloading, which leads to their overwriting. Instead of several parts of one video, one is downloaded - the last of the uploaded ones

**Comment by nlogozzo** [comment]
What are your settings for the download that cause the file to be broken into multiple parts? Split chapters, file type, etc...

Could you also give me the link for the video you are trying to download?
