### ISSUE TITLE
Videos downloads max out at 1080p, regardless of settings.

### ISSUE THREAD

**Issue by Ifyexarmoon** [NickvisionApps/Parabolic#696]
As youtube has started to periodically block firefox users from watching 4k content, I have been using yt-dlp more, but I have had to use the command line, since no matter the content or whether I set a specific resolution or 'best', Parabolic maxes out at 1080p mp4.
[Here](https://www.youtube.com/watch?v=Sw8qPy2OCJc) is the 4k video that got me to get around to investigating, although I tested with a whole lot of videos.
This is on multiple different computer's installs of Fedora 39 KDE Plasma 5.27, including Asahi Remix and Bazzite, if it is relevant.
Also, here is the debugging info for the asahi linux one.
```
org.nickvision.tubeconverter
2023.11.1
GTK 4.12.4
libadwaita 1.4.2
Flatpak
yt-dlp 2023.11.16
psutil 5.9.6
aria2 version 1.37.0
ffmpeg version 6.1
en-US
LANG=en_US.utf8
LC_CTYPE="en_US.utf8"
LC_NUMERIC=en_US.utf8
LC_TIME=en_US.utf8
LC_COLLATE="en_US.utf8"
LC_MONETARY=en_US.utf8
LC_MESSAGES="en_US.utf8"
LC_PAPER=en_US.utf8
LC_NAME=en_US.utf8
LC_ADDRESS=en_US.utf8
LC_TELEPHONE=en_US.utf8
LC_MEASUREMENT=en_US.utf8
LC_IDENTIFICATION=en_US.utf8
LC_ALL=
```
If I missed any useful information I should submit, please tell me!

**Comment by nlogozzo** [comment]
Interesting...

When you validate the video in the dialog, and it shows the list of resolutions...is 4K an option? Or do you have disallow conversions on in which it only shows best?

**Comment by nlogozzo** [comment]
Can confirm, even after selecting 4K resolution, 1080p is still downloaded. Will fix...

**Comment by Ifyexarmoon** [comment]
Yeah, all available resolutions visible on youtube in chromium show up, including 4k, they just don't do anything different than selecting 1080p. Glad to hear you are seeing something consistent with that!

**Comment by Ifyexarmoon** [comment]
Not sure if you've already fixed this bug, but I thought I'd add what I've figured out recently.
I think that you must be prioritizing H.264/avc1, which maxes out at 1080p for (possibly) all YouTube videos. I think to get 4k you're going have to use vp09 or add a new codec conversion step. 
I assume codec conversion is possible, although I haven't tried, all the videos I've downloaded with command-line yt-dlp I left as vp09 mp4.

**Comment by nlogozzo** [comment]
> I think that you must be prioritizing H.264/avc1, which maxes out at 1080p for (possibly) all YouTube videos. I think to get 4k you're going have to use vp09 or add a new codec conversion step.

If you go into advanced options for the download you should see the "Prefer AV1 Codec" setting. It should be off by default however...

**Comment by Ifyexarmoon** [comment]
Hadn't noticed that! Turning on the AV1 codec option successfully downloads 4K vp09. Video quality options >1080p should probably be hidden until vp09 is selected, to avoid confusion (or it should switch to vp09 for anything >1080p automatically). Also the toggle should should probably say vp09 as I have never seen a YouTube video available in AV1

**Comment by nlogozzo** [comment]
> Video quality options >1080p should probably be hidden until vp09 is selected, to avoid confusion (or it should switch to vp09 for anything >1080p automatically).

I'll probably do this as the solution

> Also the toggle should should probably say vp09 as I have never seen a YouTube video available in AV1

AV1 is the new codec that supports 8K. AV1 is an extension of vp9 so av1 includes vp9 and more.

**Comment by nlogozzo** [comment]
Please test the beta: https://github.com/NickvisionApps/Parabolic/releases/tag/2023.12.0-beta1

**Comment by Ifyexarmoon** [comment]
Just got the beta installed, downloaded a playlist and it seems to be working, everything >1080p is automatically vp09 while everything lower is h264!  Thanks for your hard work getting this fixed, this update is a lovely Christmas present!

**Comment by nlogozzo** [comment]
> Just got the beta installed, downloaded a playlist and it seems to be working, everything >1080p is automatically vp09 while everything lower is h264!  Thanks for your hard work getting this fixed, this update is a lovely Christmas present!

Glad to hear! Hope to have a stable release out before the new year, enjoy the holiday!!
