### ISSUE TITLE
In Windows 11 don't download correct links - write "Incorrect link".

### ISSUE THREAD

**Issue by ErgoProxy0-13** [NickvisionApps/Parabolic#703]
In Windows 11 don't download correct links - write "Incorrect link".
In Russian - "Ссылка (Некорректная)".

**Comment by nlogozzo** [comment]
I'm confused on what the issue is? Is there a translation issue?

CC @daudix @fsobolev

**Comment by nlogozzo** [comment]
@ErgoProxy0-13 could you provide me with one of the links you are trying to download?
