### ISSUE TITLE
Option to set default file type

### ISSUE THREAD

**Issue by M00NJ** [NickvisionApps/Parabolic#705]
When downloading multiple audio files manually  I have to select `Audio` in the drop-down menu, individually for each download, since it defaults back to `Video` the next time. This can get pretty tedious after a while. It would be nice the have a preference for the default file type, or at least have it remembered.

![Screenshot from 2023-12-16 00-18-29](https://github.com/NickvisionApps/Parabolic/assets/82398591/3ef8404a-f253-4837-92e6-54a0f11135e5)

**Comment by nlogozzo** [comment]
I don't know if this was intentional, but looks like you have conversions disabled. 

If you enable it in Preferences, you'll get a whole list of file formats which will be listed and will be remembered every time.  

Disallowed conversions work a little different hence why the choice isn't remembered... but I'll look into it

**Comment by M00NJ** [comment]
I see. Yes, I disabled conversions since I just wanted the best possible audio quality from source.
Thanks for explainig it, I'll play around with the settings some more :)

**Comment by M00NJ** [comment]
> I see. Yes, I disabled conversions since I just wanted the best possible audio quality from source. Thanks for explainig it, I'll play around with the settings some more :) I still think the pref would be useful though.

**Comment by nlogozzo** [comment]
Conversions wouldn't affect the audio quality. As long as you select the highest option in quality, you can just pick the audio format you'd like (mp3, flac, etc..) and it should be ok.

Like I said when you turn off disable conversions and select a file format that will be remembered.

**Comment by M00NJ** [comment]
But in case of YouTube Music e.g. the source file is already compressed. So if I select a lossless file type like FLAC, I just get the same audio quality in a bigger file, since it cannot readd the information that was lost when the file was compressed. However I thought YT Music used AAC but it's OPUS in Parabolic. That's interesting to me as well. So what I meant is I want it to download the original format in the best quality, that's why I turned of conversion. But I'll turn in back on and select OPUS, since it should to the same thing and be remembered like you said.

**Comment by nlogozzo** [comment]
Ok, Parabolic will now remember whether you choose "Video" or "Audio" with Disallow Conversions on.

**Comment by nlogozzo** [comment]
Please test the beta: https://github.com/NickvisionApps/Parabolic/releases/tag/2023.12.0-beta1

**Comment by M00NJ** [comment]
Sorry for taking so long. I just tested it and it works perfectly. Thanks a lot!
