### ISSUE TITLE
Problem with TV4Play.se, again.

### ISSUE THREAD

**Issue by jotakswe** [NickvisionApps/Parabolic#709]
Hi!

I previously reported a problem with TV4Play.se, which I solved myself. #646

Now it doesn't work again, you have to enter a "token" for it to work.
That "token" is in cookies, but it doesn't work to use a "cookie file" for Parabolic.

"www.tv4play.se FALSE / TRUE 1731022680 tv4-refresh-token "token_value"".

I use an app in Kodi media player called "Retrospect", and they have a solution to these problems.
Also a solution to my first problem.

Is that something you guys can look at, or maybe it won't work with "yt-dlp"?

Parabolic: 2023.11.1
OS: Linux Manjaro 6.1.68-1-MANJARO (64-bit)
Browser: Firefox 120.0.1 (64-bit)

Links to "Retrospect" on Github:

https://github.com/retrospect-addon/plugin.video.retrospect

https://github.com/retrospect-addon/plugin.video.retrospect/tree/master/resources/lib/streams

https://github.com/retrospect-addon/plugin.video.retrospect/blob/master/resources/lib/streams/npostream.py

https://github.com/retrospect-addon/plugin.video.retrospect/blob/master/resources/lib/streams/m3u8.py

https://github.com/retrospect-addon/plugin.video.retrospect/blob/master/resources/lib/streams/adaptive.py

**Comment by nlogozzo** [comment]
This is again something you should report to `yt-dlp`. Parabolic just calls yt-dlp under the hood, so handing these different sites all goes through them. You should try running the yt-dlp program via the command line with your link and confirm that it also doesn't work there before reporting. If it works via the command line, then report back here and I will reopen the issue.
