### ISSUE TITLE
"Split chapters" does not respect set filename

### ISSUE THREAD

**Issue by rexendevar** [NickvisionApps/Parabolic#710]
I just downloaded a bunch of live albums off YouTube with the intention that I would rename them and have Parabolic split them into chapters, which I could then easily arrange in order. Unfortunately, upon downloading, I discovered that the file names for the split chapters retained the original title of the youtube video - which, given that they are all titled the same, is a problem for my sorting. 

![image](https://github.com/NickvisionApps/Parabolic/assets/46948713/99216877-6368-471e-ae24-6cfceb4d8ea6)

Shown at the top are the set filenames I requested, which were downloaded as normal. Below that are all the split versions, which should demonstrate my problem.

**Comment by nlogozzo** [comment]
Got it fixed:
![image](https://github.com/NickvisionApps/Parabolic/assets/17648453/f128f429-bb4a-4381-95e9-bcaf6649d1db)

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Parabolic/commit/612333baab5eaa9ac93df7ef57d9092d7cb15ed2

**Comment by nlogozzo** [comment]
Please test the beta: https://github.com/NickvisionApps/Parabolic/releases/tag/2023.12.0-beta1
