### ISSUE TITLE
[Feature request] Add option to write video thumbnails 

### ISSUE THREAD

**Issue by LionelVallet** [NickvisionApps/Parabolic#713]
It would be nice if, under the option to download subtitles, there was an option to download video thumbnails using yt-dlp parameter `--write-thumbnail`.

The best would be to have an image format option using`--convert-thumbnail 'jpg'` from yt-dlp.

**Comment by nlogozzo** [comment]
Do you have `Embed Metadata` turned on in Preferences (GNOME) / Settings (WinUI)?

Having this feature on should download thumbnails for videos if available.

**NOTE:** not all video file types support thumbnails. Only MP4 not WEBM.

**Comment by LionelVallet** [comment]
`Embed Metadata` is turned on and I have no metadata file nor folder next to the video. I'm using the Flatpak version. I tried with YouTube and Arte.tv

With yt-dlp, video thumbnails don't depend on the type of video file. They are not generated by ffmpeg; they are the thumbnails that the creator has uploaded to the video platform.

**Comment by nlogozzo** [comment]
> I have no metadata file nor folder next to the video

There will be no extra metadata file or folder next to the video. The metadata is embeded...hence it is written to the actual video file itself.

> With yt-dlp, video thumbnails don't depend on the type of video file. They are not generated by ffmpeg; 

Correct that they are not generated by ffmpeg but because again the metadata is embeded into the file, only certain formats accept embedding a thumbnail .

-

Are you opening the file in some sort of tagging software to confirm that nothing is being embedded in the file?
Could you provide me with a link of the video you are trying to download and the log for the download if you confirm nothing is being embedded.

**Comment by LionelVallet** [comment]
There is indeed a thumbnail in the file's metadata, but I don't see the point because no program uses it, not even the file explorer's thumbnailer.

The yt-dlp option offers to have an image file next to the video file. So NAS and multimedia applications can integrate these images into their media collection interfaces.

I suggest adding this option to the Parabolic UI as it is present in other yt-dlp UIs (eg. [youtube-dl-wpf](https://github.com/database64128/youtube-dl-wpf)).

**Comment by nlogozzo** [comment]
Parabolic will embed thumbnails in file types that support it, and they will show in file explorer:
![image](https://github.com/user-attachments/assets/7f931c79-5d45-4909-92a9-5ca0ec921fc9)


Parabolic will write the thumbnail next to the file, if it cannot be embedded. 

I did make a change where all thumbnails will be converted to `jpg` using `--convert-thumbnails`

**Comment by nlogozzo** [comment]
Parabolic [V2024.9.0-beta2](https://github.com/NickvisionApps/Parabolic/releases/tag/2024.9.0-beta2) is here with a fix for this issue!

Please follow the install instructions on the page to test it out :)
