### ISSUE TITLE
Video failing to download

### ISSUE THREAD

**Issue by Lajiii** [NickvisionApps/Parabolic#722]
When trying to download a Video from kemono.su with Parabolic it always ends in error using the windows version, it didn't used to be like that though, I can't remember exactly, but around 2 updates back in worked perfectly.

I've also downloaded the same URL with a GUI version of ytdl and it works also. ( specifically this one here: https://github.com/StefanLobbenmeier/youtube-dl-gui/releases )

I'll attach both the failure and success logs from Parabolic and ytdl respectively,

I've only ever used Github reporting once before so I do apologize if I've done anything wrong.

Last thing, for replication I'm not sure how this can work as the way most of these keemono downloads work is you have to download it within 24-48 hours after they're posted, otherwise the URL expires and that's the end of that.

The URL for the download is 'expired', if that causes it to be basically 'un-fixable', that's alright, I just thought that maybe since ytdl was able to do it without any problems the issue could be spotted that way.

[parabolic-failure-log-2024-01-10-2-15-3.odt](https://github.com/NickvisionApps/Parabolic/files/13891679/parabolic-failure-log-2024-01-10-2-15-3.odt)
[ytdl-succes-log-2024-01-10-2-15-3.txt](https://github.com/NickvisionApps/Parabolic/files/13891681/ytdl-succes-log-2024-01-10-2-15-3.txt)

**Comment by nlogozzo** [comment]
Parabolic [V2024.9.0-beta1](https://github.com/NickvisionApps/Parabolic/releases/tag/2024.9.0-beta1) is here with a fix for this issue!

Please follow the install instructions on the page to test it out :)
