### ISSUE TITLE
Many links provide -Invalid URL-

### ISSUE THREAD

**Issue by Rubencintorcas** [NickvisionApps/Parabolic#727]
EDIT 2: Please provide link that seems not working we can try to help. In pagesthat are not the usual please. ( Edit : ZDinfo Seems working only searching the link in dev mode and find the correctly one)
PLUTO TV
![Captura de pantalla 2024-01-17 155713](https://github.com/NickvisionApps/Parabolic/assets/156927416/08886b8d-fc41-4ee9-960c-b24019688bdd)
![Captura de pantalla 2024-01-17 155727](https://github.com/NickvisionApps/Parabolic/assets/156927416/e531334e-2376-4e24-a006-9fc55bef95b4)
ZDINFO
![Captura de pantalla 2024-01-18 170312](https://github.com/NickvisionApps/Parabolic/assets/156927416/14bffb90-ac9d-49f4-85f3-cb154dbfd729)
![Captura de pantalla 2024-01-18 170330](https://github.com/NickvisionApps/Parabolic/assets/156927416/1f97f057-4705-4dbd-8b95-954f3a562523)

**Comment by kolbdog3333** [comment]
You do realize its a fork of yt-dlp right? It wont be able to download drm protected videos.

**Comment by Rubencintorcas** [comment]
Do you realize that if you find the correct url almost 90% can be dowloaded, but if you only provide de master url doens't get nothing you need to go to the resource and all will work properly.

**Comment by nlogozzo** [comment]
Parabolic [V2024.9.0-beta1](https://github.com/NickvisionApps/Parabolic/releases/tag/2024.9.0-beta1) is here with a fix for this issue!

Please follow the install instructions on the page to test it out :)
