### ISSUE TITLE
Font error

### ISSUE THREAD

**Issue by xWentAFK** [NickvisionApps/Parabolic#728]
**Bug Description:**
When attempting to download a video from a platform like YouTube, the title provided by the video cannot be applied when a special font is used. Consequently, the downloaded file is saved with a randomly generated name, making it challenging to organize and identify content.

**Steps to Reproduce:**
Open the application.
Add a video for download, for instance: [Tested Video Link](https://www.youtube.com/watch?v=vdc0zijxpNs).
Attempt to download the video, leaving the video's title as the file name.

![BUG-REPORT](https://github.com/NickvisionApps/Parabolic/assets/142660266/37b61717-d8bb-42db-a33b-7c94feebd828)

**Expected Behavior:**
The selected title font should be applied to the downloaded video file, allowing users to organize and recognize content easily.

**Suggestions for Resolution:**
It might be beneficial to implement a default font for the title input when downloading videos.
Incorporating a feature to automatically convert video titles to the chosen default font during the download process maybe fixes it then?

**Device and Software information**
OS: Fedora Linux 39
Parabolic version: 2023.12.0

**Comment by nlogozzo** [comment]
The random string is Parabolic's random ID used in temporarily downloading the file in the cache folder and then it's moved and renamed to the correct folder and filename.

Whats the link you tried downloading? Your system font? And the output from the downloads log (click the Terminal icon in the row)?

**Comment by xWentAFK** [comment]
> The random string is Parabolic's random ID used in temporarily downloading the file in the cache folder and then it's moved and renamed to the correct folder and filename.
> 
> Whats the link you tried downloading? Your system font? And the output from the downloads log (click the Terminal icon in the row)?

1. The link I had given in the report: https://www.youtube.com/watch?v=vdc0zijxpNs
2. Default font I didn't touch and is "Cantarell" (the video uses some non-default font for the title)

3:
WARNING: [youtube] Preferring "en-GB" translated fields. Note that some metadata extraction may fail or be incorrect.
[youtube] Extracting URL: https://www.youtube.com/watch?v=vdc0zijxpNs
[youtube] vdc0zijxpNs: Downloading webpage
[youtube] vdc0zijxpNs: Downloading ios player API JSON
[youtube] vdc0zijxpNs: Downloading android player API JSON
[youtube] vdc0zijxpNs: Downloading m3u8 information
[info] vdc0zijxpNs: Downloading 1 format(s): 251
[info] Downloading video thumbnail 46 ...
[info] Writing video thumbnail 46 to: /home/wentafk/.var/app/org.nickvision.tubeconverter/cache/Nickvision Tube Converter/9c441129-0711-497e-84d8-84266e2377e7/9c441129-0711-497e-84d8-84266e2377e7.webp
Deleting existing file /run/user/1000/doc/22bca148/Ambience/9c441129-0711-497e-84d8-84266e2377e7.opus
[download] Destination: /home/wentafk/.var/app/org.nickvision.tubeconverter/cache/Nickvision Tube Converter/9c441129-0711-497e-84d8-84266e2377e7/9c441129-0711-497e-84d8-84266e2377e7.webm
[download] Download completed
[ExtractAudio] Destination: /home/wentafk/.var/app/org.nickvision.tubeconverter/cache/Nickvision Tube Converter/9c441129-0711-497e-84d8-84266e2377e7/9c441129-0711-497e-84d8-84266e2377e7.opus
Deleting original file /home/wentafk/.var/app/org.nickvision.tubeconverter/cache/Nickvision Tube Converter/9c441129-0711-497e-84d8-84266e2377e7/9c441129-0711-497e-84d8-84266e2377e7.webm (pass -k to keep)
[TCMetadata] Adding metadata to "/home/wentafk/.var/app/org.nickvision.tubeconverter/cache/Nickvision Tube Converter/9c441129-0711-497e-84d8-84266e2377e7/9c441129-0711-497e-84d8-84266e2377e7.opus"
[ThumbnailsConvertor] Converting thumbnail "/home/wentafk/.var/app/org.nickvision.tubeconverter/cache/Nickvision Tube Converter/9c441129-0711-497e-84d8-84266e2377e7/9c441129-0711-497e-84d8-84266e2377e7.webp" to png
[TCEmbedThumbnail] mutagen: Adding thumbnail to "/home/wentafk/.var/app/org.nickvision.tubeconverter/cache/Nickvision Tube Converter/9c441129-0711-497e-84d8-84266e2377e7/9c441129-0711-497e-84d8-84266e2377e7.opus"
[MoveFiles] Moving file "/home/wentafk/.var/app/org.nickvision.tubeconverter/cache/Nickvision Tube Converter/9c441129-0711-497e-84d8-84266e2377e7/9c441129-0711-497e-84d8-84266e2377e7.opus" to "/run/user/1000/doc/22bca148/Ambience/9c441129-0711-497e-84d8-84266e2377e7.opus"

**Comment by xWentAFK** [comment]
> > The random string is Parabolic's random ID used in temporarily downloading the file in the cache folder and then it's moved and renamed to the correct folder and filename.
> > Whats the link you tried downloading? Your system font? And the output from the downloads log (click the Terminal icon in the row)?
> 
>     1. The link I had given in the report: https://www.youtube.com/watch?v=vdc0zijxpNs
> 
>     2. Default font I didn't touch and is "Cantarell" (the video uses some non-default font for the title)
> 
> 
> 3: WARNING: [youtube] Preferring "en-GB" translated fields. Note that some metadata extraction may fail or be incorrect. [youtube] Extracting URL: https://www.youtube.com/watch?v=vdc0zijxpNs [youtube] vdc0zijxpNs: Downloading webpage [youtube] vdc0zijxpNs: Downloading ios player API JSON [youtube] vdc0zijxpNs: Downloading android player API JSON [youtube] vdc0zijxpNs: Downloading m3u8 information [info] vdc0zijxpNs: Downloading 1 format(s): 251 [info] Downloading video thumbnail 46 ... [info] Writing video thumbnail 46 to: /home/wentafk/.var/app/org.nickvision.tubeconverter/cache/Nickvision Tube Converter/9c441129-0711-497e-84d8-84266e2377e7/9c441129-0711-497e-84d8-84266e2377e7.webp Deleting existing file /run/user/1000/doc/22bca148/Ambience/9c441129-0711-497e-84d8-84266e2377e7.opus [download] Destination: /home/wentafk/.var/app/org.nickvision.tubeconverter/cache/Nickvision Tube Converter/9c441129-0711-497e-84d8-84266e2377e7/9c441129-0711-497e-84d8-84266e2377e7.webm [download] Download completed [ExtractAudio] Destination: /home/wentafk/.var/app/org.nickvision.tubeconverter/cache/Nickvision Tube Converter/9c441129-0711-497e-84d8-84266e2377e7/9c441129-0711-497e-84d8-84266e2377e7.opus Deleting original file /home/wentafk/.var/app/org.nickvision.tubeconverter/cache/Nickvision Tube Converter/9c441129-0711-497e-84d8-84266e2377e7/9c441129-0711-497e-84d8-84266e2377e7.webm (pass -k to keep) [TCMetadata] Adding metadata to "/home/wentafk/.var/app/org.nickvision.tubeconverter/cache/Nickvision Tube Converter/9c441129-0711-497e-84d8-84266e2377e7/9c441129-0711-497e-84d8-84266e2377e7.opus" [ThumbnailsConvertor] Converting thumbnail "/home/wentafk/.var/app/org.nickvision.tubeconverter/cache/Nickvision Tube Converter/9c441129-0711-497e-84d8-84266e2377e7/9c441129-0711-497e-84d8-84266e2377e7.webp" to png [TCEmbedThumbnail] mutagen: Adding thumbnail to "/home/wentafk/.var/app/org.nickvision.tubeconverter/cache/Nickvision Tube Converter/9c441129-0711-497e-84d8-84266e2377e7/9c441129-0711-497e-84d8-84266e2377e7.opus" [MoveFiles] Moving file "/home/wentafk/.var/app/org.nickvision.tubeconverter/cache/Nickvision Tube Converter/9c441129-0711-497e-84d8-84266e2377e7/9c441129-0711-497e-84d8-84266e2377e7.opus" to "/run/user/1000/doc/22bca148/Ambience/9c441129-0711-497e-84d8-84266e2377e7.opus"

Manually trying to rename the file also does not work because of the font: 
![BUG-REPORT-ADDITION](https://github.com/NickvisionApps/Parabolic/assets/142660266/ae975f32-0428-4401-982d-71de3ceed8f9)

**Comment by nlogozzo** [comment]
> Manually trying to rename the file also does not work because of the font

In that case, it's a system issue. If the system can't rename the file how do you expect Parabolic to.

When downloading the video you change change the file name in the add download dialog,  so I recommend you do that.
