### ISSUE TITLE
[Bug] Metadata is missing when loading a playlist from SoundCloud

### ISSUE THREAD

**Issue by rthrejheytjyrtj545** [NickvisionApps/Parabolic#730]
There are no tags, no titles, no album, no cover, and so on when downloading songs from a collection

#680 is closed as fixed, so a separate issue

**Comment by nlogozzo** [comment]
Can you provide a link to a soundcloud media you were trying to download?

**Comment by nlogozzo** [comment]
Finally fixed this issue! Will release an update soon!

**Comment by nlogozzo** [comment]
Parabolic [V2024.9.0-beta2](https://github.com/NickvisionApps/Parabolic/releases/tag/2024.9.0-beta2) is here with a fix for this issue!

Please follow the install instructions on the page to test it out :)
