### ISSUE TITLE
Add several links at once

### ISSUE THREAD

**Issue by sojusnik** [NickvisionApps/Parabolic#733]
It seems that at the moment you can only add one link to download from, but is it planned to add a way to add several links at once?

You could use a workaround and create a playlist with several links and then download them at once, but this is often too cumbersome.

One way to implement this could be allowing to have more than one line in the "add download" window (the text field would increase with each new line added), where each line would represent one link, so that several links could be easily added at once?

**Comment by nlogozzo** [comment]
> One way to implement this could be allowing to have more than one line in the "add download" window (the text field would increase with each new line added), where each line would represent one link, so that several links could be easily added at once?

Also providing an option to upload a text file that contains multiple urls.

**Comment by gianfelicevincenzo** [comment]
Ok, I see that it is possible to do it....but where? I can't find any options, any buttons where I can upload a text file

**Comment by nlogozzo** [comment]
> Ok, I see that it is possible to do it....but where? I can't find any options, any buttons where I can upload a text file
> 
> (**2024.5.0** on flathub, gnome software Fedora 40)

No, non è ancora possible. È qualcosa che aggiungerò nel prossimo aggiornamento 😅

**Comment by gianfelicevincenzo** [comment]
Excuse me. Forgive me for my bad english

**Comment by nlogozzo** [comment]
> Sorry. Forgive me for my bad english

Non si preoccupi...parlo pure italiano :)

**Comment by nlogozzo** [comment]
This feature is now available in [V2024.10.3](https://github.com/NickvisionApps/Parabolic/releases/tag/2024.10.3) 🎉

**Comment by ZMensRain** [comment]
@nlogozzo I was trying to use this feature but I can't seem to get it to work. Is there any specific format the file needs to be in? Like one url per line or separated by a specific character? Thank you for any info you can give me
