### ISSUE TITLE
Crash Recovery Mode

### ISSUE THREAD

**Issue by JoseBritto** [NickvisionApps/Parabolic#735]
I had around 15 downloads. When adding a new one Parabolic crashed. (need to investigate why, but I don't have any related logs atm). After crash I lost all the videos :(

It would be great if we could recover from this somehow. We could save all the active downloads currently in the queue to a file and remove that entry when completed. So, even after crash there is a good chance this file would be intact and we can recover. (Still the progress will be lost but can start over without adding manually). Probably don't start re-download automatically, but we can show them in queue and allow the user to start each one manually.

**Comment by nlogozzo** [comment]
> Denaro crashed

**Parabolic 😅

**Comment by JoseBritto** [comment]
> > Denaro crashed
> 
> **Parabolic 😅

Updated 🤦‍♂️

**Comment by antistress** [comment]
Agree, Parabolic could keep data already downloaded until the download is complete.
Maybe with a file stored on the disk named name_file.part or something like that to reveal that this is part of a file

**Comment by nlogozzo** [comment]
I'd like to implement this feature for the next release!

The download options will be written to disk as well to minimize user interaction when you start the app up again it will start the unfinished downloads before the crash.

But I have an issue...what do I do with downloads that need a username and password to be downloaded. I cannot write that username and password to a json file on disk for obvious reasons...

**Comment by JoseBritto** [comment]
> But I have an issue...what do I do with downloads that need a username and password to be downloaded. I cannot write that username and password to a json file on disk for obvious reasons...

Wouldn't having those ones be displayed as paused and prompting for credentials when resuming work? I can't think of any way of saving it especially in a crash. Unless we save everything to keyring.

When starting the app we could display a toast or a notification saying "4 downloads resumed, 2 require user action" or something similar letting the user know.

**Comment by nlogozzo** [comment]
> > But I have an issue...what do I do with downloads that need a username and password to be downloaded. I cannot write that username and password to a json file on disk for obvious reasons...
> 
> Wouldn't having those ones be displayed as paused and prompting for credentials when resuming work? I can't think of any way of saving it especially in a crash. Unless we save everything to keyring.
> 
> When starting the app we could display a toast or a notification saying "4 downloads resumed, 2 require user action" or something similar letting the user know.

Either this or I could encrypt the json file and store the encryption key in the system credential manager...

**Comment by nlogozzo** [comment]
![image](https://github.com/user-attachments/assets/f67d1a70-059a-41f2-b01a-80d87b1c24b9)

**Comment by nlogozzo** [comment]
This feature is now available in [V2024.10.3](https://github.com/NickvisionApps/Parabolic/releases/tag/2024.10.3) 🎉

**Comment by antistress** [comment]
Thanks!
Will it also work with failed downloads (i.e. I've shut down my PC before the download is complete)?

**Comment by nlogozzo** [comment]
Yes. If Parabolic force closes, all the downloads that were not completed should be resumed when you open the app again.

**Comment by antistress** [comment]
👍 👏
