### ISSUE TITLE
Allow changes to the UI language

### ISSUE THREAD

**Issue by LauraWebdev** [NickvisionApps/Parabolic#736]
First of all, great application. One thing that would be great would be a dropdown to switch the UI language instead of always using the system language. For example: I have a system setup in German but would like to use the application in English.

**Comment by nlogozzo** [comment]
You could change the desktop file or run via the command line and specify `LANG=en_US.UTF-8` before `flatpak run` to force the app to use English.

I would like to have this feature, but I don't think its per GNOME HIG to have a feature like this.
