### ISSUE TITLE
Leftover text in Comment field

### ISSUE THREAD

**Issue by Batwam** [NickvisionApps/Parabolic#742]
Hello, I just tested Parabolic v2023.10.2 (flatpak) and noted that the following comment was left in the comment field.

Would it be possible to remove this?
![image](https://github.com/NickvisionApps/Parabolic/assets/56710655/12afa238-819e-4c91-a877-5acc09b72058)

**Comment by nlogozzo** [comment]
There is a setting in Parabolic's preferences called "Remove Source Data" or something close to that (don't remember off the top of my head)...turning that on should prevent Parabolic from writing this information in the tag.

**Comment by Batwam** [comment]
ok, found it thanks. if the default is to include the link, it doesn't look like this works correctly as the link included is only partial?

**Comment by nlogozzo** [comment]
What software are you using to view the tag? Tagger? Could be a bug with it interpreting the link as markdown....

**Comment by Batwam** [comment]
I checked with my music player (rhythmbox), exiftool and Nautilus. Rhythmbox displays the track numbers for songs which have them so I'm pretty sure that the track numbers aren't there.

**Comment by Batwam** [comment]
ok, I have noted that the track numbers are now showing. I was going to mark this as closed but couldn't quite let it go as I couldn't understand why this changed. I then remembered that the only thing I changed was to turn on the option to scrub the Source Metadata. So, I went back, turn that back off and the track numbers disappeared again. bingo!

source Metadata scrubbing on (left) and off (right):
![Screenshot from 2024-02-25 22-05-43](https://github.com/NickvisionApps/Parabolic/assets/56710655/8bdbb44c-6ce4-43a5-9f94-eb59c6a74fbb)

as you can see, the right hand side has the video link but it's also missing the track number (the rest of the data cropped at the top is identical between both files).
