### ISSUE TITLE
Error notification has "Open File" action

### ISSUE THREAD

**Issue by p3732** [NickvisionApps/Parabolic#746]
Hi,
when a download fails, due to permissions or something, the shown desktop notification still offers to open the file.

Version: 2023.12.0

**Comment by rugk** [comment]
I can confirm, this is likely not useful… :upside_down_face: 

![grafik](https://github.com/NickvisionApps/Parabolic/assets/11966684/f10c0ca0-11c0-4f32-853e-5b9fbc6a998f)

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Parabolic/releases/tag/2024.5.0
