### ISSUE TITLE
Video never appears in the download folder

### ISSUE THREAD

**Issue by nclm** [NickvisionApps/Parabolic#749]
As far as I know, I have a pretty vanilla install of Ubuntu 23.10 / GNOME 45.2.

I installed Parabolic from Flathub a few days ago, and tried to download videos from a couple of different sources.

It all seem to work smoothly, and the downloads visibly finish successfully.

However, the videos are nowhere to be found.

I tried looking for their name, or for .mp4 or .webm, or sort by date, etc, they just don’t exist at all.

Not sure what that could come from, but seems like a pretty big issue because the purpose of the app is simply not happening.

Let me know what info you could need to debug this?

Thanks!

**Comment by nlogozzo** [comment]
The download row should have a folder icon that you can click and it will open the folder containing the download.

If they aren't there either, click the terminal icon in the download row that should display a log of the download and give some hints as to what went wrong.

**Comment by nclm** [comment]
Clicking the icon did nothing, forgot to mention.

I’ll try again soon and post a log, thanks!

**Comment by nclm** [comment]
Alright, here is a log and a screencast (not) downloading a random short video.

```
[vimeo] Extracting URL: https://vimeo.com/591525001
[vimeo] 591525001: Downloading webpage
[vimeo] 591525001: Downloading JSON metadata
[vimeo] 591525001: Downloading JSON metadata
[vimeo] 591525001: Downloading jwt token
[vimeo] 591525001: Downloading JSON metadata
[vimeo] 591525001: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 591525001: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 591525001: Downloading fastly_skyfire m3u8 information
[vimeo] 591525001: Downloading fastly_skyfire m3u8 information
[vimeo] 591525001: Downloading akfire_interconnect_quic MPD information
[vimeo] 591525001: Downloading akfire_interconnect_quic MPD information
[vimeo] 591525001: Downloading fastly_skyfire MPD information
[vimeo] 591525001: Downloading fastly_skyfire MPD information
[info] 591525001: Downloading 1 format(s): http-1080p
[info] There are no subtitles for the requested languages
[info] Downloading video thumbnail 1280 ...
[info] Writing video thumbnail 1280 to: /home/nicolas/.var/app/org.nickvision.tubeconverter/cache/Nickvision Tube Converter/efee146b-a020-426b-90a1-43bd13f22250/efee146b-a020-426b-90a1-43bd13f22250.jpg
[download] Destination: /home/nicolas/.var/app/org.nickvision.tubeconverter/cache/Nickvision Tube Converter/efee146b-a020-426b-90a1-43bd13f22250/efee146b-a020-426b-90a1-43bd13f22250.mp4
[download] Download completed
[TCSubtitlesConvertor] There aren't any subtitles to convert
[TCEmbedSubtitle] There aren't any subtitles to embed
[TCMetadata] Adding metadata to "/home/nicolas/.var/app/org.nickvision.tubeconverter/cache/Nickvision Tube Converter/efee146b-a020-426b-90a1-43bd13f22250/efee146b-a020-426b-90a1-43bd13f22250.mp4"
[TCEmbedThumbnail] mutagen: Adding thumbnail to "/home/nicolas/.var/app/org.nickvision.tubeconverter/cache/Nickvision Tube Converter/efee146b-a020-426b-90a1-43bd13f22250/efee146b-a020-426b-90a1-43bd13f22250.mp4"
[MoveFiles] Moving file "/home/nicolas/.var/app/org.nickvision.tubeconverter/cache/Nickvision Tube Converter/efee146b-a020-426b-90a1-43bd13f22250/efee146b-a020-426b-90a1-43bd13f22250.mp4" to "/home/nicolas/efee146b-a020-426b-90a1-43bd13f22250.mp4"
```
[Screencast from 2024-03-17 23-00-12 (trimmed).webm](https://github.com/NickvisionApps/Parabolic/assets/923008/1ee790ef-226d-471f-83de-de41f4926b01)

Btw, this is Parabolic 2023.12.0.

**Comment by nlogozzo** [comment]
It looks like it was saved in your home directory...no file is there?

**Comment by nclm** [comment]
No, no file there.

**Comment by nlogozzo** [comment]
Are you still experiencing this issue? 

Did you try using `Flatseal` to give Parabolic home permissions...maybe that will fix it...

**Comment by nlogozzo** [comment]
Could you try the latest release? https://github.com/NickvisionApps/Parabolic/releases/tag/2024.5.0

**Comment by nclm** [comment]
Hi! I tried 2024.5.0 and it does not work out of the box. Then I used Flatseal to give the home permissions, and now it works! So I guess the app should get folder permission as a default?

**Comment by nlogozzo** [comment]
The app has permissions to the Downloads folder itself already...and I've never heard of any problems with it besides you. So I think it's just a bug on your system 🤷‍♂️
