### ISSUE TITLE
Does not detect active internet connection with Wireguard

### ISSUE THREAD

**Issue by channeladam** [NickvisionApps/Parabolic#750]
Running Parabolic 2023.12.0 on Manjaro / Arch Linux - tried it both from the Flatpak and from AUR.

Wireguard is configured on the machine to a VPN provider.

Browsers and other apps that use the internet work just fine...

In the UI, Parabolic however says "No active internet connection".

**Comment by nlogozzo** [comment]
I will look into the network detection, but for now you can specify the enviornment variabile, `AURA_DISABLE_NETCHECK` to `true` and restart the system and Parabolic will bypass networkkng checking.

**Comment by channeladam** [comment]
fyi, with AURA_DISABLE_NETCHECK=true, downloading works fine with the Wireguard configured.

Thank you!

**Comment by channeladam** [comment]
Hi @nlogozzo,

Sorry for the delay... I've only just got around to testing... 2024.10.0.

The issue still occurs - with Wireguard, the Add Download button is disabled.
The AURA_DISABLE_NETCHECK=true workaround enables the Add Download button.

**Comment by nlogozzo** [comment]
@channeladam You are running Parabolic from flatpak, correct?
Could you run the following command and provide the output for me?
```
dbus-send --system --type=method_call --dest=org.freedesktop.NetworkManager --print-reply /org/freedesktop/NetworkManager org.freedesktop.DBus.Properties.Get string:'org.freedesktop.NetworkManager' string:'State'
```

**Comment by channeladam** [comment]
@nlogozzo  Yes, flatpak.

Here is the output:

```
method return time=1727967748.273457 sender=:1.7 -> destination=:1.172 serial=964 reply_serial=2
   variant       uint32 50
```

I'm not sure what that means, but if the app is trying to get the network status from NetworkManager then, at least with my Wireguard config and firewall rules, it may not recognise it. 

For instance the network icon in the desktop tray has a little red cross even though Wireguard is active - but when clicking on that icon it says 'wg0' is 'Connected'.

FYI, my Wireguard config was based upon this method: https://www.wireguard.com/netns/#the-new-namespace-solution

**Comment by nlogozzo** [comment]
I have decided to remove the network monitor feature from Parabolic. 

Because the app still has some functionality without a network (keyring, history) and if there is no connection in the end the URL will simply not validate.

**Comment by nlogozzo** [comment]
[V2024.10.1](https://github.com/NickvisionApps/Parabolic/releases/tag/2024.10.1) is here with a fix for this issue :)

*Allow it some time to be available via Flathub*
