### ISSUE TITLE
Allow for codec selection

### ISSUE THREAD

**Issue by arthwist** [NickvisionApps/Parabolic#753]
Hello, I'd like to know if it's possible to upload a video with the H264 codec with Parabolic Git because Premiere Pro doesn't support codecs like AV1 or VP9...

**Comment by nlogozzo** [comment]
I believe if `Prefer AV1` is not selected, and you use a format such as MP4, it should be H264...but I will look into it.

**Comment by JoseBritto** [comment]
> I believe if `Prefer AV1` is not selected, and you use a format such as MP4, it should be H264...but I will look into it.

I believe yt-dlp always chooses vp9 if available. We would need a preference option for this.

If there's is a ui rework like denaro, we could make the options before downloading dynamic and only show  relevant options to select codec and formats.

**Comment by Sturmlocke86** [comment]
+1 More options sounds good to me. Would H264 deliver better download quality over VP1/AV1? I've been downloading using the default VP9 so far; would AV1 deliver better quality?

**Comment by nlogozzo** [comment]
So I might make this into another drop down...

Instead of `Prefer AV1` option, I will change it to a dropdown that says `Codec` and will be `VP9 (Default), AV1, H264`
