### ISSUE TITLE
This application requires the Windows App Runtime Version 1.4

### ISSUE THREAD

**Issue by playaz44** [NickvisionApps/Parabolic#755]
Hi, I keep getting the error "This application requires the Windows App Runtime Version 1.4", I have installed version [1.4.0 (1.4.230822000)](https://learn.microsoft.com/pl-pl/windows/apps/windows-app-sdk/stable-channel#version-14) (I also tested the latest one [1.5.1 (1.5.240311000)](https://learn.microsoft.com/pl-pl/windows/apps/windows-app-sdk/stable-channel#version-151-15240311000)) but none of them work. I can't run Parabolic.

![image](https://github.com/NickvisionApps/Parabolic/assets/9553500/d3b141eb-5ca8-49d4-b19a-f673b7e3fa70)

System info:

Windows 11 Pro
23H2
22631.3296
Windows Feature Experience Pack 1000.22687.1000.0

12th Gen Intel(R) Core(TM) i5-12500H   2.50 GHz
16,0 GB RAM

**Comment by nlogozzo** [comment]
Try re-running the Parabolic installer itself? See if it fixes the dependency...

**Comment by playaz44** [comment]
I tried, after restarting, still the same error.

**Comment by nlogozzo** [comment]
> I tried, after restarting, still the same error.

Not restarting, but download the installer again from the releases page and uninstall and install Parabolic again...

**Comment by Sominemo** [comment]
I'm facing this issue too. It seems the app requires version 4000.1049.117.0 of Microsoft.WindowsAppRuntime.1.4, but my system already has 4000.1136.2333.0 installed and doesn't allow to downgrade the existing package in any way.

My system is Windows 11 22631.3296

**Comment by nlogozzo** [comment]
It's annoying how theh aren't backwards compatibile though....

Let me see if I can make a new installer with an updated SDK

**Comment by Sominemo** [comment]
On an unrelated issue, the app also installs a version of yt-dlp which interferes with my own installation. It would be cool if the app installed its own version of yt-dlp without putting it into PATH. Should I file an issue about it, if you are willing to work on this?

**Comment by playaz44** [comment]
> > I tried, after restarting, still the same error.
> 
> Not restarting, but download the installer again from the releases page and uninstall and install Parabolic again...

I did as you wrote and I still have the same error.

**Comment by nlogozzo** [comment]
Please visit the releases page (https://github.com/NickvisionApps/Parabolic/releases/tag/2023.12.0) and download and install the `NickvisionTubeConverterSetup.exe` file and install it.

The installer was updated to support the latest WindowsAppSDK version.

**Comment by nlogozzo** [comment]
Also try the latest release: https://github.com/NickvisionApps/Parabolic/releases/tag/2024.5.0
