### ISSUE TITLE
slow download and not playable after download and no choice for format

### ISSUE THREAD

**Issue by userforsource** [NickvisionApps/Parabolic#758]
I you newpipe is android
https://github.com/TeamNewPipe/NewPipe/issues
If you download a video it does not need much time just download and play.
Where as this requires a lot of time after download it proceess that video which takes a lot of time as it use ffmpeg. Can you solve this and make it better app like new pipe.

**Comment by nlogozzo** [comment]
Parabolic's download speed is relatively fast...we've never seen any issues.

Plus, the app does allow for choosing a specific format on download.

Could you provide a link to the video you are trying to download and clearer errors that you are getting?

Until then, this issue will be closed.
