### ISSUE TITLE
 [ISSUE - UNSOLVED] Buttons Greyed out and can't be selected/clicked.

### ISSUE THREAD

**Issue by MaiderGoku** [NickvisionApps/Parabolic#762]
![Screenshot 2024-04-12 190123](https://github.com/NickvisionApps/Parabolic/assets/105241930/18939ddd-5e92-4ec6-8127-8435c15cdb60)
![Screenshot 2024-04-12 190351](https://github.com/NickvisionApps/Parabolic/assets/105241930/fac596a2-684b-4905-aed9-4fed637e2022)
![Screenshot 2024-04-12 190803](https://github.com/NickvisionApps/Parabolic/assets/105241930/5b858072-5a76-40a9-9cfc-a9c1a87e4bda)
![Screenshot 2024-04-07 213236](https://github.com/NickvisionApps/Parabolic/assets/105241930/867f2dae-34fd-48b2-9263-104084ff64f2)
![Screenshot 2024-04-07 213156](https://github.com/NickvisionApps/Parabolic/assets/105241930/636aab4c-a7d1-4afa-a880-2288b613246e)
![Screenshot 2024-04-07 214713](https://github.com/NickvisionApps/Parabolic/assets/105241930/ae14b883-6bbf-48a2-9838-5e4f3fc3eae7)

**Comment by playaz44** [comment]
Today I also experienced this, nothing can be clicked.

**Comment by nlogozzo** [comment]
Are you using a VPN or metered network connection of any kind?

**Comment by playaz44** [comment]
I'm using cloudflare warp, in a few hours I'll check if it works without cf

**Comment by nlogozzo** [comment]
yeah, the only reason the button gets grayed out is if there is no active internet connection...and it could be detecting the use of the VPN as no internet.

**Comment by playaz44** [comment]
I've checked without a VPN and still nothing works.

**Comment by playaz44** [comment]
Today I tried to turn on parabolic but currently the gui does not appear, reinstallation did not help, the program not start without any error. He looks totally dead.

**Comment by nlogozzo** [comment]
> Today I tried to turn on parabolic but currently the gui does not appear, reinstallation did not help, the program not start without any error. He looks totally dead.

I plan on rewritting Parabolic so give it some time to be fixed...finishing up my degree this week so unfortunately I haven't had much time to work on the apps :/

**Comment by nlogozzo** [comment]
Could you try the latest release? https://github.com/NickvisionApps/Parabolic/releases/tag/2024.5.0

**Comment by playaz44** [comment]
> Could you try the latest release? https://github.com/NickvisionApps/Parabolic/releases/tag/2024.5.0

Yes, it started working for me after installing the new version, thanks.
