### ISSUE TITLE
Not working with aria2c on Windows11

### ISSUE THREAD

**Issue by yakki-minati** [NickvisionApps/Parabolic#766]
I have added aria2c to path but whenever I select the download with aria2c and download try to download any video or playlist the software freezes and become unresponsive.

**Comment by nlogozzo** [comment]
Could you try the latest release? https://github.com/NickvisionApps/Parabolic/releases/tag/2024.5.0

**Comment by yakki-minati** [comment]
Not Fixed yet, still the same problem.
