### ISSUE TITLE
(Feature) 1-click download button/mode

### ISSUE THREAD

**Issue by joewood9364** [NickvisionApps/Parabolic#771]
Thanks for this great app which I use everyday. I would like to request a "1-click download" or "Validate & Download" button alongside the current "Validate" button.

Essentially this button will validate & confirm in 1 step rather than 2 by using the default configuration from the app preferences.
(If the download is not valid then just mark it as erroneous in the download list.)

**Comment by nlogozzo** [comment]
We could add an option to Preferences: `Download Immediately After Validation` to allow Parabolic to do this if the setting is turned on. This will prevent the need to add a secondary button to the dialog as well.

**Comment by pyrareae** [comment]
The ability to ctrl-v a link and automatically start the download without any other input would be nice

**Comment by nlogozzo** [comment]
Parabolic [V2024.9.0-beta3](https://github.com/NickvisionApps/Parabolic/releases/tag/2024.9.0-beta3) is here with a fix for this issue. 

Please test it and let me know how it goes :)
