### ISSUE TITLE
Don't use SponsorBlock's "jump to highlight" functionality

### ISSUE THREAD

**Issue by p3732** [NickvisionApps/Parabolic#774]
Hi, loving the app! The SponsorBlock integration is beautiful too, though I have stumbled upon issues with it when a highlight was set on the video, it was only downloaded from there.

Maybe the integration can be tuned to not use jump-to-highlight? And while at it, maybe also don't skip "filler" sections. I feel both features of SponsorBlock aren't all that useful when downloading videos.

Thanks for your work!

**Comment by nlogozzo** [comment]
> And while at it, maybe also don't skip "filler" sections

This is something I can do.

> Maybe the integration can be tuned to not use jump-to-highlight?

This i don't know about.

This is yt-dlp's sponsorblock documentation:
```
--sponsorblock-remove CATS      SponsorBlock categories to be removed from
                                the video file, separated by commas. If a
                                category is present in both mark and remove,
                                remove takes precedence. The syntax and
                                available categories are the same as for
                                --sponsorblock-mark except that "default"
                                refers to "all,-filler" and poi_highlight,
                                chapter are not available
```

**Comment by nlogozzo** [comment]
Do you have a video URL for me that I can use to test?

**Comment by p3732** [comment]
Hi, so the "jump to highlight" issue seems to be gone in the meantime, I tested multiple videos and could not reproduce it anymore.

Regarding the filler issue, that can still be reproduced, e.g. with https://www.youtube.com/watch?v=jN7mSXMruEo

**Comment by nlogozzo** [comment]
Parabolic [V2024.9.0-beta1](https://github.com/NickvisionApps/Parabolic/releases/tag/2024.9.0-beta1) is here with a fix for this issue!

Please follow the install instructions on the page to test it out :)
