### ISSUE TITLE
[Bug] It is no longer possible to download media from Twitter

### ISSUE THREAD

**Issue by Heus-Sueh** [NickvisionApps/Parabolic#775]
It is no longer possible to download media from Twitter, this occurs because of the url change from `twitter.com` to `x.com`, there is a way to get around this by changing the media url to `twitter.com` instead of `x.com`

**Comment by nlogozzo** [comment]
This has been fixed by yt-dlp. We just need to wait for them to release a new version.

Will keep this open to track when that happens.

**Comment by nlogozzo** [comment]
Hi,

A new version of yt-dlp has been released. However, I am currently working on a big update for Parabolic that I plan to have finished by the end of the weekend. So please wait until then for the new Parabolic update.

Thanks :)

**Comment by nlogozzo** [comment]
Parabolic [V2024.9.0-beta1](https://github.com/NickvisionApps/Parabolic/releases/tag/2024.9.0-beta1) is here with a fix for this issue!

Please follow the install instructions on the page to test it out :)
