### ISSUE TITLE
Unable to install yt-dlp (Windows 10 Installer - V2024.5.0)

### ISSUE THREAD

**Issue by ErickPhoen1x** [NickvisionApps/Parabolic#776]
I'm trying to install Parabolic but I'm getting the "Unable to install yt-dlp" error. I tried installing it both on the 'C:\Program Files (x86)\Nickvision Parabolic' directory and on the 'D:\Nickvision Parabolic' directory but both had the same issue.
And I don't have a Python folder in C:\Program Files nor C:\Program Files (x86).
![awsqd](https://github.com/NickvisionApps/Parabolic/assets/126206073/75f35ef1-93ac-4e26-8b33-5e45562391a7)

**Comment by nlogozzo** [comment]
Do you have python already installed on your system by chance?

**Comment by ErickPhoen1x** [comment]
I might have it since I remember using it a long time ago but I don't know where to find it.

**Comment by medo-ma** [comment]
![NickvisionTubeConverterSetup tmp_7pgegSGzJA](https://github.com/NickvisionApps/Parabolic/assets/172166330/7986e519-742a-4afd-9bfa-49891d726acd)
i got the same error, i tried uninstalling all py versions then reinstalling py 3.11 + parabiloc and still as the same.
As I remember, everything happened after I installed py 3.12.

**Comment by medo-ma** [comment]
the installer unable to install yt-dlp on his own for some reason, so after the instalation completed,  i installed the yt-dlp modul using pip [link](https://github.com/yt-dlp/yt-dlp/wiki/Installation#with-pip) and parabolic works now 💞😁.
![NickvisionTubeConverter WinUI_VqlzGLf47k](https://github.com/NickvisionApps/Parabolic/assets/172166330/b998ed72-e67f-4fcc-85bc-07c79f2e4544)

**Comment by nlogozzo** [comment]
Parabolic [V2024.9.0-beta1](https://github.com/NickvisionApps/Parabolic/releases/tag/2024.9.0-beta1) is here with a fix for this issue!

Please follow the install instructions on the page to test it out :)
