### ISSUE TITLE
[bug] Crashes when attempting to download, or opening the downloads tab

### ISSUE THREAD

**Issue by itsZainBoi** [NickvisionApps/Parabolic#778]
Whenever I try to download anything from youtube, or even reddit, the app crashes. Even clicking on the downloads tab crashes the app.

**Debug-info:**

org.nickvision.tubeconverter
2024.5.0

Microsoft Windows NT 10.0.26100.0
en-DM
yt-dlp 2024.04.09
ffmpeg version 2024-05-15-git-7b47099bc0-full_build-www.gyan.dev
aria2 version 1.37.0

**Comment by brunodelucasbarbosa** [comment]
I have too problem!
org.nickvision.tubeconverter
2024.5.0

Microsoft Windows NT 10.0.19045.0
pt-BR
ffmpeg version 2024-05-15-git-7b47099bc0-full_build-www.gyan.dev
yt-dlp 2024.04.09
aria2 version 1.37.0

**Comment by nlogozzo** [comment]
Parabolic is currently being rewriten to fix a bunch of issues and performance....stay tunned for more

**Comment by DilukshanN7** [comment]
Same

**Comment by Maanyaaz** [comment]
Hi, I am having the same issue. As soon I click to authenticate a link, the app closes. Can you please help?

**Comment by nlogozzo** [comment]
> Hi, I am having the same issue. As soon I click to authenticate a link, the app closes. Can you please help?

Hi, can you open a new issue for us to track? And can you provide some more information (the operating system you are using, if Linux is it flatpak or snap, the version of Parabolic you are using from the about dialog) ?

**Comment by Maanyaaz** [comment]
I just opened issue #989 Please disregard #990, I opened that accidentally.
