### ISSUE TITLE
temp files (=data currently downloaded) should be stored in the destination folder

### ISSUE THREAD

**Issue by antistress** [NickvisionApps/Parabolic#779]
Hi,
For large files (like those handle by Parabolic) having temp files (=data currently downloaded until the file is complete) in system tree looks like a bad idea.
In my case my home directory is almost full whereas the destination folder have plenty of space
For exemple, using the flatpak version, temp files are stored in /home/my_user/.var/app/org.nickvision.tubeconverter/cache/ whereas destination folder is on another disk.
Thanks

**Comment by nlogozzo** [comment]
With the C++ rewrite, I have rewritten the download engine and this will now be the new behavior.

**Comment by antistress** [comment]
Thanks
I see with 2024.5.0 flatpak version it's still not the case, what is the roadmap for the C++ rewrite ?

**Comment by nlogozzo** [comment]
> what is the roadmap for the C++ rewrite ?

You can check the TODO list under the PR #782 for what is left for it to be finished. Little by little I am working on it and completing it. I hope to have the done by the end of the week...but i've been saying that for a few weeks 😅

**Comment by nlogozzo** [comment]
Parabolic [V2024.9.0-beta1](https://github.com/NickvisionApps/Parabolic/releases/tag/2024.9.0-beta1) is here with a fix for this issue!

Please follow the install instructions on the page to test it out :)

**Comment by antistress** [comment]
Hi !
I tried V2024.9.0-beta1 with several downloads at the same time and it works great :)
One suggestion ans one question.

Question : could downloads have pause and resume button ?

Suggestion : while downloading Parabolic adds a lot a file in the destination folder.
Maybe files from the same link could be gathered together ?
See screenshots (from video-downloader) :
![Capture d’écran du 2024-09-08 08-38-26](https://github.com/user-attachments/assets/74cadb49-b534-48b4-8ad3-cf45b2346747)
![Capture d’écran du 2024-09-08 08-38-42](https://github.com/user-attachments/assets/9b0e648e-0c3c-4e13-98b6-61b90c05cca1)
