### ISSUE TITLE
Download from YouTube fails/hangs

### ISSUE THREAD

**Issue by Mycohl** [NickvisionApps/Parabolic#786]
Downloading a specific video from YT fails, either with an error or by freezing while waiting for download.

Note that this may have something to do with YT's new "ad-injection" process, but I am unsure. The reason I suspect this is because when the video first loads on the YT site, it shows a length of 5:34, but then changes to 5:57.

Version: Latest Flathub (2024.5.0)
URL: https://www.youtube.com/watch?v=4CTyOyaUVHs

Steps to repro: 
1. Attempt to download the above video URL

I have tried closing and re-opening Parabolic several times, and I've also rebooted and reset router.
Downloading using a third-party website appears to work, although the video length is only 5:33.

[error.txt](https://github.com/user-attachments/files/16059067/error.txt)

**Comment by nlogozzo** [comment]
This has been fixed in the C++ branch.

**Comment by nlogozzo** [comment]
Parabolic [V2024.9.0-beta1](https://github.com/NickvisionApps/Parabolic/releases/tag/2024.9.0-beta1) is here with a fix for this issue!

Please follow the install instructions on the page to test it out :)
