### ISSUE TITLE
Unable to download videos marked as "inappropriate for some users"

### ISSUE THREAD

**Issue by kongysoftware** [NickvisionApps/Parabolic#793]
(using Flatpak version on Fedora 40)
Results in "ERROR: unable to download video data: HTTP Error 403: Forbidden"

**Comment by nlogozzo** [comment]
What is the file format you are trying to download?

**Comment by kongysoftware** [comment]
I am trying to download an .MP4 in the best quality.

**Comment by nlogozzo** [comment]
Can you provide the link to the video you are trying to download?

**Comment by kongysoftware** [comment]
I am not entirely sure whether it is because of the inappropriate tag, but there have been many videos I've tried to repeatedly download that result in the same error every time, and that was what they all had in common.
Here is one of the videos.
[](https://youtu.be/FzEFwH8_K5U?si=v8R2jKHNf7i_kIcf)

**Comment by kongysoftware** [comment]
I have also just tried downloading these videos in .WEBM and .MP3 and it results in the same error.

**Comment by nlogozzo** [comment]
This is fixed in the C++ branch

**Comment by nlogozzo** [comment]
Parabolic [V2024.9.0-beta1](https://github.com/NickvisionApps/Parabolic/releases/tag/2024.9.0-beta1) is here with a fix for this issue!

Please follow the install instructions on the page to test it out :)
