### ISSUE TITLE
macOS version?

### ISSUE THREAD

**Issue by hyuri** [NickvisionApps/Parabolic#816]
Hey! Any chances/plans for a macOS version? It's the best downloader on Linux and there's nothing like it on mac.

**Comment by nlogozzo** [comment]
Duplicate of #751

> I no longer have access to a Mac, however Parabolic does not have a QT version that should in theory build and run on macOS without issues...I will try to set that up in the near future.

**Comment by platform-kit** [comment]
any update on MacOS support?
