### ISSUE TITLE
UI not being translated

### ISSUE THREAD

**Issue by yoseforb** [NickvisionApps/Parabolic#819]
The application's UI appears in English, not Hebrew, in the latest development build (Parabolic is fully translated to Hebrew).

Steps:
- Build with flatpak-builder
- Run using: `LANG=he_IL.UTF-8 flatpak run org.nickvision.tubeconverter`
- UI displays in English

Expected: UI in Hebrew
Actual: UI in English

Build info: Latest dev version, built with flatpak-builder
Note: This might be related to gettext initialization.

**Comment by nlogozzo** [comment]
Ah this was my fault. Will be fixed in the next beta!

**Comment by nlogozzo** [comment]
Parabolic [V2024.9.0-beta3](https://github.com/NickvisionApps/Parabolic/releases/tag/2024.9.0-beta3) is here with a fix for this issue. 

Please test it and let me know how it goes :)

**Comment by yoseforb** [comment]
It works. Thanks you!
