### ISSUE TITLE
Allow selection of audio bitrates

### ISSUE THREAD

**Issue by nlogozzo** [NickvisionApps/Parabolic#823]
Similar to resolutions for videos.

**Comment by nlogozzo** [comment]
A fix for this issue can be found in [V2024.10.0-rc1](https://github.com/NickvisionApps/Parabolic/releases/tag/2024.10.0-rc1).

Please follow the instructions on that page to install this version and test out the fix.

*Please wait an hour after this comment for the update to be pushed to `flathub-beta`*

**Comment by janos-r** [comment]
Still can't select audio quality it seams...
