### ISSUE TITLE
snap pre-release versions don't start

### ISSUE THREAD

**Issue by elio567** [NickvisionApps/Parabolic#827]
After clicking on icon app parabolic nothing open. 
terminal show this: 
@laptop:~$ tube-converter
Content snap command-chain for /snap/tube-converter/582/gpu-2404/bin/gpu-2404-provider-wrapper not found: ensure slot is connected

ubuntu 24.04

**Comment by nlogozzo** [comment]
@soumyaDghosh

**Comment by soumyaDghosh** [comment]
Known issue.. :sob: 

Please wait...

https://forum.snapcraft.io/t/auto-connect-request-for-tagger-and-tube-converter/41958/2

Until then, please run these

```bash
sudo snap connect tube-converter:gpu-2404 mesa-2404
sudo snap connect tube-converter:gnome-46-2404 gnome-46-2404
sudo snap connect tube-converter:ffmpeg-2404 ffmpeg-2404
```
It'll be fixed.

**Comment by nlogozzo** [comment]
Any update on this?

**Comment by soumyaDghosh** [comment]
> Any update on this?

I'm trying to push about this... But sorry, till now not much😓

**Comment by soumyaDghosh** [comment]
This has been fixed!!!
