### ISSUE TITLE
Log command in debug information

### ISSUE THREAD

**Issue by Charlignon** [NickvisionApps/Parabolic#832]
## Context
Hello ! First off, I want to say that this is the best yt-dlp gui that I have used so far. Beautiful, powerful and efficient !
I experienced a few issues during download, which are probably related to #790 or https://github.com/ytdl-org/youtube-dl/issues/32905. I don't mind those. When a download fail, I like to manually run the command via CLI, as changing parameters sometimes fix things. However, there is no easy way to get the command ran by Parabolic

## Suggestion
Log the full command with options at the beginning of the debug log, for easy copy-paste into a CLI

![image](https://github.com/user-attachments/assets/d1ace085-b341-4cf0-a44d-5a699c5b6787)

## Notes 
Install : 2024.5.0 / linux / snap
I don't mind coding it myself and opening an PR, but I wanted to check if this was okay first !

**Comment by nlogozzo** [comment]
Sounds like a good idea!

I can take care of the implementation, shouldn't be too hard, unless you'd like to attempt it.

Keep in mind that the latest version of Parabolic is V2024.9.0-beta3 which features a new C++ codebase and a fix to the download issue you mentioned.

**Comment by Charlignon** [comment]
It's been a few years since I've done cpp, so I will let it in your care, if this is not a hurdle.
I've migrated to the beta version in the meantime and does fix issues with the few 403 downloads I had :ok_hand:

**Comment by nlogozzo** [comment]
> It's been a few years since I've done cpp, so I will let it in your care, if this is not a hurdle.

No problem at all :)

> I've migrated to the beta version in the meantime and does fix issues with the few 403 downloads I had 👌

Glad to hear!

**Comment by nlogozzo** [comment]
A fix for this issue can be found in [V2024.10.0-rc1](https://github.com/NickvisionApps/Parabolic/releases/tag/2024.10.0-rc1).

Please follow the instructions on that page to install this version and test out the fix.

*Please wait an hour after this comment for the update to be pushed to `flathub-beta`*
