### ISSUE TITLE
2024.9.0-beta3/http error

### ISSUE THREAD

**Issue by ozky84** [NickvisionApps/Parabolic#834]
That http bug is here again flatpak beta3 version...

`ERROR: unable to download video data: HTTP Error 403: Forbidden`

**Comment by nlogozzo** [comment]
What is the URL you are trying to download?

**Comment by ozky84** [comment]
Any of these as video and mp3 download...
I also tested other yt-dlp gui from flathub they have same problem...
So problem is in yt-dlp?

https://www.youtube.com/@finntop5/videos
https://www.youtube.com/@FinnishFinest/videos
https://www.youtube.com/@Gangstakuiskaaja/videos
https://www.youtube.com/@karpoforever/videos
https://www.youtube.com/@vmakipelto/videos
https://www.youtube.com/@pmikkonen/videos
https://www.youtube.com/@finhistorychannel5210/videos

**Comment by nlogozzo** [comment]
I was able to download this video no problem: https://www.youtube.com/watch?v=RUqGlWr5LBA

![image](https://github.com/user-attachments/assets/820da412-7744-4743-98ff-cad60200f9cd)

Could be maybe YouTube is rate limiting you....

**Comment by ozky84** [comment]
I think you right, it works out of box with vpn...
