### ISSUE TITLE
The subtitle language option within the downloads section has not been successful to download

### ISSUE THREAD

**Issue by robertospenha** [NickvisionApps/Parabolic#838]
The subtitle language option within the downloads section has not been successful to download subtitles in Brazilian Portuguese. 

I used this option and it worked normally, but about 15 days ago I realized that it no longer works I downloaded the latest beta version to see if I had a solution and noticed that the subtitle languages option was removed. Given this, I would like to know if it is an option of the project or if it is some technical limitation. 

And if I can keep hoping that this option will work again. 

I thank you for your attention and I congratulate you on your work.

**Comment by nlogozzo** [comment]
The subtitles option has been removed from the downloads section in Preferences,  yes you are correct.

But, if you update to the latest beta version (V2024.10.0-rc1) you will see that when you add a new download, the dialog will have a new subtitles section that will allow you to select and see the available subtitles to download for an individual video.

Try it out and let me know how it goes !

**Comment by robertospenha** [comment]
Thank you for your reply. 
I only had one question. Previously I had no limitation to have the subtitles of the videos in Portuguese. However, now some videos only have the English option. 
Another one that used to get the subtitles in Portuguese appeared only the options in English, German and Spanish. Maybe it's a limitation imposed by youtube that it didn't have in the past. 
However, these same videos I can access the subtitles in Portuguese if I am on the youtube platform.

**Comment by nlogozzo** [comment]
Could you provide me with the URL(s) of the videos you are trying to access the subtitles for? I will do some testing of my own and hopefully improve it.

**Comment by robertospenha** [comment]
These three videos contemplate the various scenarios that I perceived problematic. 

Before I could get any of these videos in Brazilian Portuguese now I am restricted only to these options indicated in the links.

https://www.youtube.com/watch?v=ZAZlmYKrwfk - No language

https://www.youtube.com/watch?v=Sjt5R6wlEIk - Only English

https://www.youtube.com/watch?v=Sjt5R6wlEIk - English, Spanish and German

**Comment by nlogozzo** [comment]
Could you go into the app's Preferences ans check if you have turned on "Include Auto-Generated Subtitles" and try again.

**Comment by robertospenha** [comment]
For the first video it worked, the Portuguese option appeared. 

However, for this video only the subtitles in English remain and the auto-generated only in English - https://www.youtube.com/watch?v=Sjt5R6wlEIk 

The first case was a mistake on my part by not setting up the beta version well. However, I noticed something that for my type of use got worse. 

Now I have to for each video go down to the subtitle option of my target language. And in the current version it was enough to leave the language codes activated. And it already left English and Portuguese standard.

I don't know if it makes a difference from a technical point of view to keep the previous option (which is in the stable version) in which I can leave pre-configured in the general options the subtitles I want for my videos. And maybe allow the user to adjust it if they want in specific situations, such as adding Spanish. But then he would already have the pre-configured language options already checked.

**Comment by nlogozzo** [comment]
> I don't know if it makes a difference from a technical point of view to keep the previous option (which is in the stable version) in which I can leave pre-configured in the general options the subtitles I want for my videos. And maybe allow the user to adjust it if they want in specific situations, such as adding Spanish. But then he would already have the pre-configured language options already checked.

I will implement this

**Comment by robertospenha** [comment]
Thank you. Congratulations on your work. Certainly many people are benefiting from this project. 

Long life for you and the parabolic

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Parabolic/releases/tag/2024.10.0-rc2
