### ISSUE TITLE
Video downloading at incorrect resolution

### ISSUE THREAD

**Issue by kreesto** [NickvisionApps/Parabolic#858]
Parabolic 2024.10.0 installed from Flathub
Fedora Linux 40
Gnome 46.5
Kernel Linux 6.10.11-200.fc40.x86_64

URLs used to test:
https://www.youtube.com/watch?v=wmiMa-ZNMrY
https://www.youtube.com/watch?v=nlqpw1qIekY

After adding the URL and validating, I set the quality from 'best' to '1920 x 1080'.  All other parameters were left at the default (mp4 video, default audio language, etc).  The video downloaded without error, but checking the properties of the video shows that it has a resolution of 480 x 360.  This happened with both test URLs.

I re-ran the test and left the quality setting at it's default of 'best'.  Each video downloaded at 1920 x 1080.

**Comment by nlogozzo** [comment]
[V2024.10.1](https://github.com/NickvisionApps/Parabolic/releases/tag/2024.10.1) is here with a fix for this issue :)

*Allow it some time to be available via Flathub*
