### ISSUE TITLE
Unable to download with aria2c

### ISSUE THREAD

**Issue by sinthesizer** [NickvisionApps/Parabolic#860]
I can download using default settings(using yt-dlp) but when I add aria2 in preferences and hit the download button the app freezes. I didn't have this problem before the update, everything worked fine with aria2 chosen. I'm using the flatpak version. I'm running Linux Mint 22 also.

**Comment by nlogozzo** [comment]
[V2024.10.1](https://github.com/NickvisionApps/Parabolic/releases/tag/2024.10.1) is here with a fix for this issue :)

*Allow it some time to be available via Flathub*
