### ISSUE TITLE
YouTube's links issue

### ISSUE THREAD

**Issue by Muhammed-d-art** [NickvisionApps/Parabolic#869]
I have a problem with the newest parabolic flathub's version, I Can't enter any youtube url when i can write it manually it doesn't validate the url .

**Comment by nlogozzo** [comment]
Could you provide me with the link you are trying to enter manually?

Parabolic will only recognize true URL links, i.e. it must have `http://` or `https://` in front of it.

**Comment by Muhammed-d-art** [comment]
https://youtu.be/N6w5qE2g8cI?si=UzL3WvvjkenaI8MD

**Comment by Muhammed-d-art** [comment]
I'm sorry, The issue is on my python environment i solve it 🤣
