### ISSUE TITLE
Parabolic 2024.10.0 (Snap) Fails to Detect Installed ffmpeg on Ubuntu 24.04

### ISSUE THREAD

**Issue by romulo-godoi** [NickvisionApps/Parabolic#874]
Hello everyone, I'd like to report an inconsistency occurring with Parabolic 2024.10.0 (Snap) on Ubuntu 24.04.

It seems that the application is unable to detect the ffmpeg installed on the operating system. When we try to download a file, the following error occurs: ERROR: Postprocessing: ffmpeg not found. Please install or provide the path using --ffmpeg-location.

As shown in the attached image, ffmpeg is indeed installed on the system, but Parabolic cannot detect it. I couldn't find an option in the settings to manually specify the path.

![Captura de tela de 2024-10-08 15-00-45](https://github.com/user-attachments/assets/f026df7d-3340-4180-8fa6-ec6acee636fc)

![Captura de tela de 2024-10-08 14-58-52](https://github.com/user-attachments/assets/c21c9b26-464c-4adf-8344-441c861ce7e3)

**Comment by nlogozzo** [comment]
@soumyaDghosh I thought this was just fixed?

**Comment by soumyaDghosh** [comment]
@romulo-godoi please share the output of

``` 
snap info tube-converter
```

**Comment by soumyaDghosh** [comment]
Is it even possible to download a video it ffmpeg isn't available?

**Comment by mdsadiqueinam** [comment]
Is there any workaround to fix

**Comment by soumyaDghosh** [comment]
Please refresh `ffmpeg-2404`.

`sudo snap refresh ffmpeg-2404`

**Comment by mdsadiqueinam** [comment]
> Please refresh `ffmpeg-2404`.
> 
> `sudo snap refresh ffmpeg-2404`

Working perfectly

**Comment by romulo-godoi** [comment]
> Please refresh `ffmpeg-2404`.
> 
> `sudo snap refresh ffmpeg-2404`

This worked for me too. Thanks.
