### ISSUE TITLE
Completed/Queued List is not scrollable 

### ISSUE THREAD

**Issue by mdsadiqueinam** [NickvisionApps/Parabolic#876]
OS: Ubuntu 24.04

![Screenshot from 2024-10-09 16-31-07](https://github.com/user-attachments/assets/729c80e5-9e1b-4edf-b653-9c3a18d4e64d)

**Comment by nlogozzo** [comment]
[V2024.10.1](https://github.com/NickvisionApps/Parabolic/releases/tag/2024.10.1) is here with a fix for this issue :)

*Allow it some time to be available via Flathub*
