### ISSUE TITLE
id3 tags usage in the new version

### ISSUE THREAD

**Issue by japkov** [NickvisionApps/Parabolic#880]
since the new rewrite release every file downloaded with parabolic includes web address in "comments" field in id3 tags and some files get "index-v1-a1" string put in the "title" field, while previously downloaded files do not include anything.

issue occurs with flatpak version on manjaro - tho, i'm pretty sure this is a platform-indepented thing

would be nice if the pre-download modal would include an option for NOT using id3 tags

**Comment by nlogozzo** [comment]
Do you have `Remove Source Data` turned on in the app's settings?

**Comment by japkov** [comment]
the config.json? i wasn't modifying it before and it's set to `false`. if you're talking about any ui feature that manages this setting, i see none

setting "RemoveSourceData":true doesn't affect files and tags fields are still being populated as above

**Comment by nlogozzo** [comment]
Could you provide the link to the video you are trying to download?
