### ISSUE TITLE
main window position is not being saved between launches

### ISSUE THREAD

**Issue by japkov** [NickvisionApps/Parabolic#881]
pre-rewrite version couldn't remember window size but it did its remember position. newst version does the opposite: it does remember size but always starts in the bottom right corner of the screen, ignoring xfce setting of placing windows in the mid of the screen

issue occurs with flatpak version on manjaro under xfce

**Comment by nlogozzo** [comment]
GTK4 and Wayland do not support remembering Windows Geometry (i.e. position) only size.

**Comment by realgooseman** [comment]
Same problem on Windows 11. Previous window size and position is not remembered on launch.
