### ISSUE TITLE
[REQ] integrated manifests detector

### ISSUE THREAD

**Issue by MarcoRavich** [NickvisionApps/Parabolic#882]
Hi there, 1st of all thanks for this great tool !

I just discovered [The Stream Detector addon](https://github.com/54ac/stream-detector#readme) has been archived more than a year ago.

It would be extremely useful to integrate that functionalities in Parabolic.

Hope that inspires.

**Comment by nlogozzo** [comment]
I'm confused as to what the feature this extension does that you would like to see in Parabolic...

**Comment by MarcoRavich** [comment]
> I'm confused as to what the feature this extension does that you would like to see in Parabolic...
>
Well, the extension detects (and creates formatted links to) m3u8 and similar from a webpage...

**Comment by nlogozzo** [comment]
Yes, but isn't this what yt-dlp already does when you provide a URL to validate/download?

**Comment by MarcoRavich** [comment]
> Yes, but isn't this what yt-dlp already does when you provide a URL to validate/download?

Well not exactly (AFAIK): you have to provide a valid manifest (m3u8 for example) direct link to let it download...
...but can you extract it from this link ?
https://nove.tv/programmi-nove/fratelli-di-crozza-dove-vederlo-tv-streaming

What I mean is that it would be cool to drop a link like the above one into Parabolic and just choose which manifest (automatically retrieved) to "process".

**Comment by nlogozzo** [comment]
Parabolic is just a `yt-dlp` frontend. I don't really have the knowledge to implement a feature like this from scratch if there is no library that already supports it.

When trying to run that URL through `yt-dlp` this is what I get:
```
> yt-dlp https://nove.tv/programmi-nove/fratelli-di-crozza-dove-vederlo-tv-streaming
[generic] Extracting URL: https://nove.tv/programmi-nove/fratelli-di-crozza-dove-vederlo-tv-streaming
[generic] fratelli-di-crozza-dove-vederlo-tv-streaming: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] fratelli-di-crozza-dove-vederlo-tv-streaming: Extracting information
ERROR: Unsupported URL: https://nove.tv/programmi-nove/fratelli-di-crozza-dove-vederlo-tv-streaming
```

I recommend opening an issue on `yt-dlp`'s repo to get this implemented.

**Comment by MarcoRavich** [comment]
You can extract the m3u8 link using the above extension and paste the link into Parabolic to easily download the video.

Thanks anyway.
