### ISSUE TITLE
Unable to change download directory

### ISSUE THREAD

**Issue by GrahamLees** [NickvisionApps/Parabolic#883]
V 2024.10.0
The ability to change the download directory appears to have been removed. The default in Linux is now ~/Downloads whereas it used to be in~/Downloads/Parabolic/.
Will that facility be restored?

**Comment by nlogozzo** [comment]
![Untitled](https://github.com/user-attachments/assets/ba249339-4282-43f9-beb9-d544a4ede732)

There is this button here that you can click to change the download directory....

**Comment by GrahamLees** [comment]
Oops! missed that. Thanks for the reply 😳
