### ISSUE TITLE
Can't download videos in a quality other than "Best" anymore

### ISSUE THREAD

**Issue by Victor239** [NickvisionApps/Parabolic#885]
See https://youtu.be/bB3-CUMERIU as an example, I can't download in 1920x1080, 2560x1440, etc - only selecting "Best" quality works.

**Comment by Victor239** [comment]
The download fails with an error.

**Comment by nlogozzo** [comment]
Can you provide the log with the error for the failing downloads?

**Comment by Victor239** [comment]
```
[youtube] Extracting URL: https://www.youtube.com/watch?v=bB3-CUMERIU
[youtube] bB3-CUMERIU: Downloading webpage
[youtube] bB3-CUMERIU: Downloading ios player API JSON
[youtube] bB3-CUMERIU: Downloading web creator player API JSON
[youtube] bB3-CUMERIU: Downloading m3u8 information
ERROR: [youtube] bB3-CUMERIU: Requested format is not available. Use --list-formats for a list of available formats
```

**Comment by nlogozzo** [comment]
I have solved this issue and will be released later today.

**Comment by nlogozzo** [comment]
[V2024.10.1](https://github.com/NickvisionApps/Parabolic/releases/tag/2024.10.1) is here with a fix for this issue :)

*Allow it some time to be available via Flathub*

**Comment by Victor239** [comment]
Thanks!
