### ISSUE TITLE
Restore Select/Deselect All Buttons for Subtitles and Playlist Items

### ISSUE THREAD

**Issue by KSMaan45** [NickvisionApps/Parabolic#889]
Current parabolic have no option to select and deselect all videos button for the playlist which was present in older version

Version 2024.5.0 from aur
![Screenshot from 2024-10-13 19-43-23](https://github.com/user-attachments/assets/8bb3f1ed-854f-483e-b088-a56b562510ff)

Version 2024.10.0 from flathub
![Screenshot from 2024-10-13 19-42-37](https://github.com/user-attachments/assets/fc52b1ad-f663-4a1d-ba9f-1ccd5ce21efe)

**Comment by nlogozzo** [comment]
[V2024.10.2](https://github.com/NickvisionApps/Parabolic/releases/tag/2024.10.2) is here with a fix for this issue!
