### ISSUE TITLE
Home directory xdg .desktop silently fails to launch after update

### ISSUE THREAD

**Issue by Mycohl** [NickvisionApps/Parabolic#890]
Qualified name has changed, breaking old xdg .desktop files

Steps to repro:

1. Roll back to early commit (I used 7c907b14d47cec448424b24cd2c5b7a0707d58b58352458a99a794ead4bd4099 to test)
2. Copy exported .desktop file to somewhere in home directory (In Mint, "Add to desktop" works)
3. Update to latest version
4. Attempt to launch from home directory .desktop file

Result:
Previous .desktop file silently fails to launch

Expected:
Previous .desktop file would perhaps throw an error letting you know that flatpak qualified name had changed?

Note: I'm not sure if this is a bug in flatpak or something you can fix. Even setting the .desktop file Terminal=true doesn't bring up a terminal screen for some reason, so there's no way to figure out the problem other than by running the new exported .desktop file.

**Comment by nlogozzo** [comment]
The qualified name has been changed back to `Parabolic` with version V2024.10.1 that was released today. 

So this should be fixed once that hits flathub repos.
