### ISSUE TITLE
Error when downloading TikTok videos

### ISSUE THREAD

**Issue by Francehelder** [NickvisionApps/Parabolic#894]
When i try download any TikTok video, i get an error:

![image](https://github.com/user-attachments/assets/62f61677-cd3b-4722-8fbf-dc7c3e7209aa)

Links: 
https://www.tiktok.com/@omurilomoraes/video/7418715328529566982
https://vm.tiktok.com/ZMhy4WJMk/

Isn't a yt-dlp issue. yt-dlp downloaded both when i use the terminal using the same version that Parabolic is using.

**Comment by nlogozzo** [comment]
[V2024.10.2](https://github.com/NickvisionApps/Parabolic/releases/tag/2024.10.2) is here with a fix for this issue!
