### ISSUE TITLE
Add option to change app language

### ISSUE THREAD

**Issue by AuroraMartell** [NickvisionApps/Parabolic#896]
I installed the app and the Portuguese translation came extremely broken. Is there a way to add a feature in which the end user can change the language?

**Comment by nlogozzo** [comment]
Are you using Windows or Linux?

**Comment by AuroraMartell** [comment]
> Are you using Windows or Linux?

Windows 11.

**Comment by nlogozzo** [comment]
What's broken about the translation? 

Is it wrong? Or is the text displayed incorrectly?

**Comment by AuroraMartell** [comment]
> What's broken about the translation?
> 
> Is it wrong? Or is the text displayed incorrectly?

The latter.

But I'd still like to switch to English. Most of my media/writing apps are displayed in English.
