### ISSUE TITLE
windows ui design

### ISSUE THREAD

**Issue by OreonGIT** [NickvisionApps/Parabolic#898]
Will the interface appearance on the Windows version improve? I used this program a long time ago and remember the beautiful transparent design. A lot has changed since then, as I understand.

**Comment by nlogozzo** [comment]
The old version of Parabolic was written in C# and with WinUI 3 / WindowsAppSDK . 

This is still a new platform and unstable at times. The dependency management is a mess and if we didn't constantly update the WindowsAppSDK version with our installer, users were unable to even open Parabolic.

With the new version of Parabolic we switched the app from C# to C++. Trying to use the WindowsAppSDK with C++, while it is supported, is a big pain in the butt. Thus, we've switched to Qt which made our lives so much easier.

Qt uses native Windows Win32 styling. Until Microsoft adds support for Mica for Win32, the transparency is impossible.

I do plan however to improve the interface and bring back the navigation bar and some other improvements.
