### ISSUE TITLE
Aria2c not downloading

### ISSUE THREAD

**Issue by sinthesizer** [NickvisionApps/Parabolic#910]
Aria2c was ok in last version 2024.10.1, but with aria2c selected in 2024.10.2 downloads don't seem to work. Starts the download process, then says completed but lists Error -1 and nothing downloaded. This happens with Mp4 and HLS downloads. Downloads are fine using default settings without aria2c selected in 2024.10.2.

I'm using Linux Mint 22

**Comment by nlogozzo** [comment]
Can you try with [2024.10.3](https://github.com/NickvisionApps/Parabolic/releases/tag/2024.10.3)?

**Comment by nlogozzo** [comment]
I got a full MP4 file with aria2c no problem:
![image](https://github.com/user-attachments/assets/82493fe1-ea0b-4a9f-882b-cdf5688e904a)

Can you provide the URL you are trying to download?

**Comment by nlogozzo** [comment]
Worked again for me no problem:
![image](https://github.com/user-attachments/assets/caa15e00-b294-48a3-ba8e-abfcb377a9fb)

What download options are you use (i.e. file type, quality, etc...)?

**Comment by nlogozzo** [comment]
Could you also click the terminal button on the download row to show the log, and then click the terminal icon in the log..it will copy the download command that was used by Parabolic, then come and paste it here...
![Screenshot From 2024-11-01 10-08-05](https://github.com/user-attachments/assets/089f183e-38ff-4390-aa56-584dd182cfaf)

**Comment by sinthesizer** [comment]
/app/bin/yt-dlp https://www.youtube.com/watch?v=4fk2prKnYnI --xff default --no-warnings --progress --newline --progress-template [download] PROGRESS;%(progress.status)s;%(progress.downloaded_bytes)s;%(progress.total_bytes)s;%(progress.total_bytes_estimate)s;%(progress.speed)s --no-mtime --ffmpeg-location /app/bin/ffmpeg --force-overwrites --downloader /app/bin/aria2c --downloader-args aria2c:-x 16 -k 20M --embed-metadata --embed-thumbnail --convert-thumbnails jpg --remux-video mp4 --paths /home/asanga/Downloads --output B. B.%(ext)s --output chapter:%(section_number)03d - B. B.%(ext)s --postprocessor-args -threads 12

**Comment by sinthesizer** [comment]
Hope that's what you wanted.

**Comment by nlogozzo** [comment]
So far no fix still trying to investigate why it works for me and not for you :/

**Comment by nlogozzo** [comment]
Could you try to remove and reinstall the flatpak?

**Comment by nlogozzo** [comment]
> Could you try to remove and reinstall the flatpak?

When you remove the flatpak run `sudo rm -rf /home/$(whoami)/.var/app/org.nickvision.tubeconverter` before installing the flatpak again.

Otherwise we are unable to reproduce the issue.

**Comment by nlogozzo** [comment]
@sinthesizer Could you try running `sudo update-ca-certificates` on your system and try downloading again?

**Comment by nlogozzo** [comment]
> @sinthesizer Could you try running `sudo update-ca-certificates` on your system and try downloading again?

![image](https://github.com/user-attachments/assets/832df21c-99ae-4d95-937e-35192d44da28)

We've installed Linux Mint and tested the flatpak and again cannot reproduce the issue. 

Try running that command above and ensure certificates are correctly set up on your system.

If aria2c isn't needed for you tho, I recommend turning it off and let `yt-dlp` use it's default downloader.

**Comment by sinthesizer** [comment]
Sorry I haven't replied sooner. I found your Parabolic version 2024.11.1 fixed the aria2c problem. I didn't check my mail for some time, so I didn't get to try you previous suggestions. Your efforts are much appreciated. 



    On Tuesday, 12 November 2024 at 02:37:51 am AEDT, Nick Logozzo ***@***.***> wrote:  
 
 


Closed #910 as not planned.
