### ISSUE TITLE
Toolbar Menu dropdowns color choices don't fit rest of the UI

### ISSUE THREAD

**Issue by thisisartman** [NickvisionApps/Parabolic#919]
- The dropdown has a much deeper black than the rest of the app. Maybe use the same, or slightly darker, color as the highlight on the Help button. 
- Similarly, the drop shadow is just an inverted color. Try for something on the gray side. In fact, you could just swap the menu color with the drop shadow color and it would look pretty good for the most part.

![image](https://github.com/user-attachments/assets/abb4a6f5-6849-48fb-b8d1-a52b2e8aa9ea)

**Comment by nlogozzo** [comment]
This is not something that I control. This is the Win32 Qt style that's used on Windows 11
