### ISSUE TITLE
Error al validar el URL

### ISSUE THREAD

**Issue by kingapachai** [NickvisionApps/Parabolic#923]
Me encanta tu programa y todas sus opciones para descargar audio y videos e incluso separarlo por capítulos e incluir los subtítulos como .str; sin embargo, desde la última actualización dejo de funcionar, al colocar un URL se queda cargando eternamente, espero pueda solucionarse, ya que es mi programa favorito para descargar música/videos.
![imagen](https://github.com/user-attachments/assets/156289b6-d4f4-46ce-af55-f322e0a107b5)

**Comment by nlogozzo** [comment]
Hola! Primera, hablo italiano però tambien un poquito español entonces voy a probar de ayudarle.

Puede darme el URL que esta probando de descargar?

**Comment by nlogozzo** [comment]
Puede probar de usar la nueva version? [2024.10.3](https://github.com/NickvisionApps/Parabolic/releases/tag/2024.10.3)?

**Comment by kingapachai** [comment]
Hola, ya me funciono con la 10.3, muchas gracias!
