### ISSUE TITLE
Run as silent (non GUI) CLI tool

### ISSUE THREAD

**Issue by ScallyGames** [NickvisionApps/Parabolic#927]
Not sure if this is possibly already supported but undocumented or if it would be outside the scope of this application but I'd love being able to run downloads as a CLI tool.
I've found that you can provide the video URL as first command line argument but I'd love to be able to do something like

`parabolic [Video URL] --format=mp4 --output=~/songs/MySong.mp4`

and just have it silently download it in the background with the exit code providing feedback on success/failure.

This would allow integrating parabolic into automated workflows.

**Comment by nlogozzo** [comment]
Parabolic is a GUI wrapper around the `yt-dlp` CLI tool. Everything Parabolic provides can be accomplished with `yt-dlp` itself. The only features that Parabolic adds extra is a Keyring for website credentials and the option to view your download history.

I don't see these features as a good enough reason to add a CLI to Parabolic when like I said it can all be accomplished with `yt-dlp` itself. 

Unless you have another reason for it...

**Comment by nlogozzo** [comment]
This is where all the magic happens, where Parabolic takes all of the options available in the app and creates the argument vector to pass to yt-dlp: https://github.com/NickvisionApps/Parabolic/blob/main/libparabolic/src/models/downloadoptions.cpp#L199

You can read through the function and hopefully be able to come up with the correct options to pass to yt-dip yourself in your scripts. Let me know if you have any further questions.
