### ISSUE TITLE
The app dosen't save settings for speed limit

### ISSUE THREAD

**Issue by N013M** [NickvisionApps/Parabolic#937]
![image](https://github.com/user-attachments/assets/8e1471d2-bef7-4241-a38d-fb0faf79996b)

I can't find an option to turn off the speed limit so I tried to change the value to the maximum one allowed inside the app which is (10240) but when I close the setting window and reopen it again it switches back the speed limit to the default one .

**Comment by nlogozzo** [comment]
This fix is available in today's release! https://github.com/NickvisionApps/Parabolic/releases/tag/2024.11.0

*Please allow it some time to be available on Flathub*
