### ISSUE TITLE
GNOME - Generic Video Always `mkv`

### ISSUE THREAD

**Issue by sojusnik** [NickvisionApps/Parabolic#942]
When choosing `video (generic)` (as introduced in the newest version), then all files are downloaded as mkv. Tested it with different YT channels.

Preferred video codec: VP9

Even if I set `Preferred video codec:` to `generic`, then all downloads are still in mkv.

Troubleshooting:
```
org.nickvision.tubeconverter
Linux
2024.11.0

Deployment Mode: Flatpak
Locale: de_DE.UTF-8
Running From: "/app/lib/org.nickvision.tubeconverter"

yt-dlp version 2024.11.04
ffmpeg version 7.1 
aria2 Version 1.37.0

GTK 4.16.3
libadwaita 1.6.1

LANG=de_DE.UTF-8
LC_CTYPE="de_DE.UTF-8"
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_COLLATE="de_DE.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_MESSAGES="de_DE.UTF-8"
LC_PAPER="de_DE.UTF-8"
LC_NAME="de_DE.UTF-8"
LC_ADDRESS="de_DE.UTF-8"
LC_TELEPHONE="de_DE.UTF-8"
LC_MEASUREMENT="de_DE.UTF-8"
LC_IDENTIFICATION="de_DE.UTF-8"
LC_ALL=
```

**Comment by nlogozzo** [comment]
Can you provide me with some links you are using?

I just tried it and it's `webm` for me

**Comment by nlogozzo** [comment]
I'm still getting `webm` downloading `en-us` subtitles as well.

This is on Windows tho, let me try the flatpak...

**Comment by nlogozzo** [comment]
Ah okay on Linux i'm getting `mkv`...will investigate

**Comment by nlogozzo** [comment]
> Can you have a second look on it please?

Sure

**Comment by nlogozzo** [comment]
The problem is Parabolic was passing `--embed-thumbnail` to `yt-dlp` and `webm` does not support embedding thumbnails into the file. So `yt-dlp` picked `mkv` since `mkv` does support it embedding thumbnails. 

I will have Parabolic pass `--write-thumbnail` instead which will also `webm` to be picked instead again.

**Comment by nlogozzo** [comment]
[V2024.12.1](https://github.com/NickvisionApps/Parabolic/releases/tag/2024.12.1) is here with a fix for this issue!
