### ISSUE TITLE
Parabolic won't start on Windows 10

### ISSUE THREAD

**Issue by ViBE-HU** [NickvisionApps/Parabolic#945]
11.0 is the second build which won't start on my Windows 10 machines. I found this in the Event log:

```
- 
<Event
	xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- 
	<System>
		<Provider Name="Application Error" />
		<EventID Qualifiers="0">1000</EventID>
		<Version>0</Version>
		<Level>2</Level>
		<Task>100</Task>
		<Opcode>0</Opcode>
		<Keywords>0x80000000000000</Keywords>
		<TimeCreated SystemTime="2024-11-13T01:16:00.8536531Z" />
		<EventRecordID>20438</EventRecordID>
		<Correlation />
		<Execution ProcessID="0" ThreadID="0" />
		<Channel>Application</Channel>
		<Computer>PC</Computer>
		<Security />
	</System>
- 
	<EventData>
		<Data>org.nickvision.tubeconverter.qt.exe</Data>
		<Data>0.0.0.0</Data>
		<Data>67328b26</Data>
		<Data>ucrtbase.dll</Data>
		<Data>10.0.19041.3636</Data>
		<Data>81cf5d89</Data>
		<Data>c0000409</Data>
		<Data>000000000007286e</Data>
		<Data>1c2c</Data>
		<Data>01db356999b781ed</Data>
		<Data>C:\Program Files (x86)\Nickvision Parabolic\Release\org.nickvision.tubeconverter.qt.exe</Data>
		<Data>C:\Windows\System32\ucrtbase.dll</Data>
		<Data>39c02810-eeb5-41e3-b2d9-20eddc00891e</Data>
		<Data />
		<Data />
	</EventData>
</Event>
```

```
- 
<Event
	xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- 
	<System>
		<Provider Name="Windows Error Reporting" />
		<EventID Qualifiers="0">1001</EventID>
		<Version>0</Version>
		<Level>4</Level>
		<Task>0</Task>
		<Opcode>0</Opcode>
		<Keywords>0x80000000000000</Keywords>
		<TimeCreated SystemTime="2024-11-13T01:16:02.2398595Z" />
		<EventRecordID>20439</EventRecordID>
		<Correlation />
		<Execution ProcessID="0" ThreadID="0" />
		<Channel>Application</Channel>
		<Computer>PC</Computer>
		<Security />
	</System>
- 
	<EventData>
		<Data />
		<Data>0</Data>
		<Data>BEX64</Data>
		<Data>Nem érhető el</Data>
		<Data>0</Data>
		<Data>org.nickvision.tubeconverter.qt.exe</Data>
		<Data>0.0.0.0</Data>
		<Data>67328b26</Data>
		<Data>ucrtbase.dll</Data>
		<Data>10.0.19041.3636</Data>
		<Data>81cf5d89</Data>
		<Data>000000000007286e</Data>
		<Data>c0000409</Data>
		<Data>0000000000000007</Data>
		<Data />
		<Data />
		<Data>\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_org.nickvision.t_534be0a36549952b934085f8c659a1c3f327ea_5deae684_3239fc0b-17a8-443d-853b-bde6312c2581</Data>
		<Data />
		<Data>0</Data>
		<Data>39c02810-eeb5-41e3-b2d9-20eddc00891e</Data>
		<Data>4</Data>
		<Data />
		<Data>0</Data>
	</EventData>
</Event>
```

```
- 
<Event
	xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- 
	<System>
		<Provider Name="Windows Error Reporting" />
		<EventID Qualifiers="0">1001</EventID>
		<Version>0</Version>
		<Level>4</Level>
		<Task>0</Task>
		<Opcode>0</Opcode>
		<Keywords>0x80000000000000</Keywords>
		<TimeCreated SystemTime="2024-11-13T01:16:03.2536996Z" />
		<EventRecordID>20440</EventRecordID>
		<Correlation />
		<Execution ProcessID="0" ThreadID="0" />
		<Channel>Application</Channel>
		<Computer>PC</Computer>
		<Security />
	</System>
- 
	<EventData>
		<Data>1709307824938297756</Data>
		<Data>5</Data>
		<Data>BEX64</Data>
		<Data>Nem érhető el</Data>
		<Data>0</Data>
		<Data>org.nickvision.tubeconverter.qt.exe</Data>
		<Data>0.0.0.0</Data>
		<Data>67328b26</Data>
		<Data>ucrtbase.dll</Data>
		<Data>10.0.19041.3636</Data>
		<Data>81cf5d89</Data>
		<Data>000000000007286e</Data>
		<Data>c0000409</Data>
		<Data>0000000000000007</Data>
		<Data />
		<Data>\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD96B.tmp.WERInternalMetadata.xml</Data>
		<Data>\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_org.nickvision.t_534be0a36549952b934085f8c659a1c3f327ea_5deae684_3239fc0b-17a8-443d-853b-bde6312c2581</Data>
		<Data />
		<Data>0</Data>
		<Data>39c02810-eeb5-41e3-b2d9-20eddc00891e</Data>
		<Data>268435456</Data>
		<Data>1827254a5513f7aba7b8ae69153e299c</Data>
		<Data>0</Data>
	</EventData>
</Event>
```

**Comment by nlogozzo** [comment]
What version of Windows 10 are you running? Home or Pro? and what's the version provided by `winver`?

**Comment by nlogozzo** [comment]
Did you install Parabolic using the Setup exe or are you running the portable version?

**Comment by ViBE-HU** [comment]
Tried both versions. Both machine running always the latest Windows 10 Pro build. No Insider or preview enabled.

**Comment by nlogozzo** [comment]
![image](https://github.com/user-attachments/assets/97b720c3-8491-45b9-9161-942683d15b7c)

It works no problem on Windows 10 for me. Can you try installing the latest release?

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Parabolic/releases/tag/2024.11.1

**Comment by ViBE-HU** [comment]
No success. Same error logs referring to `ucrtbase.dll`

**Comment by nlogozzo** [comment]
Can you try installing the Visual C++ Redistributable: https://aka.ms/vs/17/release/vc_redist.x64.exe

And then reboot and run Parabolic again.

**Comment by ViBE-HU** [comment]
Sadly still not working. I hardly ever used it under Windows. because Ubuntu is my main system. But now I tested many versions and looks like the 2024.05 build is the last which works.

**Comment by nlogozzo** [comment]
It seems like there's something wrong with C/C++ on your system. `ucrtbase` is the Universal C Runtime. 2024.5.0 works because that was the last version built with C#.

Maybe this can help you: https://answers.microsoft.com/en-us/windows/forum/all/ucrtbasedll-not-found-error-stopping-programs-from/f66b09d9-3ece-4242-b5e5-40e3be4454c3

But like I said it's something wrong with C on your system I don't know what you've tried.

**Comment by ViBE-HU** [comment]
The article is totally nonsense. The systems integrity are okay. The application shows only some file associations and some 1-2 services. which are btw totally normal and working.

What is interesting that both systems have the same issue. But none of the systems are crowded or "dirty". I only installed necessary basic things to run my games and Office. Is it possible that some other programs can conflict or interfere with Parabolic? Even the C++ not changed anything. Or do I need some other components?

![cplusplus](https://github.com/user-attachments/assets/f61dedb2-6107-445f-b02e-b1e09067a3fe)

**Comment by ViBE-HU** [comment]
Found this article. Not the exact same issue, but the exception code is the same. I am not a software engineer. Does this comment makes any sense to you?

https://stackoverflow.com/questions/46779455/windows-c-service-faulting-on-ucrtbase-dll-when-starting#comment80506672_46779455

**Comment by ViBE-HU** [comment]
Tried to recreate the issue myself in a virtual machine with a clean install. No "success".

But somehow I just recreated another issue:

![VirtualBox_Windows 10_22_11_2024_01_36_52](https://github.com/user-attachments/assets/56e4b04a-f0e2-4d76-993f-312db53b8961)

I installed Windows 10 Pro and updated it. Maybe it is related somehow. First I installed the actual Parabolic build which looks okay. Then I installed 2024.05 and then all build step by step. This new(?) issue started from 2024.09 and the builds affected till 2024.10.3. So I guess with 2024.10.3 you made some related change. As I understand the issue might be language or encoding related. Or system environment maybe. The attached picture shows misaligned letters and the language is Hungarian. I maintain the translation, so I am pretty sure that the translation itself is fine and this is not some kind of mistake made by me.

**Comment by nlogozzo** [comment]
The issue was fixed in V2024.10.3 so it is no longer an issue.

**Comment by ViBE-HU** [comment]
This is a disaster. I also recreated the issue on a fresh Windows 11 Pro installation (build 22631.4541) and I cannot imagine yet how. But it must be way too easy to recreate. I don't install any C/C++ relate stuff manually. Programs do and Windows update. ATM I try to figure out which program can cause this, but it is also strange that only Parabolic fails to start on my systems.

**Comment by ViBE-HU** [comment]
@nlogozzo just a sidenote: the 2025.1.0 build is finally working on my systems.

**Comment by nlogozzo** [comment]
Glad to hear!
