### ISSUE TITLE
Parabolic application closes when you click on "add download"

### ISSUE THREAD

**Issue by Edgar-67** [NickvisionApps/Parabolic#951]
Hello, 
Following the update of Parabolic to version 2024.11.0 under Ubuntu 22.04.5 LTS, the Parabolic application closes when you click on "add download" in download media. 
The problem appears on 2 different PCs. 
Thank you for bringing the problem up. 
See you soon.

**Comment by nlogozzo** [comment]
Do you have Parabolic installed via flatpak or snap?

Can you run the app via the terminal and provide the output?

**Comment by Edgar-67** [comment]
Parabolic was installed via snap
Can you give me the command to launch Parabolic and get the output ?
Thanks

**Comment by nlogozzo** [comment]
`snap run tube-converter` I believe

**Comment by Edgar-67** [comment]
It's ok

$ snap run tube-converter
[INFO] Started GTK application.
file: /build/tube-converter/parts/tube-converter/src/org.nickvision.tubeconverter.gnome/src/application.cpp(30:26) `int Nickvision::TubeConverter::GNOME::Application::run()`

Gsk-Message: 22:28:34.197: Failed to realize renderer of type 'GskNglRenderer' for surface 'GdkX11Toplevel': OpenGL ES 3.0 n’est pas pris en charge par ce moteur de rendu.


(org.nickvision.tubeconverter.gnome:5168): Adwaita-WARNING **: 22:28:34.675: AdwNavigationPage 0x5ca9017250a0 is missing a title. To hide a header bar title, consider using AdwHeaderBar:show-title instead.

(org.nickvision.tubeconverter.gnome:5168): Adwaita-WARNING **: 22:28:34.675: AdwNavigationPage 0x5ca9017d2d90 is missing a title. To hide a header bar title, consider using AdwHeaderBar:show-title instead.
[INFO] Connected to Linux taskbar.
file: /build/tube-converter/parts/tube-converter/src/libparabolic/src/controllers/mainwindowcontroller.cpp(240:25) `Nickvision::App::WindowGeometry Nickvision::TubeConverter::Shared::Controllers::MainWindowController::startup(const std::string&)`

[INFO] Loaded 0 historic download(s).
file: /build/tube-converter/parts/tube-converter/src/libparabolic/src/models/downloadmanager.cpp(176:21) `size_t Nickvision::TubeConverter::Shared::Models::DownloadManager::startup()`

[INFO] Found 0 recoverable download(s).
file: /build/tube-converter/parts/tube-converter/src/libparabolic/src/models/downloadmanager.cpp(186:21) `size_t Nickvision::TubeConverter::Shared::Models::DownloadManager::startup()`

**Comment by nlogozzo** [comment]
Keep it running until you get the app to crash and provide that output.

**Comment by Edgar-67** [comment]
It's done

$ snap run tube-converter
[INFO] Started GTK application.
file: /build/tube-converter/parts/tube-converter/src/org.nickvision.tubeconverter.gnome/src/application.cpp(30:26) `int Nickvision::TubeConverter::GNOME::Application::run()`

Gsk-Message: 22:28:34.197: Failed to realize renderer of type 'GskNglRenderer' for surface 'GdkX11Toplevel': OpenGL ES 3.0 n’est pas pris en charge par ce moteur de rendu.


(org.nickvision.tubeconverter.gnome:5168): Adwaita-WARNING **: 22:28:34.675: AdwNavigationPage 0x5ca9017250a0 is missing a title. To hide a header bar title, consider using AdwHeaderBar:show-title instead.

(org.nickvision.tubeconverter.gnome:5168): Adwaita-WARNING **: 22:28:34.675: AdwNavigationPage 0x5ca9017d2d90 is missing a title. To hide a header bar title, consider using AdwHeaderBar:show-title instead.
[INFO] Connected to Linux taskbar.
file: /build/tube-converter/parts/tube-converter/src/libparabolic/src/controllers/mainwindowcontroller.cpp(240:25) `Nickvision::App::WindowGeometry Nickvision::TubeConverter::Shared::Controllers::MainWindowController::startup(const std::string&)`

[INFO] Loaded 0 historic download(s).
file: /build/tube-converter/parts/tube-converter/src/libparabolic/src/models/downloadmanager.cpp(176:21) `size_t Nickvision::TubeConverter::Shared::Models::DownloadManager::startup()`

[INFO] Found 0 recoverable download(s).
file: /build/tube-converter/parts/tube-converter/src/libparabolic/src/models/downloadmanager.cpp(186:21) `size_t Nickvision::TubeConverter::Shared::Models::DownloadManager::startup()`


(org.nickvision.tubeconverter.gnome:5168): Gtk-ERROR **: 22:33:55.718: failed to add UI: .:37:1 Invalid object type 'AdwSpinner'
Trace/breakpoint trap (core dumped)
$

**Comment by nlogozzo** [comment]
@soumyaDghosh seems like it wasn't solved....

**Comment by soumyaDghosh** [comment]
> @soumyaDghosh seems like it wasn't solved....

No, I told you it wasn't... And also, they're not listening to me. I tried to poke them around.... To push it from edge to stable, but here they goes!

**Comment by soumyaDghosh** [comment]
@Edgar-67 if you do this, are still getting error?


`sudo snap refresh gnome-46-2404 --edge`

**Comment by Edgar-67** [comment]
I still have the problem after launching the last order

massimo@massimo:~$ sudo snap refresh gnome-46-2404 --edge
[sudo] Mot de passe de massimo : 
gnome-46-2404 (edge) 0+git.c309eb7 from Canonical✓ refreshed

massimo@massimo:~$ snap run tube-converter
[INFO] Started GTK application.
file: /build/tube-converter/parts/tube-converter/src/org.nickvision.tubeconverter.gnome/src/application.cpp(30:26) `int Nickvision::TubeConverter::GNOME::Application::run()`

Gsk-Message: 07:32:55.594: Failed to realize renderer of type 'GskNglRenderer' for surface 'GdkX11Toplevel': OpenGL ES 3.0 n’est pas pris en charge par ce moteur de rendu.


(org.nickvision.tubeconverter.gnome:3581): Adwaita-WARNING **: 07:32:56.416: AdwNavigationPage 0x62f0fba7ad90 is missing a title. To hide a header bar title, consider using AdwHeaderBar:show-title instead.

(org.nickvision.tubeconverter.gnome:3581): Adwaita-WARNING **: 07:32:56.417: AdwNavigationPage 0x62f0fbb645b0 is missing a title. To hide a header bar title, consider using AdwHeaderBar:show-title instead.
[INFO] Connected to Linux taskbar.
file: /build/tube-converter/parts/tube-converter/src/libparabolic/src/controllers/mainwindowcontroller.cpp(240:25) `Nickvision::App::WindowGeometry Nickvision::TubeConverter::Shared::Controllers::MainWindowController::startup(const std::string&)`

[INFO] Loaded 0 historic download(s).
file: /build/tube-converter/parts/tube-converter/src/libparabolic/src/models/downloadmanager.cpp(176:21) `size_t Nickvision::TubeConverter::Shared::Models::DownloadManager::startup()`

[INFO] Found 0 recoverable download(s).
file: /build/tube-converter/parts/tube-converter/src/libparabolic/src/models/downloadmanager.cpp(186:21) `size_t Nickvision::TubeConverter::Shared::Models::DownloadManager::startup()`


(org.nickvision.tubeconverter.gnome:3581): Gtk-CRITICAL **: 07:32:56.613: Unable to register the application: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.19" (uid=1000 pid=3581 comm="/snap/tube-converter/current/usr/lib/org.nickvisio" label="snap.tube-converter.tube-converter (enforce)") interface="org.a11y.atspi.Socket" member="Embed" error name="(unset)" requested_reply="0" destination="org.a11y.atspi.Registry" (bus)

(org.nickvision.tubeconverter.gnome:3581): Gtk-CRITICAL **: 07:33:04.189: Unable to register the application: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.19" (uid=1000 pid=3581 comm="/snap/tube-converter/current/usr/lib/org.nickvisio" label="snap.tube-converter.tube-converter (enforce)") interface="org.a11y.atspi.Socket" member="Embed" error name="(unset)" requested_reply="0" destination="org.a11y.atspi.Registry" (bus)

(org.nickvision.tubeconverter.gnome:3581): Gtk-ERROR **: 07:33:04.389: failed to add UI: .:37:1 Invalid object type 'AdwSpinner'
Trappe pour point d'arrêt et de trace (core dumped)

**Comment by nlogozzo** [comment]
The next update will revert back to Gtk.Spinner and fix the crash

**Comment by nlogozzo** [comment]
[V2024.11.1](https://github.com/NickvisionApps/Parabolic/releases/tag/2024.11.1) is here with a fix for this issue!
