### ISSUE TITLE
Quality setting reset to max when we set language

### ISSUE THREAD

**Issue by Philetjosie** [NickvisionApps/Parabolic#954]
I usually do not use max. quality when downloading for my projector.
I noticed that when I set quality to 1024x1920, and then I go to the next menu to set the audio language, then the film quality is switched back to max quality. 
If i do not make film quality setting at the end, the value I choose is always reset to max.
Its a really small bug for a really great software !
Thanks.

**Comment by nlogozzo** [comment]
[V2024.11.1](https://github.com/NickvisionApps/Parabolic/releases/tag/2024.11.1) is here with a fix for this issue!
