### ISSUE TITLE
Update `yt-dlp` to `2024.11.18`

### ISSUE THREAD

**Issue by nlogozzo** [NickvisionApps/Parabolic#956]

**Comment by barracuda156** [comment]
@nlogozzo Could we have a micro-release for Parabolic too? Otherwise patches on top of main from next are huge.

**Comment by nlogozzo** [comment]
@barracuda156 Once I fix #954 I plan on releasing an update

**Comment by nlogozzo** [comment]
[V2024.11.1](https://github.com/NickvisionApps/Parabolic/releases/tag/2024.11.1) is here with a fix for this issue!
