### ISSUE TITLE
Hide history when disabled in settings, adapt font sizing to other pages

### ISSUE THREAD

**Issue by therichkid** [NickvisionApps/Parabolic#961]
Thank you for your amazing app and all the effort you put in!

I have two minor enhancement suggestions:

1. When disabling the history in settings by setting them to "Never", the history menu point has no functionality as it will always be empty. In this case, the history should be hidden from the menu.
2. Styling improvement: The font when no history is available is smaller than on other pages, e.g. keyring. It should be consistent over all pages.

**Comment by nlogozzo** [comment]
> When disabling the history in settings by setting them to "Never", the history menu point has no functionality as it will always be empty. In this case, the history should be hidden from the menu.

I don't think I will be implementing this because there really is no benefit from hiding it in the sidebar...there's plenty of room to keep it there.

> Styling improvement: The font when no history is available is smaller than on other pages, e.g. keyring. It should be consistent over all pages.

This I will fix

**Comment by nlogozzo** [comment]
[2024.12.0](https://github.com/NickvisionApps/Parabolic/releases/tag/2024.12.0) is here with a fix for this issue!

**Comment by therichkid** [comment]
Thank you :)
