### ISSUE TITLE
Set repository browser URL in Weblate project

### ISSUE THREAD

**Issue by rffontenelle** [NickvisionApps/Parabolic#963]
[Repository browser URL](https://docs.weblate.org/en/latest/admin/projects.html#repository-browser) allows translators to browse the source code when translation specific string in the exact file and line. It's very useful to read the source and double-check the context.

Currently, App component doesn't have it set and Docs is broken.

```
https://github.com/NickvisionApps/Parabolic/blob/{{branch}}/{{filename}}#L{{line}}
```

Please set the above repository browser URL in both [App](https://hosted.weblate.org/settings/nickvision-tube-converter/app/#vcs) and [Docs](https://hosted.weblate.org/settings/nickvision-tube-converter/docs/#vcs) settings (link should go directly to the settings page)

**Comment by nlogozzo** [comment]
Done
