### ISSUE TITLE
Instagram download issue with Parabolic

### ISSUE THREAD

**Issue by Francehelder** [NickvisionApps/Parabolic#964]
If i download some reels of the same Instagram profile, Parabolic saves all this videos with the same name "Video by puttheusernamehere.mp4" by default.

This not happen when i use yt-dlp directly.

**Comment by nlogozzo** [comment]
Can you provide the links of the videos you are trying to download?

**Comment by Francehelder** [comment]
https://www.instagram.com/omarcosrossi/reel/DCMeqpzxIaR/
https://www.instagram.com/omarcosrossi/reel/C7uIXPSupTZ/

**Comment by nlogozzo** [comment]
> This not happen when i use yt-dlp directly.

What's the command you are using to download it from `yt-dlp` directly?

When I do `yt-dlp https://www.instagram.com/omarcosrossi/reel/DCMeqpzxIaR/` I get a file called `Video by omarcosrossi`, so same behavior as Parabolic.

**Comment by Francehelder** [comment]
> When I do yt-dlp https://www.instagram.com/omarcosrossi/reel/DCMeqpzxIaR/ I get a file called Video by omarcosrossi, so same behavior as Parabolic.

I get a file called `Video by omarcosrossi [DCMeqpzxIaR].mp4`

![image](https://github.com/user-attachments/assets/4f92a599-6e1a-4d62-a24a-7e215cbc7655)

**Comment by nlogozzo** [comment]
Exactly. 

But you said: "This not happen when i use yt-dlp directly."

**Comment by Francehelder** [comment]
But, isn't the same name. There a kind of video ID in the file name. Same ID is in the link itself.
This not appears when i use Parabolic. Every reels of that profile is saved com the same name. 
Remains only the last video downloaded. Every time i download, Parabolic overwrite the file.

**Comment by nlogozzo** [comment]
I made it so Parabolic will automatically include `[MEDIA ID]` to the end of the title when you validate a video by default. Other users can turn this feature off in Preferences, but it is on by default to follow `yt-dlp`'s default behavior as well.

**Comment by Francehelder** [comment]
Thanks!!

**Comment by nlogozzo** [comment]
[2024.12.0](https://github.com/NickvisionApps/Parabolic/releases/tag/2024.12.0) is here with a fix for this issue!
