### ISSUE TITLE
Restore Opening Parabolic with URLs from External Applications

### ISSUE THREAD

**Issue by nlogozzo** [NickvisionApps/Parabolic#974]
See #628

**Comment by nlogozzo** [comment]
https://github.com/user-attachments/assets/e63b1d98-cb3a-45be-b097-f513a9ce87f3

**Comment by pol5xc** [comment]
Thank you very much, I've just tested it on firefox and works great!

**Comment by d-k-bo** [comment]
I tried the build from https://github.com/NickvisionApps/Parabolic/actions/runs/12319043850, but unfortunately, it doesn't seem to support DBus Activation anymore/yet (see the original issue #628).

**Comment by d-k-bo** [comment]
Unfortunately, it doesn't work yet.

When using the `org.freedesktop.Application.Open` method, the DBus service crashes with exit code 134.

Example¹:

```python
#!/usr/bin/env python3

import dbus

if __name__ == "__main__":
    bus = dbus.SessionBus()
    proxy = bus.get_object(
        "org.nickvision.tubeconverter", "/org/nickvision/tubeconverter"
    )
    open = proxy.get_dbus_method("Open", "org.freedesktop.Application")
    open(["https://youtu.be/8eXj97stbG8"], {})
```
Output of `/usr/bin/flatpak run --branch=master --arch=x86_64 --command=/app/lib/org.nickvision.tubeconverter/org.nickvision.tubeconverter.gnome org.nickvision.tubeconverter --gapplication-service` (which is also executed by the DBus service)¹ after the invokation of the above script:
```
(org.nickvision.tubeconverter.gnome:2): GLib-GIO-CRITICAL **: 19:52:47.147: g_file_get_uri: assertion 'G_IS_FILE (file)' failed
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string: construction from null is not valid
```
---

I noticed that when I start Parabolic with `--gapplication-service`, it already activates the application (which results in a window being opened). AFAICT, other apps run silently in the background in this case — until they are either activated via DBus or a timeout passed.¹

---

¹ adapted from the previous issue

**Comment by nlogozzo** [comment]
With this build: https://github.com/NickvisionApps/Parabolic/actions/runs/12322014414

I am getting `dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Remote peer disconnected`, but then `/usr/bin/flatpak run --branch=master --arch=x86_64 --command=/app/lib/org.nickvision.tubeconverter/org.nickvision.tubeconverter.gnome org.nickvision.tubeconverter --gapplication-service` works fine...

Could you try?

Sorry I never really understood any of this dbus stuff.

**Comment by d-k-bo** [comment]
This time it crashes with a SIGSEGV without logging any extra errors.

> I am getting dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Remote peer disconnected

This is because the flatpak/parabolic process crashes. The above command is normally executed by the dbus broker. When executed, the window shouldn't open (be activated) yet, instead it should only be activated when either `org.freedesktop.Application.Activate` or `org.freedesktop.Application.Open` is called.

This can be simulated by running the command manually and then calling the DBus method via the above python script.

---

I will take a look at the code tomorrow, maybe I can spot the error.

**Comment by nlogozzo** [comment]
I have an idea on what is causing the segfault...but I have a question. Is GApplication.Activate called when GApplication.Open is called as well?

**Comment by nlogozzo** [comment]
Try this build: https://github.com/NickvisionApps/Parabolic/actions/runs/12326547417

I believe it should be fixed now

**Comment by nlogozzo** [comment]
THIS BUILD ACTUALLY FIXES IT https://github.com/NickvisionApps/Parabolic/actions/runs/12331345594

**Comment by d-k-bo** [comment]
I can confirm that it works! :tada:

> Is GApplication.Activate called when GApplication.Open is called as well?

The application is either started via the GApplication.Activate or the GApplication.Open signals. If it is started via GApplication.Open, GApplication.Activate isn't called. The behaviour introduced in 600aefb is exactly what is required here. Well done and thank you for your work.

**Comment by nlogozzo** [comment]
Thank you for working through the issue with me!

2024.12.0 is ready to go! Will release a stable update now :)

**Comment by nlogozzo** [comment]
[2024.12.0](https://github.com/NickvisionApps/Parabolic/releases/tag/2024.12.0) is here with a fix for this issue!

**Comment by OwlRoyalty** [comment]
@nlogozzo Any way to make it work on Windows 11? 

One easy and convenient possibility is by using `URL/URI Scheme links` like for example: 

`parabolic://https://www.youtube.com/watch?v=43R9l7EkJwE`

I managed to get the scheme working but only opens Parabolic's main window, but doesn't trigger the add new download dialog with the link from the scheme. 

Maybe I need to pass a custom parameter? Like for example:
`parabolic://url=https://www.youtube.com/watch?v=43R9l7EkJwE`


---
To Enable the `parabolic://` URL Scheme on Windows 11. Create a `Parabolic.reg` file with the code:
``` 
[HKEY_CURRENT_USER\SOFTWARE\Classes\parabolic]
@="URL:parabolic"
"URL Protocol"="Nickvision Parabolic Protocol"

[HKEY_CURRENT_USER\SOFTWARE\Classes\parabolic\DefaultIcon]
@="C:\\Program Files (x86)\\Nickvision Parabolic\\Release\\org.nickvision.tubeconverter.winui.exe,0"

[HKEY_CURRENT_USER\SOFTWARE\Classes\parabolic\shell]

[HKEY_CURRENT_USER\SOFTWARE\Classes\parabolic\shell\open]

[HKEY_CURRENT_USER\SOFTWARE\Classes\parabolic\shell\open\command]
@="\"C:\\Program Files (x86)\\Nickvision Parabolic\\Release\\org.nickvision.tubeconverter.winui.exe\" \"%1\""
```
Run or double click the `Parabolic.reg` file. This will add the entries to the Registry Editor `regedit.exe`.  And now the `parabolic://` URL Scheme should be available to use in any Web Browser or external App.

**Comment by nlogozzo** [comment]
Can you create a new feature request issue with this information so I dont loose track?

**Comment by nlogozzo** [comment]
I see you did already, never mind thank you!
