### ISSUE TITLE
Unable to build parabolic on Ubuntu 24.04

### ISSUE THREAD

**Issue by jhonny-oliveira** [NickvisionApps/Parabolic#975]
Hi!

I'm attempting to build parabolic as part of my opensource initiative (https://xtradeb.net) and eventually publish it to Debian. I managed to build version 2024.5.0 with .Net by caching all nuGet dependencies and ship them with the source upload. This cache amounted to an unnecessary binary of 150MB, but now with version 2024.10.1 and with the libnick dependency, this seems to become larger than 500MB.

In addition, running "vcpkg install boost-date-time gtest libnick qtbase qtsvg qttools" is failing with:

```
-- Building x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: /usr/bin/make V=1 -j 7 -f Makefile all
    Working Directory: /ws/build/xtradeb/2404/apps/parabolic/parabolic/vcpkg/buildtrees/libpq/x64-linux-dbg/
    See logs for more information:
      /ws/build/xtradeb/2404/apps/parabolic/parabolic/vcpkg/buildtrees/libpq/build-x64-linux-dbg-out.log
      /ws/build/xtradeb/2404/apps/parabolic/parabolic/vcpkg/buildtrees/libpq/build-x64-linux-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_make.cmake:136 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_make.cmake:2 (vcpkg_build_make)
  ports/libpq/portfile.cmake:140 (vcpkg_install_make)
  scripts/ports.cmake:196 (include)


error: building libpq:x64-linux failed with: BUILD_FAILED
See https://learn.microsoft.com/vcpkg/troubleshoot/build-failures?WT.mc_id=vcpkg_inproduct_cli for more information.
```

```
In file included from ../../src/include/postgres.h:46,
                 from hashfn.c:24:
../../src/include/utils/elog.h:79:10: fatal error: utils/errcodes.h: No such file or directory
   79 | #include "utils/errcodes.h"
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [<builtin>: hashfn.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:19: all] Error 2
```

These are the pacakges I have instaled to support vcpkg: "sudo apt install curl zip unzip tar git bison libltdl-dev python3-jinja2 autoconf-archive flex libpg-query-dev". I also tried postgresql-server-dev-all and postgresql-server-dev-16.

Even if it is possible to overcome this issue, would it be possible to patch the source to allow libnick to build from Ubuntu system packages?

Potentially, this would enable me to build both libnick and parabolic using system packages and avoid shipping huge cache binaries with the source.

Thank you!
Jhonny Oliveira

**Comment by nlogozzo** [comment]
vcpkg is not required to build libnick and Parabolic. As long as you have all of the dependencies manually installed, they will find them in the system and build.

**Comment by jhonny-oliveira** [comment]
Thank you @nlogozzo !

I managed to make some progress. Unfortunately, not completely successful.

I packaged libnick, maddy and libxml++-5.0. Not that I fancy packaging dependencies...

Then, I built parabolic, but the build is not entirely successful. Occasionally, it breaks around 69%, but it succeeds most of the times.
Unfortunately, these are not all the bad news. When I install the package, I always get this error:

```
$ /usr/lib/x86_64-linux-gnu/org.nickvision.tubeconverter/org.nickvision.tubeconverter.gnome 
[INFO] Started GTK application.
file: ./org.nickvision.tubeconverter.gnome/src/application.cpp(30:26) `int Nickvision::TubeConverter::GNOME::Application::run()`

terminate called after throwing an instance of 'std::invalid_argument'
  what():  UI file not found: /usr/lib/x86_64-linux-gnu/org.nickvision.tubeconverter/ui/main_window.ui
Aborted (core dumped)
```

I guess, something is missing in the package. Doesn't get built...

These are both build logs: 
[parabolic_2024.10.1-1xtradeb1.2404.1_failed_build.txt](https://github.com/user-attachments/files/18048647/parabolic_2024.10.1-1xtradeb1.2404.1_failed_build.txt)
[parabolic_2024.10.1-1xtradeb1.2404.1_successful_build.txt](https://github.com/user-attachments/files/18048651/parabolic_2024.10.1-1xtradeb1.2404.1_successful_build.txt)

Once again, thank you!

**Comment by nlogozzo** [comment]
You are missing `blueprint-compiler`: https://jwestman.pages.gitlab.gnome.org/blueprint-compiler/

**Comment by jhonny-oliveira** [comment]
Great! It builds and installs now.

I also had to add aria2 as a dependency, otherwise, the options to add downloads were always greyed out.

These are the application loading logs:

```
$ /usr/lib/x86_64-linux-gnu/org.nickvision.tubeconverter/org.nickvision.tubeconverter.gnome
[INFO] Started GTK application.
file: ./org.nickvision.tubeconverter.gnome/src/application.cpp(30:26) `int Nickvision::TubeConverter::GNOME::Application::run()`

MESA: error: ZINK: failed to choose pdev
libEGL warning: egl: failed to create dri2 screen

(org.nickvision.tubeconverter.gnome:3476): Adwaita-WARNING **: 19:21:42.293: AdwNavigationPage 0x5da4d67acd80 is missing a title. To hide a header bar title, consider using AdwHeaderBar:show-title instead.

(org.nickvision.tubeconverter.gnome:3476): Adwaita-WARNING **: 19:21:42.295: AdwNavigationPage 0x5da4d689cff0 is missing a title. To hide a header bar title, consider using AdwHeaderBar:show-title instead.
[INFO] Connected to Linux taskbar.
file: ./libparabolic/src/controllers/mainwindowcontroller.cpp(235:25) `Nickvision::App::WindowGeometry Nickvision::TubeConverter::Shared::Controllers::MainWindowController::startup(const std::string&)`

[INFO] Loaded 0 historic downloads.
file: ./libparabolic/src/models/downloadmanager.cpp(166:21) `void Nickvision::TubeConverter::Shared::Models::DownloadManager::loadHistory()`

[INFO] Configuration saved.
file: ./libparabolic/src/controllers/mainwindowcontroller.cpp(322:21) `void Nickvision::TubeConverter::Shared::Controllers::MainWindowController::onConfigurationSaved()`

[INFO] Uninhibited system suspend.
file: ./libparabolic/src/controllers/mainwindowcontroller.cpp(338:29) `void Nickvision::TubeConverter::Shared::Controllers::MainWindowController::onConfigurationSaved()`

```

These are the build depends:
```
Build-Depends: debhelper-compat (= 13),
               cmake,
               libboost-json-dev,
               libcurl4-openssl-dev,
               libssl-dev,
               libglib2.0-dev,
               libsecret-1-dev,
               libgtk-4-dev,
               libboost-date-time-dev,
               libgtest-dev,
               blueprint-compiler,
               libnick-dev,
#               qtbase5-dev,
#               libqt5svg5-dev,
#               qttools5-dev,
#               libgdk-pixbuf-2.0-dev,
               libadwaita-1-dev,
               libxml++5.0-dev,
               libaria2-0-dev
```

These are the package depends:

```
Depends: ${misc:Depends}, ${shlibs:Depends},
         gnome-icon-theme, aria2,
         yt-dlp
Suggests: vlc
```

If you think this is all good and will go ahead and publish it for Ubuntu 24.04 and 24.10.

I could also at some point try to build both gnome and qt, but then, we would probably need to build both at the same time and break the package into something like this: parabolic-common, parabolic (gnome) and parabolic-qt.

Thank you!

**Comment by nlogozzo** [comment]
> If you think this is all good and will go ahead and publish it for Ubuntu 24.04 and 24.10.

It also required `ffmpeg`. But idk if that is already a dependency of `yt-dlp`. Otherwise, looks good to me!
