### ISSUE TITLE
Program suddenly unable to authenticate any Youtube URL

### ISSUE THREAD

**Issue by TheInsane101** [NickvisionApps/Parabolic#978]
This might be my favourite Youtube downloader ever! However, this happened out of the blue: entering in ANY Youtube video link, even if fully public and unrestricted, gives me an error when trying to authenticate it. Funnily enough, links from the web archive still work (the only other link I tried). I did not change Parabolic's settings whatsoever before or after this error started occurring, and reinstalling the program didn't fix the issue. 

Here's the error:

https://github.com/user-attachments/assets/ad1fbbd1-e7c2-40ef-94e5-56d656d6dd01

I am still unable to download any Youtube videos due to this error. Any assistance would be appreciated.

**Comment by nlogozzo** [comment]
Is this Windows 10 or actually Windows 7?

**Comment by nlogozzo** [comment]
Do you use the Cookies File or Cookies from Browser option?

**Comment by TheInsane101** [comment]
> Do you use the Cookies File or Cookies from Browser option in the app's settings?

It's always been cookies from Firefox

**Comment by nlogozzo** [comment]
What if you change it to None and try to download something?

**Comment by TheInsane101** [comment]
Okay it works now! Thank you so much! Why did keeping the Firefox cookies enabled work before and suddenly stop working?

**Comment by nlogozzo** [comment]
> Why did keeping the Firefox cookies enabled work before and suddenly stop working?

By using cookies, you associated using Parabolic with your YouTube account attached to the cookies. 

Google eventually catches on and can block your YouTube account from accessing the videos.

Just a question however...where you manually uploading a `Cookies File` to Parabolic? or did you have `Cookies from Browser` selected to `Firefox`?

**Comment by TheInsane101** [comment]
> Just a question however...were you manually uploading a `Cookies File` to Parabolic? or did you have `Cookies from Browser` selected to `Firefox`?
The latter.
