### ISSUE TITLE
The resolution at start up always defaulting to best

### ISSUE THREAD

**Issue by subhasutra** [NickvisionApps/Parabolic#979]
There was an issue from last year that was closed, which said the behaviour would be to remember the last used resolution. However when "mp4 (video)" is selected, the quality at start up is always set to "Best", regardless of what resolution has last been used. I am using the flatpak version, so I was wondering if I am missing some permission perhaps that is causing this?

One more issue I have faced is, when the crop thumbnail for audio is selected in settings, every thumbnail is cropped, even if video is selected in file type.

**Comment by nlogozzo** [comment]
[2024.12.0](https://github.com/NickvisionApps/Parabolic/releases/tag/2024.12.0) is here with a fix for this issue!

**Comment by subhasutra** [comment]
Thank you!
