### ISSUE TITLE
no subtitles in the last release

### ISSUE THREAD

**Issue by sellige00** [NickvisionApps/Parabolic#985]
[V2024.12.0]
Hi 
I downloaded https://www.arte.tv/fr/videos/031583-000-A/la-main-au-collet/
For audio "en" , for subtitles "fr"
Via VLC, there is no track with subtitles 

I tested with another video (from arte), same problem

Is it due to the new release? it was ok with the previous one

In options "include generated subtitles" is ticked

Thank you for your software

**Comment by nlogozzo** [comment]
I have found the fix! Expect an update by the end of the week!

**Comment by sellige00** [comment]
Thank you!

**Comment by nlogozzo** [comment]
[V2024.12.1](https://github.com/NickvisionApps/Parabolic/releases/tag/2024.12.1) is here with a fix for this issue!
