### ISSUE TITLE
NickVision Parabolic shuts down when attempt to validate link

### ISSUE THREAD

**Issue by Maanyaaz** [NickvisionApps/Parabolic#989]
The PC has Windows 10 Home
Version22H2
OS build 19045.5247
Experience Windows Feature Experience Pack 1000.19060.1000.0
System Type 64 bit operating system, x64 based processor
RAM 16 GB
Parabolic version - 2024.12.0
I have attached the video to demonstrate the issue. 

https://github.com/user-attachments/assets/0e021b3f-9f7b-462a-a2b9-18c8bc11916e

**Comment by Maanyaaz** [comment]
Does this have to do anything with the vcpkg and cmake? 
![image](https://github.com/user-attachments/assets/09235380-a9c4-43b9-8527-31d0faea8f0f)

**Comment by nlogozzo** [comment]
Did you build Parabolic manually? How did you install it?

**Comment by nlogozzo** [comment]
If you used the installer, what path did you install Parabolic to?

**Comment by nlogozzo** [comment]
Can you try the new version of Parabolic as well? https://github.com/NickvisionApps/Parabolic/releases/tag/2024.12.1

**Comment by Maanyaaz** [comment]
Hello. So the same issue is with the new version too. I tried installing the program in both c and d drives and had no success. 
For the new version this was the path I used - C:\Program Files (x86)\Nickvision Parabolic
I have not built it manually yet. I asked the person who introduced me to Parabolic and they say that I need a particular .net version?

**Comment by Maanyaaz** [comment]
Oh and to specify I am from New Zealand, dunno if there are any issues with the location.

**Comment by nlogozzo** [comment]
> I asked the person who introduced me to Parabolic and they say that I need a particular .net version?

This is incorrect. New versions of Parabolic are now written in `C++`. `.NET` is no longer required.

> Oh and to specify I am from New Zealand, dunno if there are any issues with the location.

This could be the issue. Does it crash with no matter what video you try? What if you try to validate something that is not from YouTube...i.e. DailyMotion, Vimeo, etc...

**Comment by Maanyaaz** [comment]
Yes its doing the same with the other platforms too.

**Comment by nlogozzo** [comment]
Hmm...it seems as if you don't even have `yt-dlp` bundled with Parabolic.

Do you use an antivirus software? If so, which one?

**Comment by Maanyaaz** [comment]
I was using express vpn but i have uninstalled it for now

**Comment by nlogozzo** [comment]
> I was using express vpn but i have uninstalled it for now
> 
> 

Did Parabolic work previously when you had express VPN?

Sounding more and more like this could be a location issue.

**Comment by nlogozzo** [comment]
Either way, Parabolic should handle these crashes and display an error instead of crashing.

**Comment by Maanyaaz** [comment]
so curious thing is that other downloaders like 4k are also not working. i did have an external f drive that got corrupted and i am wondering if something happened then.

**Comment by nlogozzo** [comment]
Hmm, could be. Did you ever have yt-dlp installed on said F drive? Maybe Parabolic is pulling it from there and crashing because there is an issue.

**Comment by Maanyaaz** [comment]
When i execute the yt-dlp i get this 
![image](https://github.com/user-attachments/assets/a2a51500-5d6b-4751-a983-f98bdcbe0a93)

**Comment by nlogozzo** [comment]
That's fine. Does `4K Downloader` say anything when it doesn't work?

**Comment by Maanyaaz** [comment]
Nope. T_T

**Comment by nlogozzo** [comment]
Hmm...I don't know what this issue could be...but maybe try a clean install of Windows if everything is broken.

**Comment by Maanyaaz** [comment]
I will try.

**Comment by nlogozzo** [comment]
Will do

**Comment by Maanyaaz** [comment]
Hi, I dont know what i did but this is what i am getting now - 
![image](https://github.com/user-attachments/assets/1693f280-09e7-4260-8196-c1ac6ac87d9f)

**Comment by Maanyaaz** [comment]
ok, i think i figured it out. Had to go in "The PC" section and manually change the location of the downloads, music and videos folders. 
![image](https://github.com/user-attachments/assets/de90e53d-b751-4448-8cf7-ba017e1bf865)
![image](https://github.com/user-attachments/assets/1741a0a4-e8ba-4546-bbf4-5991a640c8b2)

**Comment by nlogozzo** [comment]
> Had to go in "The PC" section and manually change the location of the downloads, music and videos folders from F to D drive.

Ah that explains it. Parabolic by default tries to download to your downloads folder and well if the F drive is corrupted then that why it crashed. 

> except the ones with warnings of inappropriate for users

This is expected. It is an issue with yt-dlp itself nothing I can fix.

Closing the issue for now, let me know if you have any other issues.

**Comment by Maanyaaz** [comment]
Will do. Thank you.
