### ISSUE TITLE
Download in 4K

### ISSUE THREAD

**Issue by blatantthrowaway** [NickvisionApps/Parabolic#991]
I don't  see an option to download videos in 4K. The one I attempted to download has a 4K version on Yt, but it only downloads in 1080p.

**Comment by blatantthrowaway** [comment]
Nvm I figured it out. I changed the requested codec from any to H.264

**Comment by nlogozzo** [comment]
I am reopening this because it is an issue. 

If you have `Any` preferred codec selected then Parabolic should use all available codec and have 4K listed.

**Comment by nlogozzo** [comment]
![image](https://github.com/user-attachments/assets/7f1503f6-f157-4a08-befc-c70d42f49f8c)

I have `Preferred Video Codec` set to `Any` and 4K resolution shows. Can you provide me with the URL of the video you were trying to download?

**Comment by blatantthrowaway** [comment]
I don't see any of this on the Windows version.

**Comment by nlogozzo** [comment]
Okay this is the Windows version:
![image](https://github.com/user-attachments/assets/d6c31716-181c-4fdc-900b-96ffe38260e9)

4K is still there with `Preferred Video Codec` set to `Any`.

**Comment by nlogozzo** [comment]
What is the video URL you are using?

**Comment by blatantthrowaway** [comment]
It's with any video. I've tried many 4K videos

**Comment by nlogozzo** [comment]
Can you give me the URL of one?

**Comment by blatantthrowaway** [comment]
https://www.youtube.com/watch?v=YTepdzA8fco&ab_channel=InteractiveMenus%26SceneAccess

**Comment by blatantthrowaway** [comment]
This is all I see. How do I get that detailed menu that you showed?
https://github.com/user-attachments/assets/4e49ac5f-86fd-4f3d-9c57-f9fcb945a06a

**Comment by nlogozzo** [comment]
Ah, it seems as if you have `Download Immediately After Validation` switched on for some reason. 

Click the settings page at the bottom and you should see it there and uncheck it and then try again.

**Comment by blatantthrowaway** [comment]
That did it thanks you.
