### ISSUE TITLE
App throws error when quality option is set other than 'Best'

### ISSUE THREAD

**Issue by elio567** [NickvisionApps/Parabolic#994]
When quality is set not on 'Best' even when is set on highest option or there is only one available, downloading ends with 'ERROR: Requested format is not available. Use --list-formats for a list of available formats'

TikTok: all?  e.g https://www.tiktok.com/@fcbarcelona/video/7449411739558399265
Instagram: some  https://www.instagram.com/sainer__/reel/BMM1jeMhO-f/

(when set on 'Best' download is completed, but thumbnails aren't deleted)

checked with yt-dlp where was fine

OS: Ubuntu 24.10
Parabolic: 2024.12.1

**Comment by nlogozzo** [comment]
[V2024.12.2](https://github.com/NickvisionApps/Parabolic/releases/tag/2024.12.2) is here with a fix for this issue!
