### ISSUE TITLE
Don't want to launch (Win11)

### ISSUE THREAD

**Issue by OkaXo** [NickvisionApps/Parabolic#996]
Hello,

  Since an update, the application won't launch. I've tried uninstalling it, installing different versions but nothing. 
  
  The hourglass appears for 3 seconds to load the application, but nothing appears and no error message. 

Thank you for your help

**Comment by nlogozzo** [comment]
You are trying to reinstall the latest [V2024.12.1](https://github.com/NickvisionApps/Parabolic/releases/tag/2024.12.1), correct?

What if you try [V2024.12.0](https://github.com/NickvisionApps/Parabolic/releases/tag/2024.12.0)? No luck starting either?

**Comment by nlogozzo** [comment]
Did Parabolic crash when you tried downloading something before you installed the update?

**Comment by OkaXo** [comment]
when I had started the application it had detected an update that I made. Strangely enough, at the end of the update, when the application restarted, it still found an update that I had made, and then it was impossible to relaunch the application. and no error message.

I've uninstalled the application thoroughly and reinstalled several recent and older versions and it's still the same. with the portable version unzipped on the desktop it's the same. antivirus disavowed and no firewall. when I launch the EXE there's the spinner for 3 seconds then nothing and no error message.

I can't find anything else to try.

**Comment by ViBE-HU** [comment]
Could you please check event logs? Check the Applications section for error logs.

https://learn.microsoft.com/en-us/shows/inside/event-viewer

**Comment by OkaXo** [comment]
Nom du journal :Application
Source :       Application Error
Date :         24/12/2024 11:04:32
ID de l’événement :1000
Catégorie de la tâche :Événements d’arrêts inattendus d’applications
Niveau :       Erreur
Description :
Nom de l’application défaillante org.nickvision.tubeconverter.qt.exe, version : 0.0.0.0, horodatage : 0x6764795c
Nom du module défaillant : MSVCP140.dll, version : 14.29.30133.0, horodatage : 0x60ff28cc
Code d’exception : 0xc0000005
Décalage d’erreur : 0x0000000000013020
ID du processus défaillant : 0x0x5B10
Heure de début de l’application défaillante : 0x0x1DB55EB3A2D3B9D
Chemin d’accès de l’application défaillante : C:\Users\Desktop\NickvisionParabolic_V2024.12.1_Windows.zip\org.nickvision.tubeconverter.qt.exe
Chemin d’accès du module défaillant: C:\WINDOWS\SYSTEM32\MSVCP140.dll
ID de rapport : b14474d0-2591-4e36-9b1b-9d6c0cf87b59
Nom complet du package défaillant : 
ID de l’application relative au package défaillant : 
XML de l’événement :
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" Guid="{a0e9b465-b939-57d7-b27d-95d8e925ff57}" />
    <EventID>1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8000000000000000</Keywords>
    <TimeCreated SystemTime="2024-12-24T10:04:32.1812391Z" />
    <EventRecordID>445121</EventRecordID>
    <Correlation />
    <Execution ProcessID="3396" ThreadID="12948" />
    <Channel>Application</Channel>
    <Computer>DESKTOP-R16ALEU</Computer>
    <Security UserID="S-1-5-21-2122029079-657380300-9730156-1001" />
  </System>
  <EventData>
    <Data Name="AppName">org.nickvision.tubeconverter.qt.exe</Data>
    <Data Name="AppVersion">0.0.0.0</Data>
    <Data Name="AppTimeStamp">6764795c</Data>
    <Data Name="ModuleName">MSVCP140.dll</Data>
    <Data Name="ModuleVersion">14.29.30133.0</Data>
    <Data Name="ModuleTimeStamp">60ff28cc</Data>
    <Data Name="ExceptionCode">c0000005</Data>
    <Data Name="FaultingOffset">0000000000013020</Data>
    <Data Name="ProcessId">0x5b10</Data>
    <Data Name="ProcessCreationTime">0x1db55eb3a2d3b9d</Data>
    <Data Name="AppPath">C:\Users\Franck\Desktop\NickvisionParabolic_V2024.12.1_Windows.zip\org.nickvision.tubeconverter.qt.exe</Data>
    <Data Name="ModulePath">C:\WINDOWS\SYSTEM32\MSVCP140.dll</Data>
    <Data Name="IntegratorReportId">b14474d0-2591-4e36-9b1b-9d6c0cf87b59</Data>
    <Data Name="PackageFullName">
    </Data>
    <Data Name="PackageRelativeAppId">
    </Data>
  </EventData>
</Event>

**Comment by OkaXo** [comment]
after seeing the errors in the log, I reinstalled microsoft visual c++ 2015 redistributable and the application launches but with a strange interface.
![Capture d'écran 2024-12-24 113358](https://github.com/user-attachments/assets/398a851d-a60c-4a9f-96a6-1fa946f15093)

**Comment by nlogozzo** [comment]
This is the new interface introduced in V2024.12.0
