### ISSUE TITLE
Soundcloud download produces m4a if opus is selected

### ISSUE THREAD

**Issue by BuZZ-dEE** [NickvisionApps/Parabolic#999]
I would like to download the following:

https://soundcloud.com/raversreunited/al-storm-mc-finchy-ravers-reunited-ravers-goes-bonkers-2021

as opus file.

![Bildschirmfoto vom 2024-12-25 02-27-08](https://github.com/user-attachments/assets/96ef0cc0-f5e5-431e-babd-e8044ae6a310)

As a result I get:

Al Storm & MC Finchy - Ravers Reunited: Ravers Goes Bonkers 2021 [1181789425].m4a

**Comment by nlogozzo** [comment]
[V2024.12.2](https://github.com/NickvisionApps/Parabolic/releases/tag/2024.12.2) is here with a fix for this issue!

**Comment by BuZZ-dEE** [comment]
@nlogozzo It works. Thank you.
